* ffmpeg (capture command)
** ffmpeg -video_size 1024x768 -framerate 23 -f x11grab -i :0.0+0,0 -f pulse -ac 2 -i default output.mkv
*** Flood messages of "Past duration ... too large" maybe solved by decreasing or changing -framerate
*** https://trac.ffmpeg.org/wiki/Capture/Desktop (appropriate link)
*** pactl list short sources
**** This will display all pulseaudio devices
** ffmpeg -video_size 1024x768 -framerate 23 -f x11grab -i :0.0+0,0 -f pulse -ac 2 -i 1 output.mkv (new command with 1 instead of "default")
** BASICS:
* ffmpeg (splitting/cutting)
** https://superuser.com/questions/140899/ffmpeg-splitting-mp4-with-same-quality

#+begin_src shell

  ffmpeg -i largefile.mp4 -t 00:50:00 -c copy smallfile1.mp4 \
  -ss 00:50:00 -c copy smallfile2.mp4

  # ===== how to remember
  # -input
  # -time =
  # -copycopy =
  # -splitstart = 
  # -copycopy =

#+end_src
** 
* ffmpeg (basic video rescale)
*** ffmpeg -i DSCF9322.MOV -crf 25 -vf scale=1280:-1 new.mp4
*** https://trac.ffmpeg.org/wiki/Scaling
*** https://trac.ffmpeg.org/wiki/Encode/VP9
* ffmpeg (speedup, maybe for kodland)
** https://itnext.io/speedup-ffmpeg-without-compiling-from-source-code-c1f34d4ec544
* ffmpeg (crop)
** https://shotstack.io/learn/crop-resize-videos-ffmpeg/
* ffmpeg (concatenate, very COOL)
** https://stackoverflow.com/questions/7333232/how-to-concatenate-two-mp4-files-using-ffmpeg
*** concat demuxer
**** (most files used by general users do not support file-level concatenation).
 $ cat mylist.txt
 file '/path/to/file1'
 file '/path/to/file2'
 file '/path/to/file3'

$ ffmpeg -f concat -safe 0 -i mylist.txt -c copy output.mp4
* ffmpeg (rotate using transpose)
** https://www.baeldung.com/linux/ffmpeg-rotate-video
*** ffmpeg -i input.mp4 -vf "transpose=0" output_0.mp4
* ffmpeg (downloading from sharepoint)
** https://www.lisenet.com/2022/how-to-download-view-only-teams-meeting-recording-video-from-sharepoint/
#+begin_quote

$ ffmpeg -i "some-link" -codec copy video.mp4

#+end_quote
* yt-dlp, firefox or any other browser
#+begin_quote

yt-dlp -f mp4 --write-sub  --cookies-from-browser firefox <url>

#+end_quote
golang magik brainfudge zig 
* sudo dpkg -l *ogre*
** Need to rewrite this, check for existing libraries
* for pulseaudio settings
** after installing pulseaudio-equalizer

qpaeq # ========== to change eq settings
pulseaudio --kill && pulseaudio --start # ========== to restart and read settings
* Swapfile:
** ubuntu 22 needs swapfile for hibernation, coz with no swap file big enough, cant hibernate.
** [[https://dev.to/dansteren/ubuntu-2204-hibernate-using-swap-file-1ca1][example]]
** [[https://www.stefanproell.at/posts/2022-11-01-fde-hibernate/][link above forgot to include how to edit the grubfile]]
* decrypt:
** [[https://unix.stackexchange.com/questions/749766/best-way-to-encrypt-a-file-with-just-password-no-keypairs-that-is-easily-usabl][easiest way for our passes]]
** Or easier still, sure only 80%:
#+begin_src shell

  gpg -c passes.txt

#+end_src
** decrypting it back
#+begin_src shell

  gpg --decrypt <encrypted_file>

#+end_src
* Most Linux uses xrandr connect to external monitor. This is likely an X11 thing. The following works like magic
#+begin_quote

xrandr --query
xrandr --output DP-1 --same-as eDP-1
xrandr --output DP-1 --auto --right-of eDP-1

#+end_quote
* using inotifywait
** using it with my Sphinx projects
#+begin_quote

inotifywait -m -e modify,create,delete source/index.rst | while read path action file; do   sphinx-build -M html source outputdir; done

#+end_quote
* Latex
** This requires installation of all base, font and extras (latex)
#+begin_quote

pdflatex <somefile>.tex

#+end_quote
