* Latah:
** https://www.tandfonline.com/doi/abs/10.1080/01639625.1997.9968043?journalCode=udbh20
** Personal notes:
*** Reading about Latah, and anthropology has made me realize a few things.
*** That many "half-savage" cultures, having Shamans in common (what Malays refer to as Bomoh), also grant powers not just to positions but also to certain words. Where certain curse words or rude words or words with spiritual meaning will have such incredible power as to be able to trigger a certain trance state upon the receiver/listener of such word. Apparently, some latah-like startles across many cultures also can be triggered by such words. Makes me realize another important role of "more progressive" forms of art in society. To remove the magical power imparted upon certain curse words. In this sense, art is truly rational.     
* Tigers love Durian! (Golden, a chance to be offensive)
** https://archive.org/details/studiesinbrownhu00clifrich/mode/1up
*** Maybe the alien can actually taste durian for the first time. 
*** Maybe the alien can start a planetary invasion with the humans for this peculiar fruit
*** Hang on there, were going too far
*** An alien battling a tiger for durian?
* Betel nut still exists and are still a danger to certain isolated regions of Asia.
* A malay man Pandak Aris cursing the Sakai's who "betrayed" him to the fifth and sixth generation
* A warm blowing upon his face which almost deprived him of reason
* The Spirit of The Tree:
** tree-felling...It is a healthy form of exercise, and it kept Trimlett's muscles in good trim for the occasional rough-and-tumbles in which he was called upon to engage with Chinese coolies. The Malays put it down to drunkenness, that useful explanation, which, to the native mind, accounts for 90% of the incomprehensible eccentricities of the White Men... 
** Note: even in todays interconnected gloabalized world, I have seen malays who still think this way. God, the Malays are doomed!
