* What I wish I knew before I started attempting to work in a tech startup company (Malaysia)
** That while University education generally is the fault. Malay controled Universities are the worst culprit. Becoz they are primarily at fault in creating the bubbles of students not communicating with the outside world, and that the "culture" of these Universities have transformed into Datuk-worshipping institutions, with each Datuk creating their own mini-cults, and the students are there to feed the egos of Uni lecturers. There are some (exceptionally) uncorrupted lecturers, but usually few and far in between. 
** That I wished I learnt early the power of Git tools as a version control tool. While they are not taught in many programming schools, in the workplace they are considered indispensable. In fact, they are considered the only way to move forward in managing codes submitted by mutliple programmers. 
*** With regards to this point, I am now so comfortable with Git, that I use them even when writing non-programming related stuff like articles. Of course, this does not include branching strategies under Git, which is a subject in and of itself. I would recommend thos to anyone, even budding developers who think they do not need such tools, perhaps thinking it would be a waste of time and mental energy. Not only will you love Git, it will make transitioning to Git GUI clients easier (such as SourceTree), which i strugged with horribly during my first experience in a tech startup. In fact, for Linux users like myself, I recommend staying away from Git clients until you try simple Git with your personal bash scripts. 
** When applying to work for a tech startup company. 99% of the time, they will always expect their new staff to develop the same set of skills, which is knowledge or basic knowledge of a LAMP stack and Javascript. The platforms are specific and dont differ much, unless you really hunt for a niche company. 
** I wished that I learnt Javascript on my own, and it doesnt have to be in Web development. For example, I wished I couldve pursued a mixture of Photoshop and Photoshop scripting, coz apparently Photoshop can also use Javascript for creating powerful scripts shortcuts. This is a lot more fun than struggling within Web development. 
** Most developers are arrogant intelligent men. If youre thinking youre arrogant, and then be prepared for some roughening, and youll be horribly shocked. But also be prepared to be humiliated, coz these men have undergone their arrogant developer phase, and went through a lot. I wish I knew this. 
** I wished I knew many Linux Youtubers such as Brodie Robertson and DistroTube. They have countless (and I mean COUNTLESS) videos on software reviews, including those related to Git and IDE's, and those outside of typical development. You would never be able to finish watching their videos. Plus they are all free!
** I wished I discovered Emacs early on. As it is now my favourite IDE. In fact, it is more than just an IDE, as the typical Emacs user literally lives inside the Emacs. You could use it for example, to write notes in the fantastic .org format (some kind of native Emacs format). The typical Emacs user also switches modes every time he switches, for example, from programming in Javascript, to programming in Powershell, to writing notes in .org mode. Emacs uses a kind of "package manager" to list all modes that can be installed (there are hundreds of these). And enabling these is a matter of memorizing the appropriate keyboard shortcuts. 
** 

