Progressive:
* Bands list:
** Karnivool
** Pendragon
** Of The I
** Rishloo
** Dream Theater
** Like Thieves
** Soen
** Sylvan
** Porcupine Tree
** The Butterfly Effect
** Steven Wilson
** Tool
** Polyphia
** CHON
** Ling Tosite Sigure
** Periphery
** Dead Letter Circus
** Tesseract
** Twelve Foot Ninja
** Protest The Hero
** Pain of Salvation
** Veil of Maya
** Leprous
** Devin Townsend
** Oceans Ate Alaska
** Northlane
** Jinjer
** Opeth
** Circa Survive
** Arcane
** Breaking Orbit
** Haken


Time to manage my mess of a prog music history. The categories are just personal, nothing theoretical:
** Entry-level, or immediately accessible beauty. Prog-music I put here, are either entry-level in that it can immediately hook virgin ears to the beauty of Prog Rock, or can be immediately beautiful in its lush landscape and layers of sounds. This could also be due to more modern sound technology, which enables even wackier sounds to be achieved by modern prog. Not necessarily more mainstream than the next category, as some bands thrive on complex layers alone (rather than complex progression.)
*** Karnivool
*** Dream Theater
*** Like Thieves
*** Soen
*** Ling Tosite Sigure
*** Dead Letter Circus
*** Leprous
*** Devin Townsend (Devin Townsend are a hit and miss for me, they know how to write amazing stuff, but can never understand why some of their guitar riffs sound very non-progressive)
*** Northlane (metalcore but utilizes atmospheric sound for the soft parts, and even their heavy riffs are tastfully paced to complement a lush sonic landscape)
*** Breaking Orbit (promising sound, a bit of a lightweight among most prog in this list, but I like variety)


** Double-take. Prog-music I put here, may require more experienced listeners, and are not apparently as beautiful as the prior category. Sometimes the landscape of its sound is not as complex or layered, and in some cases, the sonic landscape is almost mainstream as its true beauty lies in its more progressive harmony, melodies and counter-melodies (such as Circa Survive), and rhythmic progression. Older prog that belong here can also easily mistakenly be grouped together with its more mainstream peers of the time due to older hardware that sound similar to younger listeners. Highly conceptual albums also may belong here, where the whole works better than the pieces (Sylvan, for example)
*** Pendragon
*** Of The I
*** Rishloo
*** Like Thieves
*** Tesseract
*** Soen
*** Sylvan
*** Porcupine Tree
*** The Butterfly Effect
*** Steven Wilson
*** Tool
*** Periphery (In your face prog-metal, that sounds very mainstream metal at first listen, but grows on you)
*** Pain of Salvation
*** Veil of Maya (a bit too hardcore for my poor ears, but still an amazing sound)
*** Oceans Ate Alaska
*** Opeth (popular among older prog fans, personally I prefer their more slower pieces, as well as the whole Heritage album)
*** Circa Survive (I like their melody a lot, and some of their songs also have counter-melody)
*** Arcane (a big name among Aussie prog fans, perhaps the most inaccessible of prog in this list, the newer concept album "Known/Learned" is highly recommended. These guys are not in your face in the slightest, with a sound that really grows on you)

** Others, bands here I dont know where to put. Some here are not prog, but still deserves to be considered special.
*** Polyphia (instrumental)
*** CHON (instrumental)
*** Twelve Foot Ninja (hilarious band)
*** Protest The Hero (massive punk attitude, but more than just another punk band)
*** Jinjer (A female vocal screaming like a male is highly unexpected, but more than that, this is just a powerful nu-metal)



 Ad-hoc:
* From o'brother (Lay Down), drum beats
** 1-2-3-4-5-6-7-8 |-|-|-|-|-|-|-|
*** bb|s|-|-|s|-|-| 
*** As a general 8/4 is considered good as a landscape-y beat for rock
*** Everything is either detail or beat in the general structure of music (not to be confused with "fillers")
*** the 'bb' in this case os the detail despite, bass as a fundamental beat
* Circa Survive (Schema), drum beats
** 1-2-3-4-5-6
*** metric modulation!!
*** 1-2-3 4-5-6
*** .3--| .3--|
*** the dot decoration is like acciacatura (crushed note)
* Half-baked idea:
** general staccato beat is (Mozart-like?, and happy), beat-up-beat-up-up, making a well-blended fusion, requires more hinting, so double up (up-up) is not necessary, so it becomes beat-up only (make sure of context first)
* Chopin:
** Nocturne:
*** Not a play on rhythm memory, but note memory. A very unusual technique indeed.
