#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="zoho_ticket.css" />
#+OPTIONS:  toc:nil num:nil ^:nil


* Reminder
*** remember, you made the FUCKING d minor prelude??
* What to do today:
** Send CVs by beating Applicant Tracking System using this link: https://resumecaptain.com/
** Randomizer
#+begin_src lisp

  (make-list 10 2)

  (setq var1 (-cons*
              "we need to bind ;b to sly-mode parenthesis, Emacs versor, emacs built-in profiler, edebug, apropos, macro expansion, advising system, indirect buffers, etc."
              "DB history, Emacs code compass, BACKUP our data, magit, DB or vector for our persistent highlgiats"
              "email, CV, also Audiosockets, https://vfunction.com/blog/3-tier-application/, do a Gtest for C++"
              "we do use this link http://programarcadegames.com/index.php?lang=en&chapter=introduction_to_animation with our game, ur graphql link history"
              "attention is all you need (transformer model), RISC-v, ISA, Haskell"
              "crochet, Hanifas health, code generation (internet of bugs), ambiguity in corpo legal terms"
              "try Razvan article on creating portabl GEntoo on USB, commit your treesitter.so in user-emacs-directory coz its pretty safe unless your changing architecture completely, https://www.datacamp.com/blog/docker-projects"
              "url practices in ~/my-trash/delete/stupidNotion/README.org, STEAM, how banks or best practices for race condition"
              (append
               (make-list 3 "Qt practice")
               (make-list 2 "boppps")
               (make-list 4 "drawing")
               )
              ))

  (nth (random (length var1)) var1)


  ;; testing our url randomizer


  (defun ardie1()
  (interactive)
  (org-copy-subtree)
  (let (
        (ardie/org-random-list (butlast (split-string (substring-no-properties (current-kill 0)) "\n")))
        )
    (message
     (nth (random (length ardie/org-random-list)) ardie/org-random-list)
     )))

#+end_src
** rsync:
#+begin_quote



rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/Documents /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/Desktop /media/ardie/ardie-back-2025/


rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/emacs-python-workspace /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/emacs-gforth-workspace /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/emacs-go-workspace /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/emacs-csharp-workspace /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/emacs-lisp-workspace /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/Music /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/my-trash /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/my-emacs-29-config/tree-sitter /media/ardie/ardie-back-2025/

# ==================================================
watch out for the different flag, a flag removed
# ==================================================

rsync -avzh --delete --max-size='400M' --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/.profile /home/ardie/.bashrc  /media/ardie/ardie-back-2025/my-hidden-shell-profiles/

rsync -avzh --delete --max-size='400M' --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/.bash_history  /media/ardie/ardie-back-2025/my-hidden-shell-profiles/.bash_history_$(date +%Y-%m-%d)



#+end_quote
** Emacs
**** We need this for our battery somehow:
#+begin_quote

var1=`upower -i /org/freedesktop/UPower/devices/battery_BAT1 | awk '/perc/{print $2}'`; if [ ${var1%?} -gt 100 ]; then echo "haha"; fi

zenity --info --text="Process complete!"

#+end_quote
**** We need to this cool advicing
#+begin_src emacs-lisp

    (defun foo ()
    (print "asd")
    )


  (defun my-foo-advice ()
    "My advice for `foo`."
    ;; Example of around advice logic
    (with-output-to-temp-buffer "testest"
      (switch-to-buffer "testest")
      (insert "hello there")
      )
    )


  (defun my-advice (num &optional character)
    "My advice for `foo`."
    ;; Example of around advice logic
    (set-cursor-color "#000000")
    )

    (set-cursor-color "#e52b50")

(my-advice)

  (foo)

  (with-output-to-temp-buffer "testest"
    (switch-to-buffer "testest")
    (insert "hello there")
    )


  (advice-add 'foo :after #'my-foo-advice)
  (advice-add 'foo :after #'my-advice)


(self-insert-command )

#+end_src
**** We also need to simplify our ;;t (sexp hydra)
**** we should really do bindings for our Bash too, so it works in 42kl. This works temporarily, in our terminal session, so we can put this inside our .profile
***** https://unix.stackexchange.com/questions/604703/bash-bind-command-not-working-with-alt-key-combination
#+begin_quote

bind '"\ea": backward-char'
bind '"\ee": forward-char'
bind '"\C-a": backward-word'
bind '"\C-e": forward-word'

#+end_quote
**** We need to advice our hydra/ our self-insert so that the variable ardie/right-char-count gets unset again
***** https://www.reddit.com/r/emacs/comments/rlli0u/whats_your_favorite_defadvice/
**** We need to write these down somewhere
#+begin_quote

Can you guess what are these? (illegal):
- foo() ()
- foo() []
- foo[] ()


Can you guess what are these (legal):
- int (* fun())()
- int (* fun()) []
- int (*foo[])()
- int foo[][]

  also read this link: https://stackoverflow.com/questions/20617067/returning-function-pointer-type

  https://www.tutorialspoint.com/cprogramming/c_return_pointer_from_functions.htm

#+end_quote
**** write abou this one
#+begin_src c++

  void foo(char* someString);

// both behave similar
foo(&someString)
foo(someString)



// Not sure if C++ can do this
// but pointers are so important, you can pass a double pointer in C
// (privately, we can call them pointer-pointer, for our childish brain)

void foo(int** array) // passing a double pointer
{
    //....
    *array = theNewCollection;
    //...
}

#+end_src
**** [[https://protesilaos.com/codelog/2024-01-29-emacs-prefix-map/][defining new prefix map]]
**** we check all our hydras, to have all of our keys intact, along with -a -e shortcuts.
***** this gets easily complicated, so for our word-hydra, we are going to replace arrow keys <up><down> with -p and -n
***** if we are going to remove -b and -f as much as possible, we need to do something about capitalize and upper
***** ... so for word-hydra, we remove hydra-p and replace it with hydra-d
***** ... then p can become uppercase, coz we never do line movement for word
**** Learning Rogue-like game using these link:
***** [[https://www.reddit.com/r/roguelikedev/comments/1o5sw2d/any_good_resources_for_making_a_roguelike_in_c/][good resources]]
***** [[https://itch.io/jam/7drl-challenge-2025][7DRL challenge]]
***** [[https://github.com/libtcod/libtcod][libtcod]]
***** [[https://www.roguebasin.com/index.php/Complete_roguelike_tutorial_using_C++_and_libtcod_-_part_1:_setting_up][complete tutorial]]
***** [[https://libtcod-tutorials.gitlab.io/tutorial-pages/tutorials/tutorial-0/][more links]]
***** [[https://libtcod.readthedocs.io/en/latest/guides/getting-started.html][getting started]]
***** [[https://www.roguebasin.com/index.php/Complete_Roguelike_Tutorial,_using_python%2Blibtcod][python and libtcod]]
**** we should also try [[https://orgmode.org/manual/Speed-Keys.html][speed keys]]
**** We should really try [[https://github.com/winterTTr/ace-jump-mode][ace jump mode]], Reddit post mentions the guy uses arrow keys as a "smell" that there's a better way to navigate
**** C-mouse-9 ignores instrucion to checkout to "work and fuzz" if theres a conflict file (example: theres a file in fuzzing but not in working). We need a prompt/dialog/buffer/feedback to show the conflict coz we spent an hour hunting for this elusive problem
**** IMPORTANT: we need a multi cursors for word select
**** our Emacs company mode needs fixing, but not urgent. The Esc must escape suggestions (like in our cpp )
**** math in games
***** https://www.mathnasium.com/math-centers/richmondwest/news/role-mathematics-gaming-rw
***** https://gamedesignskills.com/game-development/video-game-math/
***** https://www.reddit.com/r/gamedev/comments/12nd3a/what_math_concepts_have_you_found_to_be_most/
***** https://pikuma.com/blog/math-for-game-developers
***** https://scenegraph.academy/article/why-is-math-needed-for-games-development/
***** https://www.gamedeveloper.com/programming/mathematics-in-videogames
***** https://www.effortlessmath.com/blog/how-math-skills-give-players-a-competitive-edge-in-various-online-games/
**** we need to read all this links on C++ I guess:
***** https://www.syncfusion.com/succinctly-free-ebooks/cplusplus/pointers-references-and-const-correctness
***** https://www.embeddedrelated.com/showarticle/1651.php
***** Also, on MOC objects, whats all that about
**** CONCEPTUAL!
***** We need to recognize other workflows that use a before-after value. So it can also be intuitively added like our (ardie/add-to-special-abbrev)
**** We made another one!! Open a file at random
#+begin_src emacs-lisp



  (let ((ardie/files-i-want (directory-files-recursively "/home/ardie/Documents/my_notes/my-org-files/" "\\.org\\'")))
  (nth
   (mod (random (current-time-string) ) (length ardie/files-i-want))
       ardie/files-i-want)
  )

#+end_src
**** https://gcore.com/learning/how-to-install-mate-on-ubuntu
**** We need to try and write about Doom Emacs, and a little about Spacemacs
**** Solve the Lubuntu keyboard shortcuts once and for all
***** create randomizer of opening one of my notes upon Emacs startup
***** 
**** More cool Emacs functions, might be too much at this point:
#+begin_src emacs-lisp

  ;; ==========
  ;; Edit: actually, we have a different idea. We found this magic trick, we have to make it more clever:
  ;; find-file-at-point 
  ;; ==========

  (defun
      ardie/open-current-file ()
    (interactive)
    (find-file (current-kill 0 t))
    )


#+end_src
**** We need to JUST practice our eLisp skill by adding random pairs for specific modes. (Clue, this will make our understanding defer eval, or lazy eval, slightly more epic)
**** emacs how to put org mode options in separate file
**** For writing more efficiently in org-mode
#+begin_src emacs-lisp


    (defhydra my-test-hydra 
      (:color purple)
      "my super test"
      ("/"
       (progn
         (org-end-of-line)
         (org-meta-return)
         )
       :exit t))

    (define-minor-mode my-test-mode
      "A minor mode so that my key settings override annoying major modes."
      :init-value nil
      :global nil
      :lighter " my-test"
      :keymap (let ((map (make-sparse-keymap)))
                (define-key map
                            (kbd "//")
                  'my-test-hydra/body) map))

  (add-hook 'ardie/special-org-hook #'my-test-mode)

#+end_src
**** TODO Important, to test cascade deletes
***** Story, we have a system that stores students and their departments. Here are the details.
***** Joint Degree Program: A student enrolled in a combined Bachelor of Science in Mechanical Engineering and Bachelor of Science in Electrical Engineering program.
***** Instead of cascaded deletes, it if we delete mechanical engineering department, it replaces that students column with NULL values
#+begin_src sql

  CREATE TABLE employees (
  employee_id SERIAL PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  hire_date DATE DEFAULT CURRENT_DATE,
  salary NUMERIC(10, 2) CHECK (salary > 0),
  department_id INTEGER,
  CONSTRAINT fk_department
  FOREIGN KEY (department_id)
  REFERENCES departments (department_id)
  ON DELETE SET NULL
  );

  CREATE TABLE departments (
  department_id SERIAL PRIMARY KEY,
  department_name VARCHAR(50) UNIQUE NOT NULL
  );

#+end_src
**** We need to write a "separator function" that auto-separates a lne based in symbols, example:
#+begin_quote

#include <QMainWindow> -----into-----
#
include
<
QMainWindow
>

#+end_quote
**** Do we need this? Its Emacs hiding text being made professional
#+begin_src emacs-lisp

  (defun ardie/tell-face ()
  (interactive)
  (if
      (equal (face-at-point) nil)
      (setq ardie/current-face 'default)
    (setq ardie/current-face (face-at-point)) 
    )
  (setq our-foreground
	(face-attribute ardie/current-face :foreground))
  (print our-foreground)
  (setq our-background
	(face-attribute 'default :background))  
  (print our-background)
  )

(face-attribute 'font-lock-comment-face :background)



(setq default-background (face-attribute 'default :background)
      default-foreground (face-attribute 'font-lock-comment-face :foreground))

(defun disappear ()
  (interactive)
  (set-face-attribute ardie/current-face nil
              :foreground our-background))

(defun reappear ()
  (interactive)
  (set-face-attribute ardie/current-face nil
              :foreground our-foreground))

#+end_src
**** [[https://www.awseducate.com/student/s/content][AWS Educate]]
***** [[https://console.cloud.google.com/welcome/new?project=steel-fin-473905-g3&authuser=1][GCP google cloud]]
**** Holy SH*T again!!
#+begin_src emacs-lisp

  ;; inspired by https://endlessparentheses.com/ispell-and-abbrev-the-perfect-auto-correct.html


  ;; an idea is to use define-derived-mode to create a mode for safely writing in an overpowered mode

  (defun ardie/test()
    (interactive)
    ;; (print (substring-no-properties (ispell-get-word nil)))
    (if mark-active
        (let ((after (substring-no-properties (buffer-substring (region-beginning)(region-end)))))
          (exchange-point-and-mark)
          (pop-mark)
          (backward-char)
          ;; (ispell-get-word nil)
          ;; (print (word-at-point))
          (let ((before (substring-no-properties (word-at-point))))
            (define-abbrev xx-abbrev-table before after)
            ))
      (let ((after (substring-no-properties (word-at-point))))
        (backward-word)
        (backward-char)
        ;; (ispell-get-word nil)
        ;; (print (word-at-point))
        (let ((before (substring-no-properties (word-at-point))))
          (define-abbrev xx-abbrev-table before after)
          ))
      )
    )


  (setq xx-abbrev-table (make-abbrev-table ))

  (setq local-abbrev-table xx-abbrev-table)

#+end_src
**** we need to read stuff: Emacs autodocumentation on point
***** https://vxlabs.com/2016/04/11/step-by-step-guide-to-c-navigation-and-completion-with-emacs-and-the-clang-based-rtags/
***** https://github.com/dawsers/emacs-qthelp
***** https://fanpengkong.com/post/emacs-ccpp/emacs-ccpp/
***** https://lahtela.me/2020/05/21/setting-up-emacs-for-qt-development.html
**** We need to use an Ubuntu clipboardmanager with Emacs built in function (rather than Emacs kill ring), and post a video on that
***** No GUI manager:
#+begin_quote

sudo apt update
sudo apt install xclip xsel

#+end_quote
***** and use this:
#+begin_src emacs-lisp

  (require 'clip-mode)
  (setq clip-mode-functions '(clip-insert-selection-at-point)) ; Use for inserting text into Emacs
  (setq clip-selection-at-point-functions '(clip-get-selections)) ; Use for selecting text from Emacs

  ;; Optional: Bind keys for copy and paste (adjust as needed)
  (global-set-key (kbd "C-c y") 'clip-yank) ; Copy and yank the selection
  (global-set-key (kbd "C-c p") 'clip-paste) ; Paste the selection

#+end_src
***** Use a clipboard manager, which works with Emacs built in copy/paste, or create a more advanced function to show history or even paste specific items
#+begin_quote


sudo apt install copyq. 
sudo apt install gpaste. 


#+end_quote
**** We need to make this tool [[https://news.ycombinator.com/item?id=22129636][array-ify]]
**** We need a really cool markdown live preview that works, with eww
#+begin_src emacs-lisp



    (setq browse-url-browser-function 'eww-browse-url)



  ;;     (defun ardie1 ()
  ;;     (interactive)
  ;;     (shell-command-on-region (point-min) 
  ;;                              (point-max) 
  ;;                              "markdown"
  ;;                              "testest")
  ;; (with-current-buffer "testest"
  ;;       (html-mode))
  ;; (with-current-buffer "testest"
  ;;       (impatient-mode))
  ;;     )


  ;; (defun ardie1 ()
  ;; (i
   nteractive)
  (let ((ardie/current-buffer (buffer-name)))
    (shell-command-on-region (point-min) 
                             (point-max) 
                             "markdown"
                             "testest")
    (switch-to-buffer ardie/current-buffer)
    )
  (with-current-buffer "testest"
    (html-mode))
  (with-current-buffer "testest"
    (impatient-mode))


  )

#+end_src
**** We need to makea video about how we manage config safely, when we have multiple Emacs (Eg: 2 versions, and 1 on Windows), minimally without any additional installation, useful if our main config file is quite large
***** The error usually looks like C:\Users\<your_username>\AppData\Roaming\elpa not found
***** 
**** things we should consider wriing in our new YT video (Ultra-ergonomic directional buffer and window navigation, for distraction free writing and coding, conditional on hard-wiring your usage of Ctrl and Alt)
***** ideas for even more "distraction free" writing or coding 
***** as you notice, I also use both left and right Ctrl and Alt, Ctrl-w for example becomes (right)Ctrl-w, becoz thats better ergonomically
***** the hydra keys are mapped to my TODO file, and other important files
***** I have funny leading keys for my hydra
***** I also have hydra for selecting, killing lines, selecting functions, super cool, etc....
***** fuure consideraiont include epoxied flat beads instead of velcro, but I have trouble finding small and flat beads, coz the velcro absorbs dust easily
***** References: https://github.com/emacsorphanage/key-chord and https://www.johndcook.com/blog/2015/02/01/rare-bigrams/
**** we need to watch more Git videos, like [[https://www.youtube.com/watch?app=desktop&v=NXaEImbo-n8&t=920s][this]], and systemcrafters vid on git reflog. Also, we faster diff checks inside Emacs. Make it EPIC!!
**** we need to do a command that copies from current buffer folder into other buffer folder, with confirm prompt from user
**** we need a "code as data" note/file
**** for C++, from this [[https://fanpengkong.com/post/emacs-ccpp/emacs-ccpp/][link]], we use this everyday, with try packages, until we are familiar, DONT use this until we figure which one uses the , we made it shorter these days.
#+begin_src emacs-lisp

  ;; from this point on, we deleted all :ensure t to avoid auto-installation
    ;; lsp
  (use-package lsp-mode
    :hook ((c-mode . lsp)
           (c++-mode . lsp)
           ;; (lsp-mode . lsp-enable-which-key-integration)
           )
    :commands lsp
    ;; :config
    ;; (setq lsp-keymap-prefix "C-c l")
    ;; (define-key lsp-mode-map (kbd "C-c l") lsp-command-map)
    ;; (setq lsp-file-watch-threshold 15000)
    )

  ;; (use-package lsp-ui
  ;;   :commands (lsp-ui-mode)
  ;;   :config
  ;;   (setq lsp-ui-doc-enable nil)
  ;;   (setq lsp-ui-doc-delay 0.5)
  ;;   (define-key lsp-ui-mode-map [remap xref-find-definitions] #'lsp-ui-peek-find-definitions)
  ;;   (define-key lsp-ui-mode-map [remap xref-find-references] #'lsp-ui-peek-find-references)
  ;;   )

  ;; (use-package lsp-ivy
  ;;   :commands lsp-ivy-workspace-symbol)

  ;; (use-package lsp-treemacs
  ;;   :commands lsp-treemacs-errors-list)

  ;; company
  (use-package company
    :bind ("M-/" . company-complete-common-or-cycle) ;; overwritten by flyspell
    :init (add-hook 'after-init-hook 'global-company-mode)
    :config
    (setq company-show-numbers            t
          company-minimum-prefix-length   1
          company-idle-delay              0.5
          company-backends
          '((company-files          ; files & directory
             company-keywords       ; keywords
             company-capf           ; what is this?
             company-yasnippet)
            (company-abbrev company-dabbrev))))

  (use-package company-box
    :after company
    :hook (company-mode . company-box-mode))

  ;; flycheck
  ;; (use-package flycheck
  ;;   :init (global-flycheck-mode)
  ;;   :config
  ;;   (setq flycheck-display-errors-function
  ;;         #'flycheck-display-error-messages-unless-error-list)

  ;;   (setq flycheck-indication-mode nil))

  ;; (use-package flycheck-pos-tip
  ;;   :after flycheck
  ;;   :config
  ;;   (flycheck-pos-tip-mode))

#+end_src
**** for more Emacs buffer ergonomic magic, also post in on Social Media
#+begin_src lisp

  (progn
    ;; http://xahlee.info/emacs/emacs/emacs_ido_setup.html
    (require 'ido)
    (ido-mode 1)
    ;; show choices vertically

    (setf (nth 2 ido-decorations) "\n")
    (setq ido-enable-flex-matching t)
    (setq ido-default-file-method 'selected-window)
    (setq ido-default-buffer-method 'selected-window)
    (setq max-mini-window-height 0.5))

  (defhydra my-b-hydra 
      (:color purple)
    "my switch to buffer"
    ("b" (progn (ido-switch-buffer)) :exit t))

  ;; ========== global goto1 minor mode for hydras.

  ;;;###autoload
  (define-minor-mode my-b-mode
      "A minor mode so that my key settings override annoying major modes."
    ;; If init-value is not set to t, this mode does not get enabled in
    ;; `fundamental-mode' buffers even after doing \"(global-my-mode 1)\".
    ;; More info: http://emacs.stackexchange.com/q/16693/115
    :init-value t
    :lighter " my-b"
    :keymap (let ((map (make-sparse-keymap)))
              (define-key map
                  ;; (kbd "C-c ;")
                  (kbd "; b")
                'my-b-hydra/body) map))

#+end_src
**** for our new Git worktree trick
#+begin_src lisp



      (global-set-key (kbd "C-<drag-mouse-8>") 'ardie/discard-unstaged-changes)
    (global-set-key (kbd "C-<mouse-8>") 'ardie/discard-unstaged-changes)

  (defun ardie/discard-unstaged-changes ()
    (interactive)

    (let
        ((current-branch (shell-command-to-string "git rev-parse --abbrev-ref HEAD")))
      (if (string-match-p "working" current-branch)
          (if (y-or-n-p "discard changes, sto restart from prev commit? (y or n) ")
              (let ((discard-change-output (shell-command-to-string "git checkout .")))
                (print discard-change-output))
            (print "action canceled")
            )
        (print "not working branch: nothing done")
        )
      )
    )  



  ;; ===== New: under test

  (defun ardie/project-save-all-buffers (&optional proj arg)
    "Save all file-visiting buffers in PROJ without asking.

  Falls back to `project-current' if PROJ is not specified."
    (let* ((proj (or proj (project-current)))
           (buffers (project-buffers (project-current))))
      (dolist (buf buffers)
        ;; Act on base buffer of indirect buffers, if needed.
        (with-current-buffer (or (buffer-base-buffer buf) buf)
          (when (and (buffer-file-name buf)   ; Ignore all non-file-visiting buffers.
                     (buffer-modified-p buf)) ; Ignore all unchanged buffers.
            (let ((buffer-save-without-query t))  ; Save silently.
              (save-buffer arg)))))))
  ;; ===== New: under test
#+end_src
***** Also in our attempt at improving further our powerful shortcuts and "no stash" workflow
**** Also for our rust-ts-mode:
#+begin_src lisp


    ;; ===== we no longer need rust-mode becoz we dont need rust-run
    ;; ===== we digged inside rust-run and discovered (compile) function used
    ;; ===== in most Emacs major programming modes

  ;; WRITE THESE SOME WHERE
  ;; ===== we unbound a key after a mistake
  ;; (fmakunbound 'my-rust-endline)
  ;; (unbind-key (kbd "RET") rust-ts-mode-map)

  (defun my-rust-endline ()
    (interactive)
    (insert ";")
    (newline)
    )

  (add-hook 'rust-mode-hook 'my-rust-endline)
  (add-hook 'rust-ts-mode-hook 'my-rust-endline)


  (define-key rust-ts-mode-map (kbd "C-<return>") 'my-rust-endline)


#+end_src
**** we need ;;h for select all, coz we still use it a lot for example in adding org-insert-structure-template
***** Also need indent-region hydra
**** we change add alternative to ;ii as highlight, coz swiper is messy
**** combobulate links:
***** [[https://sqrtminusone.xyz/configs/emacs/]]
**** we need to create a script that goes uses both next-logical-line and forward-word to copy, but we are only it works in web-mode
**** we need to really try javascript console in Emacs, we forgot where th link was
**** we should really explore combobulate to explore doing tricks in HTML and JAVSCRIPT, like moving a tree outside parent
***** moving everything outisde of any bracket
***** moving everyghing outside tag
***** but first start the experiment (and as practice), splitting the content into separate lines
**** we have to remap some of our Emacs hudra to mark-sexp. But only for Emacs29. Also we need modify our select line in hydra to save-excursion
**** we need a Emacs feature/mode that provides some cool jquery selector shortcut
**** we should really learn all the paredit tricks
**** there are several ways to exit hydras in fact, some more stable than others (becoz of nested hydras
***** [[https://emacs.stackexchange.com/questions/36597/returning-to-the-parent-hydra][link]]
***** [[https://emacspeak.blogspot.com/2020/09/emacs-paired-commands-efficient.html][repeatable hydra yank]]
**** Company mode readings:
***** [[https://www.reddit.com/r/emacs/comments/q8u2l4/unsetting_return_in_company_mode/][finally disabled company mode completion with better keybindings company-active-map]]
***** [[https://github.com/company-mode/company-mode/issues/640][variuos ideas of use-package for company-mode]]
***** [[https://company-mode.github.io/manual/Getting-Started.html#Usage-Basics][good verbose doc]]
**** We need to learn setting up opening module in Emacs rust. 
**** Read about elpy-rpc, and why do we have an elpy-rpc-buffer, it sounds cool but i dont know what its used for
**** more efficient faster completions for our Python, using this code, for now. We just need to set company-mode properly, and then use configs below from this [[https://github.com/joaotavora/eglot/discussions/1436][link]]
#+begin_src lisp


(use-package company
  :config (setq company-idle-delay 0
		company-minimum-prefix-length 1
		company-tooltip-align-annotations t))
(add-hook 'after-init-hook 'global-company-mode)
  
#+end_src
**** [[https://www.deusinmachina.net/p/tree-sitter-revolutionizing-parsing][parsing tree-sitter link]]
**** [[https://www.masteringemacs.org/article/combobulate-structured-movement-editing-treesitter][another one on tree-sitter]]
**** [[https://jackjamison.xyz/blog/emacs-garbage-collection/][garbage collection, basically to reduce stuttering]]
**** [[https://kitchingroup.cheme.cmu.edu/blog/2016/11/10/Persistent-highlighting-in-Emacs/][The Kitchin Research Group]]
**** [[https://github.com/rougier/svg-tag-mode][really cool, possible improvement to our html editing]]
**** [[https://github.com/io12/good-scroll.el][supersmooth scrolling]]
**** [[https://github.com/minad/org-modern][org-modern look]]
**** join multi into 1 without spaces
**** [[https://karthinks.com/software/fringe-matters-finding-the-right-difference/][another cool blog]]
**** We need to refactor error message of upload, what do we do with all the ID info?? Maybe theres no need for it.
***** create checks for duplicate events
***** we should add timestamp naming for CSV files
***** https://qwiet.ai/hacking-and-securing-python-applications/
**** Make sure you share-rate is above 3%
**** https://www.interview.micro1.ai/intro/micro1/?candidate=698fa6e4-4849-4b2a-90cf-db3e7d8d3816&ping=ok
**** Social media posting:
***** lvalue and rvalue:
****** Welp, my world just turned upside down for an hour or 2, and I read all over again, coz it turns out I was wrong about "string literals" being "not a real thing". Its actually a non-modifiable lvalue. LOL
****** Anyway, the reason why I think rvalue and lvalue is a much more useful mental model (but a bit of a leap for beginners) to understand C, instead "pointer pointing to protected parts of memory thingy", is becoz it would make sense as to why this example works
#+begin_src c

  char *firstPointer = "original";

  firstPointer = "we cjhange";

#+end_src
****** And this does NOT work:
#+begin_src c

  *firstPointer = "as";

#+end_src
****** I struggled with C random weirdness years, stayed away, combing back to C, after noticing "lvalue" and "rvalue" in the book "Expert C Programming: Deep C Secrets", made more sense.
****** Yeah, I know nobody reads stuff I write, and if they read, either dont understand, or disagree. But Im aiming for discoverability too. A few people now knows Emacs existence, now a few people knows the existence of lvalue and rvalue. So over a few days, Im gonna write snippets about this in different context under nerdy-stuff channel to avoid cluttering other channels
***** what is an lvalue and rvaluer
The reason why I believe lvalue and rvalue iots important to undertstand is because it would make sense of the many of the strange weirdness of C that "dont make sense", you will see this below.

It definitely has NOTHING to do with compile time and run time.

it may have something to do with what is an "expression"

Basically, in order for C to make sense from a semantic or syntax(?) we need these 2 terminology.

An lvalue are in the permanent part of memory, this is important so that it can exist beyond ats expression. Example: when the compiler sees a_variable = 42; the a_variable doesnt magically vanish beyond that line.

An rvalue are temporary values, non long term memory.

Now imagine on top of that, that lvalue is non-modifiable on top of being in persistent memory, and rvalue being temporary are also modifiable. C would not make any sense and collapse completely, and nothing would work.

So rvalues

ADD ABOUT LITERALS

First, before we dive into examples, what is an expression? (according to some articles I found)

Add another link that explains briefly what an expression is.

show examples here

- we finally understand rvalue and lvalue in C, and why ampersand (&) doesnt accept rvalue
- rvalue and lvalue has nothing to do with compile time and run time
- its actually has more to do with the semantics/syntax of the language (whatever)
- so assigning like this doesnt work because we are assigning to a "unmodifiable lvalue"
  #+begin_src c

    char avar[];
    avar = "hello"
        
  #+end_src
- while this works , because a pointer is a normal lvalue (lvalue is physical and modifiable)
  #+begin_src c

    char *avar;
    avar = "hello"    

#+end_src

# ==================================================  

Other instances of lvalue and rvalue
- we can do an expression like a_pointer + 4
- but we cant to an expression like &a_char_array+ 4
  #+begin_src c

        char achar[] = "hello there";
    char *tempPtr;
    tempPtr = achar;
    char *anotherPtr = tempPtr+4;
    *anotherPtr = '_';
    printf("%s", achar);

    

#+end_src
- we cant do this
  #+begin_src c

        char achar1[] = "hello there";
    char *tempPtr1 = &achar1+4;



***** lets read about Raylib
#+begin_quote


Several C implementations exist for generating and solving mazes, ranging from simple recursive backtracking to complex roguelike grid systems. Joe Wingbermuehle's 1999 maze.c uses a randomized depth-first search algorithm to carve paths through a grid, initializing the map with walls and recursively visiting unvisited cells to create a perfect maze. 

Maze Generation and Solving
Algorithm: The code typically initializes a grid filled with walls (1), then uses a recursive backtracking or "carve" function to remove walls (0) while moving in random directions until the entire grid is explored. 
Simulation: Advanced versions, such as those from Purdue University assignments, include functions to simulate an agent's movement through a generated maze based on a direction file, returning the number of steps or -1 if the path is invalid. 
Roguelike Style: Projects like "Decoded: Rogue" utilize K&R style C functions to handle data copying and maze structures, often employing a "cell" abstraction where walls occupy entire grid cells rather than single characters. 
Code Example (Simplified Recursive Backtracker)
A basic implementation initializes a 2D array, marks the start cell, and recursively visits neighbors to carve paths:

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define WIDTH 21
#define HEIGHT 21

// 1 = Wall, 0 = Path
int maze[HEIGHT][WIDTH];

// Function to check if a cell is valid and unvisited
int is_valid(int x, int y) {
    return (x > 0 && x < WIDTH - 1 && y > 0 && y < HEIGHT - 1 && maze[y][x] == 1);
}

// Recursive function to generate the maze
void generate_maze(int x, int y) {
    int dx[] = {0, 0, 2, -2};
    int dy[] = {2, -2, 0, 0};
    
    maze[y][x] = 0; // Mark current cell as path
    
    // Shuffle directions for randomness
    srand(time(NULL));
    
    for (int i = 0; i < 4; i++) {
        int nx = x + dx[i];
        int ny = y + dy[i];
        
        if (is_valid(nx, ny)) {
            maze[(y + dy[i] / 2)][(x + dx[i] / 2)] = 0; // Carve wall between cells
            generate_maze(nx, ny);
        }
    }
}

int main() {
    // Initialize maze with walls
    for (int y = 0; y < HEIGHT; y++) {
        for (int x = 0; x < WIDTH; x++) {
            maze[y][x] = 1;
        }
    }
    
    // Start generation from (1, 1)
    generate_maze(1, 1);
    
    // Print the maze
    for (int y = 0; y < HEIGHT; y++) {
        for (int x = 0; x < WIDTH; x++) {
            printf("%c ", maze[y][x] ? '#' : '.');
        }
        printf("\n");
    }
    
    return 0;
}

#+end_quote
***** this is VERY temporary for 42KL
#+begin_src emacs-lisp


  mkdir test0; chmod u=rwx,g=x,o=rx test0; touch -t "202606012047" test0; touch test1; truncate -s 4 test1; chmod u=rwx,g=x,o=r test1; touch -t "202606012146" test1; mkdir test2; chmod u=rx,g=,o=r test2; touch -t "202606012245" test2; touch test3; truncate -s 1 test3; chmod u=r,g=,o=r test3; touch -t "202606012344" test3; touch test4; truncate -s 2 test4; chmod u=rw,g=r,o=x test4; touch -t "202606012343" test4; ln test3 test5; chmod u=r,g=,o=r test5; touch -t "202606012344" test5; ln -s test0 test6; chmod u=rwx,g=rwx,o=rwx test6; touch -h -t "202606012220" test6

  (setq var1 "drwxrwxr-x")

  (defun mguser(avar)
    (interactive)
    (substring avar 1 4))

  (defun mggroup(avar)
    (interactive)
    (substring avar 4 7))

  (defun mgother(avar)
    (interactive)
    (substring avar 7 10))

  (defun getFullString(avar)
    (interactive)
    (concat
     "chmod "
     "u="
     (replace-regexp-in-string "-" "" (mguser avar))
     ","
     "g="
     (replace-regexp-in-string "-" "" (mggroup avar))
     ","
     "o="
     (replace-regexp-in-string "-" "" (mgother avar))
     )
    )

  (getFullString "drwxr-xr--")

  (current-kill 0 )




#+end_src
***** we might have to lower org-drill-learn-fraction to increase frequency of our org-drill
***** If you want to replace the keycaps on your PsychSparrow, look for sets explicitly labeled as "Low Profile MX-Compatible". Examples include:
****** XVX Horizon/ Womier Low Profile: These are widely available on Shopee and are designed with the MX cross-stem but a shorter height to avoid hitting the plate.
****** Keychron LSA Profile: These are high-quality PBT options available from Keychron Malaysia that fit cross-stem low-profile switches.
#+begin_quote

is womier 138 low profile r3 skyline keys compatible with armaggeddon psychsparrow

#+end_quote
***** a debugging framework in eLisp and Lisp, why is debugging so hard in Emacs and Lisp
***** the only thing you need to master Emacs is "highlight your text"
***** the real reason why we're changing is because I keep accidentally pressing M-v for scroll-down-command, so doing it this way feels like a lot of win
***** 2 recipes involving lovi lovi, or Flacourtia Intermis
****** https://yumpickles.wordpress.com/2012/02/24/lovi-lovi-flacourtia-inermis-pickle/
****** https://archwaytomomsgarden.blogspot.com/2014/10/lovi-chutney-sweet-sweet-lovi-chutney-i.html
***** we should also post about infra-sounds of AI data centers.
***** We need to post about 42KL somewhere in Facebook AND Developer Kaki
***** we need to practice typing using home rows: https://www.keybr.com/
****** lair liar line rail nail linen learn alien all real ill earlier
****** nail alien real lie lane lean learn 
***** https://www.coddykit.com/pages/blog-detail?id=512749
****** we need to read about code visualization
***** Dev Kaki
****** https://www.nvidia.com/gtc/?ncid=ref-inpa-296-prsp-en-gb-1-l11
****** select a session and STAY at least 5 minutes, and take a screenshot of u joining the session, and send to:
****** https://forms.gle/6bHa6ijhh15sgCwCA
***** [[https://dev.to/darkwiiplayer/an-introduction-to-coroutines-38i4][Introduction to coroutines (and stackful vs stackless)]]
****** dealing with terminoloy
****** coroutines: functions that can pause itself
****** there is caller and the callee, the caller CALLS the function, it EXECUTES, then RETURNS to the caller
****** coroutine: the caller CALLS the function, it EXECUTES, then YIELDS to the caller
****** what is YIELD?
****** Asymmetric coroutines: similar to functions, once it calls a function, control can only be returned from the function called. 
****** Basically: it cannot be RESUMED (from the ~top), only yielded to
****** Symmetriccoroutines: control can come from anywhere, we will call it TRANSFER
****** ----- continued -----
***** [[https://www.youtube.com/watch?v=H7c92T-megA][we need to learn about clothes]]
***** [[https://thephilosophicalsalon.com/avengers-and-the-endgame-of-liberalism/][WRITE about Avengers Endgame and the end of liberalism]]
****** https://www.thestranger.com/film/2018/04/27/26108191/a-fucking-liberal-is-the-villain-of-avengers-infinity-war
***** [[https://www.youtube.com/watch?v=hKHjH5OU7Eo][Artists dont follow rules]]
****** be delusional.
****** People go, "oh no, thats not realistic" - GOOD
****** "oh, thats not going to happen" - GOOD
****** And people are saying, "whats wrong with you" - Youre on the right track.
***** [[https://www.youtube.com/watch?v=lhwnOBjSklE][verbal orange cones]]
***** [[https://www.youtube.com/watch?v=J-SH18dtBlY][speech jammer]] 
***** https://www.youtube.com/shorts/bwAKNGgMKg0
***** mu4e
#+begin_quote



https://cachestocaches.com/2017/3/complete-guide-email-emacs-using-mu-and/

How to setup email in Emacs
-install mu (but mu is only for indexing and searchng emails)
-offlineimap (becoz mu needs another software to keep a local copy of ur emails)
-offlineimap can set up 2 emails (in the example, the guy sets a script to sync both emails every 5 minutes)
-the configs are stored inside  ~/.offlineimaprc
Concepts
--in that file, just like Git, there is a "named" local and remote repo of your email
--you can choose any folder
--you can can STORE YOUR PASSWORD, not recommended, usually under remotepass\
--we dont want that, so instead we can use Python and GPG
--"folderfilter" can filter folders, as well Googles bad default "All Mail/Important"
--to keep indexing we put "mu index" via postsynchook
--this is DONE, so we call offlineimap thatstarts a process and syncs every 5 min
--but this means leaving terminal open, so we start a daemon
--mu4e comes installed with mu (mu is the "real package", mu4e is the Emacs package that comes with it), we need to include mu4e path in our Emacs load-path
--in "headers", we have severl shortcu options
--by setting mu4e-contexts variable, we can make our mu4e aware of our email source, if its Gmail, the variable mu4e-trash-folder and mu4e-refile-folder is changed. So our delete commands for example, are context-aware
--he defines mu4e-refile-folder as a function, that filters using (cond) and (mu4e-message-field msg :subject) to check the message's subjct against a text and filters further more
--

mmu4e alert
-mu4e-alert-enable-mode-line-display calling this would update modeline with unread msgs
-which means we need to run-with-timer
-problem: mu4e maintains connection with server, which mu index will never (we NEVER get email updates)
-we solve this with mu4e~proc-kill
-we put all these all in use-package (as in example)
-we set variable mu4e-alert-interesting-mail-query for selective alerts, becoz Google being weird, marks all folders moved to trash as unread
-to send email we need SMTP, we set a bunch of SMTP parameters just our like Python Flask project. But we also have account specific parameters (we use setq for the SMTP, and mostly defvar for the account-spec)
-the my-mu4e-set-account function is to combine (set operation-ish) SMTP values and account-spec values,


https://www.macs.hw.ac.uk/~rs46/posts/2014-01-13-mu4e-email-client.html

-offlineimap mentioned above is a tool (offline) to sync copy. An alternative here is mbsync.
-just like before we are using symmetric encryption (one way, public key only). We create a dotfile, written in is our password, and generate a public key
-they both seem to use 2 different hooks
-there also some variables not used in previous article: mu4e-get-mail-command (here we set to a mbsync command) mu4e-html2text-command mu4e-update-interval mu4e-headers-auto-update mu4e-compose-signature-auto-include
-we got more commands here


  https://f-santos.gitlab.io/2020-04-24-mu4e.html

#+end_quote
***** [[https://www.youtube.com/watch?v=ZJ09dPNJ8G8][How programming jobs get created and destroyed]]
#+begin_quote

 
How IT/programmers jobs are actually created.

He hasnt worked in gaming indusrty and foesnt plan to

everything tech indusrty is largely custome in the last few decandes

the non tech is largely the same.

So all programming jobsh is largely between a speectrum and a slidin scale, mainigng old code and a new stratup (and everyinqg in between)

It was a lot like construction was, back before girders and planks were standardized, and construction used whatever resources they found at the time.

Nowadays, the analogy no loner works, becoz construction is mostly standardized, nad programming isnt (even for "big" companies)

what happend:

 - some gets an idea,
 - tis person, asometimes a solo entrpnour, getting money from investors, or gets money from a company
 - why is tis money allocated, somtimes company gets somuch money, they spend all that money on a new projec
 - this was true years ago, when programmer salaries were through the roof
 - if this is not true, the money is borrowed or from investors, who believe once the money is built, he gets the money back.
 - NOW, assuming the person with the idea isnt building it himeseves, he needs tecanical people. hires people as employees, and hires consultants from company that bulds sofware on demand.
 - in ideal worlds, the first person they hire is a senior tech person to plan stuff, and hire others.
 - mostly its not ideal, so they hire recruiter from the same or a consultant company. If the person hires full consultant company, they also look for more people by looking for recuiters themselves.
 - 

What spawned the leet-code interviews



#+end_quote
***** Be consistent like Louis Rossmann, how can we provide a counter-incentive structure to (the massive incentive use of) AI.
***** YouTubers who have no issue with long/fat functions. And even those who like functions chunky (I like em chunky too, wink, wink)
***** The #1 reason to use Emacs is to write a diary
***** Cool video on what compilers do behind the scenes, explained in a very friendly manner. Also, now that Im going down the rabbit hole of programming langs again. I just realized English as a language has a lot ambiguity in it. It is "easy" only becoz of its dominance, but its actually difficult to master from a non-native speaker, becoz theres a lot overloaded terms.
***** The bullshitness of supply and demand (write this in an org file)
***** "Public school is about education. It is NOT job training. And it should not be. Otherwise, the capitalists win." 
***** [[https://www.youtube.com/watch?v=w3krYEeqnyk&t=1214s][conquering kubernetes with Emacs]]
***** [[https://people.kernel.org/linusw/rust-in-perspective][rust in perspective, AMAZING history of languages]]
****** There are many illuminating quotes inside. But one particular interesting bit. How Niklaus Wirth (some creator of a language called Pascal), both critized C language. Something along the lines of "it gives the appearance of high level language while not behaving like 1". An example is how C has no "awareness" of array sizes and we are dealing with memory addresses. (This explains the weirdness of dealing with C++ in my own project, where appending new table rows, requires you to pass in as arguments, along the data, array size. You dont have this nonsense in Python). Of course, the benefit of having this low level of control, is that the pointer can refer to anything, register/RAM/etc. The kind of control that programmers love, giving some true hacking powers.
**** Jobs:
***** [[https://app.outlier.ai/en/expert][Outlier tasks]]
***** micro1
***** Interesting companies
****** PostCo: really likes open minded developers, who learn rare stuff. says want developers open to learning Ruby on Rails 
****** Hero Plus Group: uses Ruby in Rails. Specifically mentions Flask.
***** https://my.hiredly.com
***** https://www.maukerja.my/
***** https://www.jorawork.com/
***** https://www.ricebowl.my
***** Read about orchestration and automation
***** about Google cloud platforms: Snowflake and Databricks (good to have)
***** maybe SQL and Azure diffs
**** Emacs
***** We need to: how to get inline rust documentation in emacs without lsp server
***** We need to: what is the qch file format qt
***** Convincing others:
****** Non-destructive ways to test Emacs packages:
******* use the try package. Then do the usual use-package, or any normal config for that package you found online.
***** Also try Emacs Application Framework on a new laptop
***** You like trying cool custom personalized Emacs el. This one is useful simpler bookmark, might help a lot in you html editing: [[https://github.com/joodland/bm][here]]
***** we are professional, so we need to make Python SUBMIT to us. [[https://emacs.stackexchange.com/questions/3372/coloring-indentation-levels][Color diff indentation levels]]
***** web-mode-element-wrap must be hydra-ed. We also need to auto-select a whole delimiter. But first try the stackoverflow templating engine trick.
***** We need to learn this Emacs [[https://emacs.stackexchange.com/questions/23810/getting-proper-indentation-for-python-flask-templates][templating indent]] mode thingy
**** I read about ketamine, psilocybin and alcohol, and also neurotransmitter GABA
***** https://adf.org.au/drug-facts/ketamine/
***** https://www.psychologytoday.com/intl/blog/culturally-speaking/202312/the-magic-behind-the-molecules-psilocybin-vs-alcohol
***** https://my.clevelandclinic.org/health/articles/22857-gamma-aminobutyric-acid-gaba
****** Researchers are still studying the effects of increased level of GABA, for High blood pressure, Insomnia, Diabetes.
***** GABA presence in food:
******  kimchi, miso and tempeh
****** green, black and oolong tea
****** brown rice, soy and adzuki beans, chestnuts, mushrooms, tomatoes, spinach, broccoli, cabbage, cauliflower, Brussels sprouts, sprouted grains and sweet potatoes
**** [[https://ringgitplus.com/en/blog/income-tax/how-to-file-your-taxes-for-the-first-time.html][read on how to do e-filing for d first time]]
**** Read about your Hugo
***** Understand layouts and everything inside (partials, shortcodes, _default)
***** When you replaced your /layouts folder, it fails, simple rename back /_layouts
* Piano (no social media progress)
** You need to buy a stand
* MyKasih, SARA, MySTR
** https://bantuantunai.hasil.gov.my/2026/Identity/Account/Login
** https://checkstatus.mykasih.net/sara2/checkstatus
* More org notes
*** some YSAC u did before
*** your chocolate donut (combination of Jamie Olivers friend & Gordon Ramsay)
** For suit, call these numbers for material. (Mention that Sparkle, Lot L-D 1&2, Pudu Plaza, KL recommended these guys)
*** 011 70018033
*** 013 343 2049
*** 018 398 5048
* Address:
** G-12-30, BLOCK G MENTARI COURT Gate 1, Jalan PJS 8/9, Bandar Sunway, 46150 Petaling Jaya, Selangor, Malaysia
