#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="zoho_ticket.css" />
#+OPTIONS:  toc:nil num:nil ^:nil


* create a shortcut, for duplicating immediate line im on. no need for 3 actions of selecting, copy and paste, this is important in hydra
* create 2 more "themes"
* title window indicating runlias environment. thats pretty cool.
* we need to write or practice, whatever, quickly switching between proc and method
* The nature of documentation
** and also quickly switching between slots and shared variable
* What do we do right now
** finish a SystemCrafters video
** only glance ur previous notes
** research singapore for 10 minutes
* PNI
* What to do later
** Remember what Chomsky said
*** societies bans certain discussions on purpose to  keep the illusion  of freedom of discussion going. 
*** Most reporters worth their salt, take their job as a mostly a joke. They know the illusion of freedom of speech
*** remember, you made the FUCKING d minor prelude??
* What to do today:
** Remember you done it before, the kind of Sam Seder-ish intellect fuck-off, it feels right. 
** Put out the chicken
** Buy the battery frm Low Yatt
** wake up early, and go out early
