#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="zoho_ticket.css" />
#+OPTIONS:  toc:nil num:nil ^:nil


* create a shortcut, for duplicating immediate line im on. no need for 3 actions of selecting, copy and paste, this is important in hydra
* create 2 more "themes"
* title window indicating runlias environment. thats pretty cool.
* we need to write or practice, whatever, quickly switching between proc and method
* The nature of documentation
** and also quickly switching between slots and shared variable
* What do we do right now
** finish a SystemCrafters video
** only glance ur previous notes
** research singapore for 10 minutes
* PNI
* What to do later
** Remember what Chomsky said
*** societies bans certain discussions on purpose to  keep the illusion  of freedom of discussion going. 
*** Most reporters worth their salt, take their job as a mostly a joke. They know the illusion of freedom of speech
*** remember, you made the FUCKING d minor prelude??
* What to do today:
** Remember you done it before, the kind of Sam Seder-ish intellect fuck-off, it feels right. 
** you MUST go to the clinic/hospital for your throat
** Go to CIMB for checking of fiver attempt
* Piano (no social media progress)
** Bought a simple mask, not worth it,  painting it for now. I would most likely over-think it
** You need to buy a stand
** Post on FB after its done:
*** I did the mask experiment. Interesting reaction, Meleys especially, being the emotional creatures they are, wwere more likely to judge my music. I think Meleys will forever te emotional creatures till the end of time. Millions of years into the future
* More org notes
** For your recipes
*** Balti
*** some YSAC u did before
*** your chocolate donut (combination of Jamie Olivers friend & Gordon Ramsay)
