#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="zoho_ticket.css" />
#+OPTIONS:  toc:nil num:nil ^:nil


* Reminder
*** remember, you made the FUCKING d minor prelude??
* What to do today:
** Send CVs by beating Applicant Tracking System using this link: https://resumecaptain.com/
** Randomizer
#+begin_src lisp

  (make-list 10 2)

  (setq var1 (-cons*
              "we need to bind ;b to sly-mode parenthesis, Emacs versor, emacs built-in profiler, edebug, apropos, macro expansion, advising system, indirect buffers, etc."
              "DB history, Emacs code compass, BACKUP our data, magit, DB or vector for our persistent highlgiats"
              "email, CV, also Audiosockets, https://vfunction.com/blog/3-tier-application/, do a Gtest for C++"
              "we do use this link http://programarcadegames.com/index.php?lang=en&chapter=introduction_to_animation with our game, ur graphql link history"
              "attention is all you need (transformer model), RISC-v, ISA, Haskell"
              "crochet, Hanifas health, code generation (internet of bugs), ambiguity in corpo legal terms"
              "try Razvan article on creating portabl GEntoo on USB, commit your treesitter.so in user-emacs-directory coz its pretty safe unless your changing architecture completely, https://www.datacamp.com/blog/docker-projects"
              "url practices in ~/my-trash/delete/stupidNotion/README.org, STEAM, how banks or best practices for race condition"
              (append
               (make-list 3 "Qt practice")
               (make-list 2 "boppps")
               (make-list 4 "drawing")
               )
              ))

  (nth (random (length var1)) var1)


  ;; testing our url randomizer


  (defun ardie1()
  (interactive)
  (org-copy-subtree)
  (let (
        (ardie/org-random-list (butlast (split-string (substring-no-properties (current-kill 0)) "\n")))
        )
    (message
     (nth (random (length ardie/org-random-list)) ardie/org-random-list)
     )))

#+end_src
** rsync:
#+begin_quote



rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/Documents /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/Desktop /media/ardie/ardie-back-2025/


rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/emacs-python-workspace /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/emacs-gforth-workspace /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/emacs-go-workspace /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/emacs-csharp-workspace /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/emacs-lisp-workspace /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/Music /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/my-trash /media/ardie/ardie-back-2025/

rsync -avzh --delete --max-size='400M' --exclude="/.*" --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/my-emacs-29-config/tree-sitter /media/ardie/ardie-back-2025/

# ==================================================
watch out for the different flag, a flag removed
# ==================================================

rsync -avzh --delete --max-size='400M' --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/.profile /home/ardie/.bashrc /home/ardie/.Xmodmap /home/ardie/.Xmodmap_ORG /home/ardie/my-autocompletes /media/ardie/ardie-back-2025/my-hidden-shell-profiles/

rsync -avzh --delete --max-size='400M' --exclude='*/myenv*/' --exclude='*/.git*/' --exclude='*/.git*' /home/ardie/.bash_history  /media/ardie/ardie-back-2025/my-hidden-shell-profiles/.bash_history_$(date +%Y-%m-%d)



#+end_quote
** Emacs
**** We need this for our battery somehow:
#+begin_quote

var1=`upower -i /org/freedesktop/UPower/devices/battery_BAT1 | awk '/perc/{print $2}'`; if [ ${var1%?} -gt 100 ]; then echo "haha"; fi

zenity --info --text="Process complete!"

#+end_quote
**** We need to this cool advicing
#+begin_src emacs-lisp

    (defun foo ()
    (print "asd")
    )


  (defun my-foo-advice ()
    "My advice for `foo`."
    ;; Example of around advice logic
    (with-output-to-temp-buffer "testest"
      (switch-to-buffer "testest")
      (insert "hello there")
      )
    )


  (defun my-advice (num &optional character)
    "My advice for `foo`."
    ;; Example of around advice logic
    (set-cursor-color "#000000")
    )

    (set-cursor-color "#e52b50")

(my-advice)

  (foo)

  (with-output-to-temp-buffer "testest"
    (switch-to-buffer "testest")
    (insert "hello there")
    )


  (advice-add 'foo :after #'my-foo-advice)
  (advice-add 'foo :after #'my-advice)


(self-insert-command )

#+end_src
**** We also need to simplify our ;;t (sexp hydra)
**** we should really do bindings for our Bash too, so it works in 42kl. This works temporarily, in our terminal session, so we can put this inside our .profile
***** https://unix.stackexchange.com/questions/604703/bash-bind-command-not-working-with-alt-key-combination
#+begin_quote

bind '"\ea": backward-char'
bind '"\ee": forward-char'
bind '"\C-a": backward-word'
bind '"\C-e": forward-word'

#+end_quote
**** We need to advice our hydra/ our self-insert so that the variable ardie/right-char-count gets unset again
***** https://www.reddit.com/r/emacs/comments/rlli0u/whats_your_favorite_defadvice/
**** We need to write these down somewhere
#+begin_quote

Can you guess what are these? (illegal):
- foo() ()
- foo() []
- foo[] ()


Can you guess what are these (legal):
- int (* fun())()
- int (* fun()) []
- int (*foo[])()
- int foo[][]

  also read this link: https://stackoverflow.com/questions/20617067/returning-function-pointer-type

  https://www.tutorialspoint.com/cprogramming/c_return_pointer_from_functions.htm

#+end_quote
**** write abou this one
#+begin_src c++

  void foo(char* someString);

// both behave similar
foo(&someString)
foo(someString)



// Not sure if C++ can do this
// but pointers are so important, you can pass a double pointer in C
// (privately, we can call them pointer-pointer, for our childish brain)

void foo(int** array) // passing a double pointer
{
    //....
    *array = theNewCollection;
    //...
}

#+end_src
**** [[https://protesilaos.com/codelog/2024-01-29-emacs-prefix-map/][defining new prefix map]]
**** we check all our hydras, to have all of our keys intact, along with -a -e shortcuts.
***** this gets easily complicated, so for our word-hydra, we are going to replace arrow keys <up><down> with -p and -n
***** if we are going to remove -b and -f as much as possible, we need to do something about capitalize and upper
***** ... so for word-hydra, we remove hydra-p and replace it with hydra-d
***** ... then p can become uppercase, coz we never do line movement for word
**** Learning Rogue-like game using these link:
***** [[https://www.reddit.com/r/roguelikedev/comments/1o5sw2d/any_good_resources_for_making_a_roguelike_in_c/][good resources]]
***** [[https://itch.io/jam/7drl-challenge-2025][7DRL challenge]]
***** [[https://github.com/libtcod/libtcod][libtcod]]
***** [[https://www.roguebasin.com/index.php/Complete_roguelike_tutorial_using_C++_and_libtcod_-_part_1:_setting_up][complete tutorial]]
***** [[https://libtcod-tutorials.gitlab.io/tutorial-pages/tutorials/tutorial-0/][more links]]
***** [[https://libtcod.readthedocs.io/en/latest/guides/getting-started.html][getting started]]
***** [[https://www.roguebasin.com/index.php/Complete_Roguelike_Tutorial,_using_python%2Blibtcod][python and libtcod]]
**** we should also try [[https://orgmode.org/manual/Speed-Keys.html][speed keys]]
**** We should really try [[https://github.com/winterTTr/ace-jump-mode][ace jump mode]], Reddit post mentions the guy uses arrow keys as a "smell" that there's a better way to navigate
**** C-mouse-9 ignores instrucion to checkout to "work and fuzz" if theres a conflict file (example: theres a file in fuzzing but not in working). We need a prompt/dialog/buffer/feedback to show the conflict coz we spent an hour hunting for this elusive problem
**** IMPORTANT: we need a multi cursors for word select
**** our Emacs company mode needs fixing, but not urgent. The Esc must escape suggestions (like in our cpp )
**** math in games
***** https://www.mathnasium.com/math-centers/richmondwest/news/role-mathematics-gaming-rw
***** https://gamedesignskills.com/game-development/video-game-math/
***** https://www.reddit.com/r/gamedev/comments/12nd3a/what_math_concepts_have_you_found_to_be_most/
***** https://pikuma.com/blog/math-for-game-developers
***** https://scenegraph.academy/article/why-is-math-needed-for-games-development/
***** https://www.gamedeveloper.com/programming/mathematics-in-videogames
***** https://www.effortlessmath.com/blog/how-math-skills-give-players-a-competitive-edge-in-various-online-games/
**** we need to read all this links on C++ I guess:
***** https://www.syncfusion.com/succinctly-free-ebooks/cplusplus/pointers-references-and-const-correctness
***** https://www.embeddedrelated.com/showarticle/1651.php
***** Also, on MOC objects, whats all that about
**** CONCEPTUAL!
***** We need to recognize other workflows that use a before-after value. So it can also be intuitively added like our (ardie/add-to-special-abbrev)
**** We made another one!! Open a file at random
#+begin_src emacs-lisp



  (let ((ardie/files-i-want (directory-files-recursively "/home/ardie/Documents/my_notes/my-org-files/" "\\.org\\'")))
  (nth
   (mod (random (current-time-string) ) (length ardie/files-i-want))
       ardie/files-i-want)
  )

#+end_src
**** https://gcore.com/learning/how-to-install-mate-on-ubuntu
**** We need to try and write about Doom Emacs, and a little about Spacemacs
**** Solve the Lubuntu keyboard shortcuts once and for all
***** create randomizer of opening one of my notes upon Emacs startup
***** 
**** More cool Emacs functions, might be too much at this point:
#+begin_src emacs-lisp

  ;; ==========
  ;; Edit: actually, we have a different idea. We found this magic trick, we have to make it more clever:
  ;; find-file-at-point 
  ;; ==========

  (defun
      ardie/open-current-file ()
    (interactive)
    (find-file (current-kill 0 t))
    )


#+end_src
**** We need to JUST practice our eLisp skill by adding random pairs for specific modes. (Clue, this will make our understanding defer eval, or lazy eval, slightly more epic)
**** emacs how to put org mode options in separate file
**** For writing more efficiently in org-mode
#+begin_src emacs-lisp


    (defhydra my-test-hydra 
      (:color purple)
      "my super test"
      ("/"
       (progn
         (org-end-of-line)
         (org-meta-return)
         )
       :exit t))

    (define-minor-mode my-test-mode
      "A minor mode so that my key settings override annoying major modes."
      :init-value nil
      :global nil
      :lighter " my-test"
      :keymap (let ((map (make-sparse-keymap)))
                (define-key map
                            (kbd "//")
                  'my-test-hydra/body) map))

  (add-hook 'ardie/special-org-hook #'my-test-mode)

#+end_src
**** TODO Important, to test cascade deletes
***** Story, we have a system that stores students and their departments. Here are the details.
***** Joint Degree Program: A student enrolled in a combined Bachelor of Science in Mechanical Engineering and Bachelor of Science in Electrical Engineering program.
***** Instead of cascaded deletes, it if we delete mechanical engineering department, it replaces that students column with NULL values
#+begin_src sql

  CREATE TABLE employees (
  employee_id SERIAL PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  hire_date DATE DEFAULT CURRENT_DATE,
  salary NUMERIC(10, 2) CHECK (salary > 0),
  department_id INTEGER,
  CONSTRAINT fk_department
  FOREIGN KEY (department_id)
  REFERENCES departments (department_id)
  ON DELETE SET NULL
  );

  CREATE TABLE departments (
  department_id SERIAL PRIMARY KEY,
  department_name VARCHAR(50) UNIQUE NOT NULL
  );

#+end_src
**** We need to write a "separator function" that auto-separates a lne based in symbols, example:
#+begin_quote

#include <QMainWindow> -----into-----
#
include
<
QMainWindow
>

#+end_quote
**** Do we need this? Its Emacs hiding text being made professional
#+begin_src emacs-lisp

  (defun ardie/tell-face ()
  (interactive)
  (if
      (equal (face-at-point) nil)
      (setq ardie/current-face 'default)
    (setq ardie/current-face (face-at-point)) 
    )
  (setq our-foreground
	(face-attribute ardie/current-face :foreground))
  (print our-foreground)
  (setq our-background
	(face-attribute 'default :background))  
  (print our-background)
  )

(face-attribute 'font-lock-comment-face :background)



(setq default-background (face-attribute 'default :background)
      default-foreground (face-attribute 'font-lock-comment-face :foreground))

(defun disappear ()
  (interactive)
  (set-face-attribute ardie/current-face nil
              :foreground our-background))

(defun reappear ()
  (interactive)
  (set-face-attribute ardie/current-face nil
              :foreground our-foreground))

#+end_src
**** [[https://www.awseducate.com/student/s/content][AWS Educate]]
***** [[https://console.cloud.google.com/welcome/new?project=steel-fin-473905-g3&authuser=1][GCP google cloud]]
**** Holy SH*T again!!
#+begin_src emacs-lisp

  ;; inspired by https://endlessparentheses.com/ispell-and-abbrev-the-perfect-auto-correct.html


  ;; an idea is to use define-derived-mode to create a mode for safely writing in an overpowered mode

  (defun ardie/test()
    (interactive)
    ;; (print (substring-no-properties (ispell-get-word nil)))
    (if mark-active
        (let ((after (substring-no-properties (buffer-substring (region-beginning)(region-end)))))
          (exchange-point-and-mark)
          (pop-mark)
          (backward-char)
          ;; (ispell-get-word nil)
          ;; (print (word-at-point))
          (let ((before (substring-no-properties (word-at-point))))
            (define-abbrev xx-abbrev-table before after)
            ))
      (let ((after (substring-no-properties (word-at-point))))
        (backward-word)
        (backward-char)
        ;; (ispell-get-word nil)
        ;; (print (word-at-point))
        (let ((before (substring-no-properties (word-at-point))))
          (define-abbrev xx-abbrev-table before after)
          ))
      )
    )


  (setq xx-abbrev-table (make-abbrev-table ))

  (setq local-abbrev-table xx-abbrev-table)

#+end_src
**** we need to read stuff: Emacs autodocumentation on point
***** https://vxlabs.com/2016/04/11/step-by-step-guide-to-c-navigation-and-completion-with-emacs-and-the-clang-based-rtags/
***** https://github.com/dawsers/emacs-qthelp
***** https://fanpengkong.com/post/emacs-ccpp/emacs-ccpp/
***** https://lahtela.me/2020/05/21/setting-up-emacs-for-qt-development.html
**** We need to use an Ubuntu clipboardmanager with Emacs built in function (rather than Emacs kill ring), and post a video on that
***** No GUI manager:
#+begin_quote

sudo apt update
sudo apt install xclip xsel

#+end_quote
***** and use this:
#+begin_src emacs-lisp

  (require 'clip-mode)
  (setq clip-mode-functions '(clip-insert-selection-at-point)) ; Use for inserting text into Emacs
  (setq clip-selection-at-point-functions '(clip-get-selections)) ; Use for selecting text from Emacs

  ;; Optional: Bind keys for copy and paste (adjust as needed)
  (global-set-key (kbd "C-c y") 'clip-yank) ; Copy and yank the selection
  (global-set-key (kbd "C-c p") 'clip-paste) ; Paste the selection

#+end_src
***** Use a clipboard manager, which works with Emacs built in copy/paste, or create a more advanced function to show history or even paste specific items
#+begin_quote


sudo apt install copyq. 
sudo apt install gpaste. 


#+end_quote
**** We need to make this tool [[https://news.ycombinator.com/item?id=22129636][array-ify]]
**** We need a really cool markdown live preview that works, with eww
#+begin_src emacs-lisp



    (setq browse-url-browser-function 'eww-browse-url)



  ;;     (defun ardie1 ()
  ;;     (interactive)
  ;;     (shell-command-on-region (point-min) 
  ;;                              (point-max) 
  ;;                              "markdown"
  ;;                              "testest")
  ;; (with-current-buffer "testest"
  ;;       (html-mode))
  ;; (with-current-buffer "testest"
  ;;       (impatient-mode))
  ;;     )


  ;; (defun ardie1 ()
  ;; (i
   nteractive)
  (let ((ardie/current-buffer (buffer-name)))
    (shell-command-on-region (point-min) 
                             (point-max) 
                             "markdown"
                             "testest")
    (switch-to-buffer ardie/current-buffer)
    )
  (with-current-buffer "testest"
    (html-mode))
  (with-current-buffer "testest"
    (impatient-mode))


  )

#+end_src
**** We need to makea video about how we manage config safely, when we have multiple Emacs (Eg: 2 versions, and 1 on Windows), minimally without any additional installation, useful if our main config file is quite large
***** The error usually looks like C:\Users\<your_username>\AppData\Roaming\elpa not found
***** 
**** things we should consider wriing in our new YT video (Ultra-ergonomic directional buffer and window navigation, for distraction free writing and coding, conditional on hard-wiring your usage of Ctrl and Alt)
***** ideas for even more "distraction free" writing or coding 
***** as you notice, I also use both left and right Ctrl and Alt, Ctrl-w for example becomes (right)Ctrl-w, becoz thats better ergonomically
***** the hydra keys are mapped to my TODO file, and other important files
***** I have funny leading keys for my hydra
***** I also have hydra for selecting, killing lines, selecting functions, super cool, etc....
***** fuure consideraiont include epoxied flat beads instead of velcro, but I have trouble finding small and flat beads, coz the velcro absorbs dust easily
***** References: https://github.com/emacsorphanage/key-chord and https://www.johndcook.com/blog/2015/02/01/rare-bigrams/
**** we need to watch more Git videos, like [[https://www.youtube.com/watch?app=desktop&v=NXaEImbo-n8&t=920s][this]], and systemcrafters vid on git reflog. Also, we faster diff checks inside Emacs. Make it EPIC!!
**** we need to do a command that copies from current buffer folder into other buffer folder, with confirm prompt from user
**** we need a "code as data" note/file
**** for C++, from this [[https://fanpengkong.com/post/emacs-ccpp/emacs-ccpp/][link]], we use this everyday, with try packages, until we are familiar, DONT use this until we figure which one uses the , we made it shorter these days.
#+begin_src emacs-lisp

  ;; from this point on, we deleted all :ensure t to avoid auto-installation
    ;; lsp
  (use-package lsp-mode
    :hook ((c-mode . lsp)
           (c++-mode . lsp)
           ;; (lsp-mode . lsp-enable-which-key-integration)
           )
    :commands lsp
    ;; :config
    ;; (setq lsp-keymap-prefix "C-c l")
    ;; (define-key lsp-mode-map (kbd "C-c l") lsp-command-map)
    ;; (setq lsp-file-watch-threshold 15000)
    )

  ;; (use-package lsp-ui
  ;;   :commands (lsp-ui-mode)
  ;;   :config
  ;;   (setq lsp-ui-doc-enable nil)
  ;;   (setq lsp-ui-doc-delay 0.5)
  ;;   (define-key lsp-ui-mode-map [remap xref-find-definitions] #'lsp-ui-peek-find-definitions)
  ;;   (define-key lsp-ui-mode-map [remap xref-find-references] #'lsp-ui-peek-find-references)
  ;;   )

  ;; (use-package lsp-ivy
  ;;   :commands lsp-ivy-workspace-symbol)

  ;; (use-package lsp-treemacs
  ;;   :commands lsp-treemacs-errors-list)

  ;; company
  (use-package company
    :bind ("M-/" . company-complete-common-or-cycle) ;; overwritten by flyspell
    :init (add-hook 'after-init-hook 'global-company-mode)
    :config
    (setq company-show-numbers            t
          company-minimum-prefix-length   1
          company-idle-delay              0.5
          company-backends
          '((company-files          ; files & directory
             company-keywords       ; keywords
             company-capf           ; what is this?
             company-yasnippet)
            (company-abbrev company-dabbrev))))

  (use-package company-box
    :after company
    :hook (company-mode . company-box-mode))

  ;; flycheck
  ;; (use-package flycheck
  ;;   :init (global-flycheck-mode)
  ;;   :config
  ;;   (setq flycheck-display-errors-function
  ;;         #'flycheck-display-error-messages-unless-error-list)

  ;;   (setq flycheck-indication-mode nil))

  ;; (use-package flycheck-pos-tip
  ;;   :after flycheck
  ;;   :config
  ;;   (flycheck-pos-tip-mode))

#+end_src
**** for more Emacs buffer ergonomic magic, also post in on Social Media
#+begin_src lisp

  (progn
    ;; http://xahlee.info/emacs/emacs/emacs_ido_setup.html
    (require 'ido)
    (ido-mode 1)
    ;; show choices vertically

    (setf (nth 2 ido-decorations) "\n")
    (setq ido-enable-flex-matching t)
    (setq ido-default-file-method 'selected-window)
    (setq ido-default-buffer-method 'selected-window)
    (setq max-mini-window-height 0.5))

  (defhydra my-b-hydra 
      (:color purple)
    "my switch to buffer"
    ("b" (progn (ido-switch-buffer)) :exit t))

  ;; ========== global goto1 minor mode for hydras.

  ;;;###autoload
  (define-minor-mode my-b-mode
      "A minor mode so that my key settings override annoying major modes."
    ;; If init-value is not set to t, this mode does not get enabled in
    ;; `fundamental-mode' buffers even after doing \"(global-my-mode 1)\".
    ;; More info: http://emacs.stackexchange.com/q/16693/115
    :init-value t
    :lighter " my-b"
    :keymap (let ((map (make-sparse-keymap)))
              (define-key map
                  ;; (kbd "C-c ;")
                  (kbd "; b")
                'my-b-hydra/body) map))

#+end_src
**** for our new Git worktree trick
#+begin_src lisp



      (global-set-key (kbd "C-<drag-mouse-8>") 'ardie/discard-unstaged-changes)
    (global-set-key (kbd "C-<mouse-8>") 'ardie/discard-unstaged-changes)

  (defun ardie/discard-unstaged-changes ()
    (interactive)

    (let
        ((current-branch (shell-command-to-string "git rev-parse --abbrev-ref HEAD")))
      (if (string-match-p "working" current-branch)
          (if (y-or-n-p "discard changes, sto restart from prev commit? (y or n) ")
              (let ((discard-change-output (shell-command-to-string "git checkout .")))
                (print discard-change-output))
            (print "action canceled")
            )
        (print "not working branch: nothing done")
        )
      )
    )  



  ;; ===== New: under test

  (defun ardie/project-save-all-buffers (&optional proj arg)
    "Save all file-visiting buffers in PROJ without asking.

  Falls back to `project-current' if PROJ is not specified."
    (let* ((proj (or proj (project-current)))
           (buffers (project-buffers (project-current))))
      (dolist (buf buffers)
        ;; Act on base buffer of indirect buffers, if needed.
        (with-current-buffer (or (buffer-base-buffer buf) buf)
          (when (and (buffer-file-name buf)   ; Ignore all non-file-visiting buffers.
                     (buffer-modified-p buf)) ; Ignore all unchanged buffers.
            (let ((buffer-save-without-query t))  ; Save silently.
              (save-buffer arg)))))))
  ;; ===== New: under test
#+end_src
***** Also in our attempt at improving further our powerful shortcuts and "no stash" workflow
**** Also for our rust-ts-mode:
#+begin_src lisp


    ;; ===== we no longer need rust-mode becoz we dont need rust-run
    ;; ===== we digged inside rust-run and discovered (compile) function used
    ;; ===== in most Emacs major programming modes

  ;; WRITE THESE SOME WHERE
  ;; ===== we unbound a key after a mistake
  ;; (fmakunbound 'my-rust-endline)
  ;; (unbind-key (kbd "RET") rust-ts-mode-map)

  (defun my-rust-endline ()
    (interactive)
    (insert ";")
    (newline)
    )

  (add-hook 'rust-mode-hook 'my-rust-endline)
  (add-hook 'rust-ts-mode-hook 'my-rust-endline)


  (define-key rust-ts-mode-map (kbd "C-<return>") 'my-rust-endline)


#+end_src
**** we need ;;h for select all, coz we still use it a lot for example in adding org-insert-structure-template
***** Also need indent-region hydra
**** we change add alternative to ;ii as highlight, coz swiper is messy
**** combobulate links:
***** [[https://sqrtminusone.xyz/configs/emacs/]]
**** we need to create a script that goes uses both next-logical-line and forward-word to copy, but we are only it works in web-mode
**** we need to really try javascript console in Emacs, we forgot where th link was
**** we should really explore combobulate to explore doing tricks in HTML and JAVSCRIPT, like moving a tree outside parent
***** moving everything outisde of any bracket
***** moving everyghing outside tag
***** but first start the experiment (and as practice), splitting the content into separate lines
**** we have to remap some of our Emacs hudra to mark-sexp. But only for Emacs29. Also we need modify our select line in hydra to save-excursion
**** we need a Emacs feature/mode that provides some cool jquery selector shortcut
**** we should really learn all the paredit tricks
**** there are several ways to exit hydras in fact, some more stable than others (becoz of nested hydras
***** [[https://emacs.stackexchange.com/questions/36597/returning-to-the-parent-hydra][link]]
***** [[https://emacspeak.blogspot.com/2020/09/emacs-paired-commands-efficient.html][repeatable hydra yank]]
**** Company mode readings:
***** [[https://www.reddit.com/r/emacs/comments/q8u2l4/unsetting_return_in_company_mode/][finally disabled company mode completion with better keybindings company-active-map]]
***** [[https://github.com/company-mode/company-mode/issues/640][variuos ideas of use-package for company-mode]]
***** [[https://company-mode.github.io/manual/Getting-Started.html#Usage-Basics][good verbose doc]]
**** We need to learn setting up opening module in Emacs rust. 
**** Read about elpy-rpc, and why do we have an elpy-rpc-buffer, it sounds cool but i dont know what its used for
**** more efficient faster completions for our Python, using this code, for now. We just need to set company-mode properly, and then use configs below from this [[https://github.com/joaotavora/eglot/discussions/1436][link]]
#+begin_src lisp


(use-package company
  :config (setq company-idle-delay 0
		company-minimum-prefix-length 1
		company-tooltip-align-annotations t))
(add-hook 'after-init-hook 'global-company-mode)
  
#+end_src
**** [[https://www.deusinmachina.net/p/tree-sitter-revolutionizing-parsing][parsing tree-sitter link]]
**** [[https://www.masteringemacs.org/article/combobulate-structured-movement-editing-treesitter][another one on tree-sitter]]
**** [[https://jackjamison.xyz/blog/emacs-garbage-collection/][garbage collection, basically to reduce stuttering]]
**** [[https://kitchingroup.cheme.cmu.edu/blog/2016/11/10/Persistent-highlighting-in-Emacs/][The Kitchin Research Group]]
**** [[https://github.com/rougier/svg-tag-mode][really cool, possible improvement to our html editing]]
**** [[https://github.com/io12/good-scroll.el][supersmooth scrolling]]
**** [[https://github.com/minad/org-modern][org-modern look]]
**** join multi into 1 without spaces
**** [[https://karthinks.com/software/fringe-matters-finding-the-right-difference/][another cool blog]]
**** We need to refactor error message of upload, what do we do with all the ID info?? Maybe theres no need for it.
***** create checks for duplicate events
***** we should add timestamp naming for CSV files
***** https://qwiet.ai/hacking-and-securing-python-applications/
**** Make sure you share-rate is above 3%
**** https://www.interview.micro1.ai/intro/micro1/?candidate=698fa6e4-4849-4b2a-90cf-db3e7d8d3816&ping=ok
**** Social media posting:
***** 42KL headache:
****** whatever advantage is gained from the unique "peer-to-peer" system, seems to be lost by the obsession over details that dont matter. And the sometimes confusing messaging from the BOCALs that seem to convince "a few" (an alarmingly growing few) to be more strict on details than the Moulinette itself (like the README which Im sure is not checked my Moulinette itself, and will probably never be used anyway, since I dont see that many on Github profiles).
****** The BOCAL (the name of "seniors" in the institution) seems to give off confusing messaging. On the hand, they say its not a competition, and yet the system seems to encourage that. They also say, a huge chunk are not doing this full time, but the only way you could pass in many instances is through cheating (I will get to this cheating point later). What they define as cheating is not entirely clear anyway, as they insist its about too much leaning on AI.
****** Cheating: A recent change they did for some of the task is to include a "recode" section, but the only thing that did is to encourage some members to "memorize" the solution. Several instances I saw, of participants simply memorizing the solution and they did not bother to include a main() function (which means theyve been preparing by memorizing the solution beforehand). Whatever advantage is gained by banning AI to encourage raw hard earned learning, is lost by the time constraint which encourages last minutes memorizing anyway.
****** The confusing scoring system: Despite the fact that the Moulinette (the AI) having the final word, you are still required to get a mininum of a few evaluations. As a little context, the Moulinette will actually fail you (depending on the min req score), if you say fail question no.2, despite passing all 8 out of 10 questions. Combine this with some other elements of the institution, a pattern that emerges is peer evaluations that overly obsessed with details that dont matter (they will even try to be more strict than Moulinette, becoz they think that is the whole purpose, being impressed by the weird 25-line limit for example), or peer evaluations that mostly dont care, since passing the Moulinette is what matters.
****** Time: If you were to fail the Moulinette or retry a project, the cooldown can reach 1 whole day (im not sure if it reaches several days). This seems to be obviously designed to force you spend lots of time in the institution. Its not enough to think in terms of "hours free since Im waiting for cooldown". When you are coming and spending time to gather evals and submitting, you are already spending a hugh amount of time there (almost as much time spent doing the tasks themselves). Whatever time you saved solving the task early on, is lost trying to maneuvre its painful and time consuming scoring flow. Remember the human has a limited time per day, when you consider sleeping and eating and toilet and going beck to your home and friends, you barely have any time left (yes, there are evern sleeping going on there). This is fine, if you are in need of raw peer learning and in need of more involved environment, and you cant seem to find a place like this. However, as I said with the confusing goal and messaging of this institution, it is "spending time for the sake of spending time". This seems to go against the the implied statement by some here, who claims most are not doing this full time (made even more confusing by 1 BOCAL's statement that you should treat this like a gym, and you get better at the task by coming everyday, lets get back to this point later). And as I have repeated previously, it seems to encourage a specific "profile" to emerge among the peers. The type that believes in the "superiority" of the syllabus.
****** Gym: It appears to be like a gym. Although it is free, and one cant complain, just like a gym, they want people to spend their personal time here. But maybe more like a cult, they want members to have faith in its syllabus, and to be mouthpieces of the "superiority of its method". If competition doesnt matter, according to the BOCALs, whatever they are doing is not working. If the score doesnt matter, whatever they are doing is not working. Just like gym bros who always obsess about size of pecs (when some dont care, and come for rehabiliation, becoz they fractured from a skating accident, and swear to never have fragile wrists again), there is always the SAME type of profile to emerge at the top (just like gym bros conquering one section of the gym).
****** Questions: Ive heard by some sources, that the syllabus has rarely changed. Unlike other complaints of lack of AI, my main complaint is some questions are quite vague (and contrasting that to the hard black-and-white rule of the Moulinette, this makes little sense). BOCALs, some of them at least seem to really discourage you to use online checkers, but the questions themslves BEG an auto checker. Same-ish example, a task called my_atoi, is supposed to behave like the standard atoi (just Google what is an atoi functio). At least according to the PDF in question. But turns out, its suppose to behave COMPLETELY different. And there is no way to know that, apart from failing Moulinette very early on (most here dont have that luxury) OR "cheating". Again, what is defined as cheating, as I have previously said, its quite vague, despite claims that its clear. (And that is just 1 example of a task).
****** The confusing anti-AI message: I applaude this institutions anti-AI efforts in its method of encouraging learning. And yet, in meetups when you enter core, they change their tune to "you cant avoid AI anyway, since its everywhere". And yet, many parts of the learning suggest you stop using AI, admit if you are using AI.
****** To be honest, my complaint is not on the anti-AI or the syllabuses, but rather the very confusing message it sends, resulting in sometimes arbitrary strictness among peers, as well as a certain type of "profile" to emerge at the top of this school. Since its free, I cant complaint much. But apparently, the syllabus hasnt been changed that much for decades (which has made me even more convinced that the entire point of the syllabus, is to "raise" a certain "profile" of members, a certain "character trait"). I am of the belief that there is no such thing as a superior method, but instead one makes compromises. But the confusing and even slightly conflicting message (parted by all), seems to encourage all the members to become mouthpieces of its "superior method".
***** Philosophy of Tooling:
****** Ecological philosophy: body-plus-object system
****** Herdeggerian Readiness-to-Hand: tools are not passive objects, but define our mode of being in the world. When used effectively, it is "ready-to-hand". They recede from conscious awareness to become an extension of the self. whereas broken tools become present at hand
****** causal direction and purpose: tools flow from purpose not the reverse.
****** agency: tools are mediating instruments. Tools enable actions, but constrained to specific methods, a feedback loop occurs where "tools make the man". (The most dangerous element of this is that it shapes "material inheretence")
***** We need some of this stuff inside of our gud-mode
#+begin_src emacs-lisp

(keymap-set gud-mode-map "r" 'ardie/test)

#+end_src
***** Our attempt at exam key chord (which should use this as a launching pad for other cool stuff like 3 keys at once, for something weird)
****** we debugged gradually, from "2 conditionals eating or not eating our keys" TO "eating, not eating. And then eating -> within time, or not in time. And in time will trigger our desired function"
***** Force mouse tracking to make C GDB debugging much better
#+begin_src emacs-lisp

  (defun my-gdb-tooltip-setup ()
    "Ensure tooltips and mouse tracking are active for GDB/MI."
    (gud-tooltip-mode 1)
    (track-mouse t))
  
#+end_src
***** Dont pollute C namespace (cool idea)
****** https://gamesfromwithin.com/stupid-c-tricks-2-better-enums/
***** gdb "we are one single entity" thing:
#+begin_src emacs-lisp

(defun ardie/gud-n ()
  (interactive)
  (gdb-send "gud-a.out" "n")
  )

(defun ardie/gud-open ()
  (interactive)
  ;; (gdb-send "gud-a.out" "n")
  (gud-gdb "gdb -i=mi a.out")
  
  )

(keymap-set ardie/c-mode-map "C-c C-g" 'ardie/test)
(keymap-set gud-mode-map "n" 'ardie/gud-n)


#+end_src
***** Our progress so far (minimal exam key chord):
#+begin_src emacs-lisp

    (define-minor-mode ardie-mode
    "some
    mode"
      :global t
      (setq input-method-function
            (and ardie-mode
                 'ardie-input-method))

      )





    (defun ardie/back ()
      (interactive)
      (ardie-mode -1)
      (key-chord-mode 1)
      )





    (ardie/back)

  (setq ardie/valid-keys [?j ?q])
  (setq ardie/seconds 0.3 )
  (setq ardie/prev-keys nil )


  (defun ardie/kc-reset()
    (setq ardie/key-match nil)
    (setq ardie/prev-keys nil)
    (setq ardie/key-repeat nil)
    )


  (defun ardie-input-method (first-char)
  (cond
   ((cl-position first-char ardie/valid-keys)
    (print "its a valid key")
    (setq ardie/prev-keys first-char)
    (list first-char)
    (let ((next-char  (read-event nil nil ardie/seconds)))

      (cond

       ((null next-char)
        (print "too slow, ignoring")
        (list first-char)
        (ardie/kc-reset)
        )
       ((eq next-char ardie/prev-keys)
        (list ?z)
        (ardie/kc-reset)
        )



       (t (list next-char))

       )
      )


    )
   (t
    (list first-char))
   ))

  
#+end_src

***** Combining 2 repos into a unified history. The general flow looks like this:
#+begin_src shell

git remote add custom-history-source <some old repo URL/directory>

git fetch custom-history-source

git merge custom-history-source/main --allow-unrelated-histories -m "Merge custom historical commits"

git push origin main

#+end_src
***** We can even combine the fetch & remote add such as in this example: 
****** https://saintgimp.org/2013/01/22/merging-two-git-repositories-into-one-repository-without-losing-file-history/
***** Tote bag:
****** [[https://www.youtube.com/watch?v=c43Ahe_qFOw][Tote bag with inner and outer bag]]
***** Order of precedence is a nightmare in C, made worse by pointers, addresses, and all those adjacent concepts
****** And i fear more what is to come, if i keep using pointers
#+begin_src c


  int some_function(char a, int *n){
      (*n)++;
      // *n++; // this will not work, and gave me a headache for 30 minutes
  }

#+end_src
***** Discord post:
****** context: they still think a macro
****** write a post about that specific link, how Emacs has separates the concept of the the buffer (the "view" of the file) from the file itself. A buffer may be associated with a file or not (just a text display with some functionality). It also separates that from windows and frames.
****** These leads to some interesting behaviour possible in Emacs. Below is a sample video that I have of my own Emacs. I have a consistent scratch buffer (I named "ardie-scrratch") which is either always present and pops on the left, or will be created, when I press the "rare bigram" key-chord "]\" (right, indicates right-like functionality, in this case the "ardie-scratch" will always be open on the right side)
****** If Im in a different workspace, over my browser, and I press "super-e", it opens that same buffer, as a transparent window (Emacs refers to window as "frames")
****** whats important to know here:
******* I use key-chords, an "abandoned" Emacs package, a package supported by Emacsorphanage. "Abandoned" Emacs packages still used by Emacsers rarely die, as it is built on top core Emacs functionality that change very slowly over decades
******* key-chords, is one of the only Emacs packages, AFAIK, that lets users combine any 2 keys (not just Alt or Ctrl) and bind that to any functionality. Keys are pressed like chords (like a piano chord)
******* The transparent "super-e" is made possible with compton (a windows compositor for Linux, dont ask me). Under my personal setup, I have to make sure the command "compton -b" is run at OS startup
****** Reading about trains, on the first ELECTRIC tram being sometime around 1880!!
******* And noticing the state of public transport in Malaysia, not as bad as in India, but thats a really low bar, especially considering we dont have the kinda protest you saw in Delhi regarding BRT from other car-brained road users.
******* It literally MAKES NO SENSE at all
******* If its true that technology is progressing at an accelerated pace, at least thats what all these Javacript, Web3 and now AI bros keep on pushing and claiming.
******* (I know this a lie anyway)
******* Oooh, so much "progress".
******* And yet trains havent improved that much, the first bullet train was in 1964, and that was an ETERNITY in "oooh, so much progress" computer time.
******* And even the fastest carriage/coach in Malaysia is nowhere near half that speed.
******* I think its becoz, computer technology, is for the most still too "magical" for even most senior techies.
******* That its mostly bad culture and art. And theres a lot of bad culture and art in "tech".
******* Read about trains:
****** NO, this is one better, coz we apparently made our functoin too fancy
#+begin_src emacs-lisp

  (dolist (each/buffer (buffer-list))
  (if (eq (string-match "\*.*" (buffer-name each/buffer)) 0)
      (bury-buffer each/buffer)
    (print each/buffer)
      )
  )

  (global-set-key (kbd "C-z") 'unbury-buffer)

#+end_src
****** FINALLY, an Emacs functions promising enough to perfect our "key-chord" navigation
#+begin_src emacs-lisp

  ;; this function is supposed to fix our problem of eLisp not getting "first nth" as list
  ;; yes im a noob
  (nthcdr (- (length randoml) 3) (reverse randoml ))

  ;; this function is ugly I suppose
  (dolist (a-buffer-var (buffer-list))
  (dolist (a-recent-var recentf-list)
      (if (string-match (buffer-name a-buffer-var) a-recent-var)
        (print (pp-to-string a-buffer-var))
      )        
    )
  )

#+end_src
****** More Emacs snippets to improve, this one is for viewing history with specific commits
#+begin_src emacs-lisp

  (shell-command "git --git-dir=/home/ardie/Documents/knowledge/my-org-files/.git log --oneline")


(let ((ardie/temp-buffer (read-buffer "select EMPTY existing buffer") ))
  (with-current-buffer ardie/temp-buffer
    (shell-command
     (concat "git --git-dir=/home/ardie/Documents/knowledge/my-org-files/.git show " (car kill-ring)":misc/2021/emacsStuff/emacs.org")
     ardie/temp-buffer)
    )
  )

#+end_src
****** Emacs fido fuzzy literal substring:
******* https://www.emacs.dyerdwelling.family/emacs/20250905100614-emacs--customizing-emacs-completion-from-fidos-fuzzy-matching-to-literal-substring-search/
****** https://slate.com/technology/2014/01/programmer-privilege-as-an-asian-male-computer-science-major-everyone-gave-me-the-benefit-of-the-doubt.html
****** Another snippet, this one for file-find but our version, gets from recent clipboard (to test: diff instance or same):
#+begin_src emacs-lisp

  ;; we need a filter to check if clipboard latest is file-like 

  (let ((ardie/temp-buffer (concat "*temp-" "*" (number-to-string (random 100000)))))
  (with-temp-buffer ardie/temp-buffer

                    (clipboard-yank)
                    (mark-whole-buffer)
    (kill-ring-save (region-beginning) (region-end))

    )

  (find-file (car kill-ring))

#+end_src
****** We need to fix this snippet:
#+begin_src emacs-lisp

  (let ((n 1))
  (while (< n (length (buffer-list)))
    (if (= (string-match " " (buffer-name (nth n (buffer-list)))) 0)
    (with-current-buffer (nth n (buffer-list))
    (rename-buffer "helloooooo")
      )
    ;; (bury-buffer (nth n (buffer-list)))
    )

    (setf n (1+ n))
    )
  )
  
#+end_src

****** [[https://futurism.com/artificial-intelligence/ai-companies-destroying-rare-books][AI firms buying, destroying rare books to train models]]
******* literally ripping off authors’ books to train its AI
******* taking advantage of a legal concept known as first-sale dosctrine
******* Print books from the pre-LLM era are structurally guaranteed to be free of this contamination
******* this practice has become prevalent enough that even well-established book sellers are looking to cash in on the AI boom
******* Once focused on helping libraries, distributors, and book shops find and sell books, ISBNdb now helps AI companies bulk-buy up a million.
******* Some service companies like ISBNdb that are helping purchase in bulk, are keeping AI buyers anonymous as part of the huge deal
****** [[https://thenextweb.com/news/tech-giants-hidden-off-balance-sheet-debt-ai][Five tech giants are hiding $1.65tn in AI debt, using the trick that toppled Enron]]
******* We should read about this article, and its link terminologies, such as "replacement tenants"
******* The mechanics are simple. The company packages the debt for chips, servers and power into separate legal entity, often a joint venture, so the cost never flows through its own accounts.
****** We need a weekly reminder for our Emacs
#+begin_src emacs-lisp

  (let ((day (shell-command-to-string "LC_ALL=en_EN.utf8 date +%A")))
    ;; (print " today is ~c" day)
    (format "today is %s" (string-trim day))
    )

#+end_src
****** Post in discord, the case for touch typing
****** somehow there is an element of revenge of the nerds, when it comes to being a senior programmer. Somehow, life should be bigger than that. 
****** [[https://onlinelibrary.wiley.com/doi/full/10.1002/eng2.70849][Music Visualization weirdness]]
******* The author of solidity lang, related to "smart contract" wrote a PhD thesis on this topic
******* Application of Music Data Visualization Technology in Music Appreciation Teaching
****** Emacs ternimal emulator is no longer slow:
******* its got eat-mode
******* it is so responsive, it run Emacs inside of eat inside of Emacs
****** [[https://www.harvardmagazine.com/2025/01/harvard-study-memory-creative-thinking][is memory connected to creativity]]
******* Despite our fatigue of memory (no thanks to fetishization of short term Exams such as in our culture), some are disgusted by the idea of putting value in memory. But this is not the same thing.
******* creativity might be related to episodic memory, or ability to relive (id like to call it retrieve), specific moments from past experience
******* We should read about the book called "2001 book The Seven Sins of Memory: How the Mind Forgets and Remembers"
******* referring to a recent research involving "episodic simulation", aka how the human constructs simulations of past and future events
******* it refers to a study, of an accident patient with a severe case of amnesia, with shattered "episodic memory", unable to recall personal past experiences, but his "general knowledge" was fine.
******* most interestingly, when asked what he would to tomorrow, he was unable to plan for the future. Study suggest a strong link between, remembering the past and envisioning the future
******* led to formation of "constructive episodic simulation hypothesis", merging pieces of the past ideas of the future.
******* study involving an "induction" test, where non-control subjects did a recall experiment, reveal more detailed innovative ideas
******* but it comes with a trade-off, subjects with higher divergent creative thinking, showed "memory distortions", adding false details 
****** Emacs eat-mode, this is worth writing, as its snappy than anything Emacs has previously as a terminal emulator
****** Write about ur post (save in Important in IG) about "convenience triggering burnout on an unprecedented scale", across Asian countries. 
****** https://www.instagram.com/p/Da2yRKegapt/?igsh=ZjFkYzMzMDQzZg==
******* while its true, that most such protestors are usually carried out by NIMBY (Not In My Backyard) folks, those who protest at every idea of development in their neighbourhood. This is not the same, as a public utility like public trains (which proves better in the long run, becoz, as an example, Malaysian traffic isnt going to get better any time for many decades)
******* This sounds like (but not necessarily similar) to secret Data Center deals across several states in America. One example, in Columbia, the mayor David Mitchell signed a secrecy agreement with DigiPowerX, a data center developer, without consulting Citi Council members.
******* while NDA agreements are common in the economy. NDA regarding plans of Data Center locations is not a "trade secret", but are often multi-billion agreements under the table
******* Data Centers consume a lot of energy and water, in some parts of the Western World, the general public has had to burden that additional bill. Becoz, for example, Data Centers are connected to the same power grid.
****** we need to write about Jevons Paradox
******* a very stupid paradox that might explain why its not worth it, for infinite growth of tech
******* 
****** Why Lisp? (Opinion is fully my own)
******* [[https://gigamonkeys.com/book/lather-rinse-repeat-a-tour-of-the-repl][Link]]: A real story of, an impressive instance of remote debugging occurred on NASA's 1998 Deep Space 1 mission.
******* An interesting case on how, even when the Lisp app is deployed, there's often still a way to get to a REPL. You can interact and even debug with an app while its also running a Web Server at the same time
****** To successfully target the European and Western markets, optimize your LinkedIn profile for global recruiters, build a niche GitHub portfolio showcasing both Functional (e.g., Haskell, Scala, Rust) and Imperative (e.g., Python, Java) projects, and market your time-zone advantage for asynchronous work on global platforms like  [[https://arc.dev/][Arc.]] Here is a step-by-step strategy to position yourself as premium global talent from Malaysia:

1. Frame Your "FP + Imperative" SkillsetWestern startups and tech companies value engineers who understand multiple paradigms.The Pitch: Position yourself as a pragmatic problem solver. You use FP to write highly reliable, bug-free, and maintainable core logic, and imperative languages for performance-critical systems or integrations.Show, Don't Just Tell: Write case studies or technical blog posts (on Medium or Dev.to) explaining why you choose specific paradigms for specific tasks.GitHub: Host open-source projects or toy compilers/libraries written in languages like Scala, Elixir, or Rust.

2. Leverage the Time-Zone AdvantageThe time difference between Malaysia (GMT+8) and Europe (CET/CEST) is 5–6 hours.Asynchronous Advantage: Advertise this as a superpower. You can process pull requests and complete features while European teams sleep, leading to faster development cycles.Meeting Availability: Pitch availability for late-afternoon European syncs (your late evening) to ensure smooth collaboration. [[https://remoteineurope.com/blog/how-to-find-remote-software-developer-jobs-in-europe][remote in europe]]

3. Target the Right PlatformsDo not rely solely on generic job boards. Focus on remote-first and Europe-specific platforms:Arc: A vetted talent platform that connects developers with Western startups and matches candidates for full-time and freelance roles.Remote in Europe: A highly specialized job board for candidates looking for remote tech roles within European time zones.We Work Remotely: The largest established remote-first job community, heavily frequented by US and European companies.LinkedIn: Update your location to "Remote / Europe (Open to Relocation)" or "Asia (EMEA Hours)," and set your target regions to "Europe" or "Worldwide".

4. Optimize Your Resume & CommunicationLanguage: Polish your written English. European employers highly value clear, concise documentation and asynchronous communication.Rates/Salary: Research European developer salaries (e.g., via platforms like Remote Rocketship) to set competitive expectations.Payment Setup: Prepare digital payment rails like Wise or Payoneer to easily receive Euros or USD. [[https://www.remoterocketship.com/country/europe/jobs/developer/?page=1&sort=DateAdded&jobTitle=Developer&locations=Europe][remote rocket ship]]

****** we really need to write about [[https://www.researchgate.net/publication/345242745_Marked_Men_White_Masculinity_in_Crisis][this one]], as well an article that "references" this article
******* ... While men are consistently inundated with patriarcahl messages that limits their expression of intimacy and teaches them to suppress acts of vulnerability, they are simultaneously censured for upholding these very tenets of masculinity to which they were socialized. This contradiction in social expectation, leaves men with an uncertainty as to what is expected of them (Gourarier, 2019;Kimmel, 1987;Robinson, 2000). However, a contradiction in role expectations for men cannot merely be resolved through a modification in their gender ethos, as this conflict inherently threatens the legitimacy of their power and authority which has been traditionally enshrined within tenets of masculinity. ...
****** https://wiki.c2.com/?LispForGames
******* game code can be notoriously ugly, especially when using the typical state polling machine
****** article after several months long experiment of learning graphics programming
******* Its important this parallel with learning something else, as you will feel "long" moments of no progress (even for someone who likes digging deep, and with a knack or talent of creative programming)
******* we need to chech this too: https://gabrielgambetta.com/computer-graphics-from-scratch/09-perspective-projection.html
****** Links to WRITE:
******* https://blog.mbedded.ninja/programming/design-patterns/state-machines/
******* https://www.aleksandrhovhannisyan.com/blog/implementing-a-finite-state-machine-in-cpp/
******* https://barrgroup.com/blog/how-code-state-machine-c-or-c
******* https://www.embeddedrelated.com/showarticle/1625.php
****** we need to write abot Lisp somewhere
******* https://www.cs.colostate.edu/helpdocs/lispEmacs.html
****** We wrote this in diary already: Now that we have some familiarity of what GLSL and shaders code look like (2 types of shaders at least), and how they feed code into each other. We should REALLY read about Graphics History. Some interest includes "what is z-buffer". We downloaded the file as History-of-graphics.pdf. But heres the link:
******* https://graphics.stanford.edu/courses/cs248-01/History-of-graphics/History-of-graphics.pdf
****** Our DevOps event, also about, Sinar Project event!!
#+begin_quote

I build AI agent.
health tech startup
5 agents in 1 workflow
dont make users wait
hanle stream

60 seconds spinner reads as a crash

stream evetes over SSE

user -> init -> update 0> status -> message -> complete

whatd does "stateful" and "load balancer" actually mean

decouple: background thread + event buffer

buffer strem in stream programming

security, injection: guard rails are not enough

cyrber cimr bill in malaysia government


#+end_quote


****** In Lisp, code and data share the same structure: nested lists known as Abstract Syntax Trees (ASTs). By skipping the traditional parsing step, programmers can manipulate Lisp source code directly as data, unlocking unparalleled metaprogramming capabilities and allowing them to seamlessly extend the language's syntax.
****** This unique design stems from a core concept called homoiconicity, which provides several distinct advantages
1. Code is Data (and Vice Versa)
2. Powerful Macros
3. Structural Editing & Refactoring
4. Code Generation
(Yeah, Im quoting AI, and Im still a noob. But Lisp still seems absolutely fascinating. And Id like to think this explains why Emacs seems so "borderless", even when many competent Lispers say eLisp is not real Lisp)
****** https://docs.cocos.com/creator/3.6/manual/en/shader/glsl.html
****** [[https://themaister.net/blog/2025/10/][insightful blog into learning importance of learning compute first when GPU programming, and not just "using API"]]
****** misnomer:
******* Uniform's are literally passed from CPU to GPU
******* but that is jsut the mechanic, what really matters, is that the GPU is just secondary to the whole operation.
******* Even though the entire pipeline is "important", data is passed to the GPU "imperatively". So uniforms, are "injecting data from your code to the pipeline of a single object"
******* super important link: https://thebookofshaders.com/glossary/?search=mix

****** twitch ERC setup
******* setup untested ( number is the real versoin)
#+begin_quote

access
mt3sg1qie3e73u6en3mtlrvzzecppd

client id
gp762nuuoqcoxypju8c569th9wz7q5

refresh token:
p17sapasfwwvrykq4lfdd1tslvuy8gzi5jo1fk3xs6iq7tuz0e

(erc-tls :server "irc.twitch.tv"
         :port 6667
         :password "<your OAuth token>"
         :nick "<your nick>")

#+end_quote
****** the myth of the necessity of work:
- suffering culture: the belief that "work has to be hard"
- what is procrastination
- what is boredom: is boredom a bad thing

the myth of the necessity of work:
- most think SUCCESS = doing things with a David Goggins vibe
- working hard is a "protestant work ethic". Working hard and consume little
- in modern times, hard work has replaced religion to make your life meaningful
- Bertrand Russel was ahead of his time. He wrote about moving towards a 4-hour work day
- https://aliabdaal.com/newsletter/the-myth-about-hard-work/  
****** we should be reading about virtual memory, paging, and the difference with embedded
****** We should download The Age Of Surveillance Capitalism by Shoshana Zhuboff
****** stuff we collected for reading so far in OpenGL. 
******* https://stackoverflow.com/questions/37972229/glvertexattribpointer-and-glvertexattribformat-whats-the-difference
*******  replacing the glVertexAttribPointer() with glVertexAttribFormat() and glBindVertexBuffer()
******* the problems:
******** it tries to do too many things in 1 function. Provide the format of the data (the step, the stride, etc), and where the data comes from.
******* [[https://riptutorial.com/opengl/example/32426/using-textures-in-glsl-shaders][riptutorial has cool stuff on opengl that we STILL did not manage to work]]
****** OpenGL 
******* We should stop playing with frambuffer logic, (creating shader, linking it, create a vertice array, generating buffer and array, adding data to it, defining attributes and stride/steps and offset, etc...)
******* Instead, we should just read built in variables and functions for a while, apparently, its quite powerful
******* https://learnwebgl.brown37.net/12_shader_language/glsl_builtin_functions.html
******* https://docs.vulkan.org/glsl/latest/chapters/builtinfunctions.html
****** others texture OpenGL, glsl, vulkan, mid reading
******* https://www.cs.cornell.edu/courses/cs4621/2015fa/lectures/lec04-practicum-fa15.pdf
******* https://www.opengl.org/sdk/docs/tutorials/TyphoonLabs/Chapter_3.pdf
******* https://github.com/mattdesl/lwjgl-basics/wiki/glsl-versions
******* https://web.engr.oregonstate.edu/~mjb/cs557/Handouts/VulkanGLSL.1pp.pdf
******* https://en.wikibooks.org/wiki/GLSL_Programming/Rasterization
******* https://wikis.khronos.org/opengl/Built-in_Variable_(GLSL)
****** Sinar project links:
******* https://kopitiam.sinarproject.org/
******* https://sinarproject.org/get-involved
******* https://www.slideshare.net/slideshow/making-sense-of-internet-of-things-using-airbox-as-an-example-82766546/82766546#20
******* https://rimbawatchmy.com/forestTracker
******* https://huggingface.co/datasets/HCSA/HCSA_Indonesia_Forest_Plot_Data_2023
******* https://github.com/topics/canopy-height-models
******* https://old.thinkcity.com.my/wp1/urban-analytics-portal/
******* https://www.fixmystreet.com/
****** we should be posting about Kanata, coz its really cool
******* the function (layer-toggle layers) is not simple, auto maps to layers depending on order, so its not a dumb function (sadly), but it works
******* tap dances are too taxing on the typists mind, should not be used to trigger layers.
******* 
****** https://shahriyarshahrabi.medium.com/write-your-own-game-engine-df1132908cdf
****** Write about the nightmare of shared library, and how ti relates to "GLIBC version not found"
****** Kanata - true liberation of keyboard magic:
******* https://github.com/jtroo/kanata/discussions/888
******* https://shom.dev/start/using-kanata-to-remap-any-keyboard/#installation
******* https://github.com/jtroo/kanata/releases
******* https://github.com/jtroo/kanata/wiki/Avoid-using-sudo-on-Linux
****** daily SPF
****** https://stackoverflow.com/questions/21652546/what-is-the-role-of-glbindvertexarrays-vs-glbindbuffer-and-what-is-their-relatio
******* misnomer (we REALLY need to write this one down):
- the buffer is the binary/stream if you will, we dont pass it to the shader, we just "make it current", againt OpenGL has ugly globals, but we can think of it as this way
- the vertex array is actually FOR the SHADER, we make it current, but we also define pointers to it, so the program knows when to use it.
- also in the example below, you see more modern shortcuts, this time binding ALL attributes to buffer, NO defining a pointer for the shader, NO binding a buffer first, just straight deal with the array



****** attempt:
KMONAD (https://codebenchers.com/blog/kmonad-on-ubuntu-program-your-keyboard):
- chmod +x kmonad
- ./kmonad
- using evtest and listing /dev/input/my-id or /dev/input/my-path
- it should be ~/.config/kmonad/config.kbd
- install kmonad as a service: copy executable to /usr/bin/kmonad
- create a service file (that points to ur config): /etc/systemd/system/kmonad.service
- "systemctl enable" and "systemctl start" that specific service
****** macros
C and C++ macros pollute the namespace because the preprocessor relies on simple text substitution. It does not respect scopes like namespaces, classes, or functions. Any macro you define can accidentally overwrite matching code downstream, causing silent bugs or compilation errors. [1, 2, 3] 
## Why Macro Pollution Happens
******* Global scope: Macros apply globally from the line they are defined until the end of the compilation unit.
******* No type safety: The preprocessor runs before the compiler, replacing text blindly.
******* Shadowing errors: A macro named MAX will break any variable, function, or class method named MAX. [4, 5] 

## Modern Workarounds in C++
You can replace almost all macros with standard C++ features that respect scope and types. [6, 7] 
## 1. Use Inline Functions for Function-Like Macros [8] 
Replace macro logic with inline or constexpr functions. They obey namespaces and classes. [9, 10, 11] 

// Bad macro#define SQUARE(x) ((x) * (x))
// Good workaroundnamespace MathUtils {
template <typename T>
    constexpr T square(T x) { return x * x; }
}

## 2. Use constexpr or const for Constant Macros [12, 13] 
Replace numeric and string macros with typed constants.

// Bad macro#define BUFFER_SIZE 1024
// Good workaroundnamespace Config {
    constexpr int BufferSize = 1024;
}

## 3. Use Enums for Groups of Constants [14, 15] 
For related integer constants, strongly typed enum class keeps names isolated.

// Bad macro#define COLOR_RED 0#define COLOR_BLUE 1
// Good workaroundenum class Color {
    Red,
    Blue
};

## Legacy and C Workarounds
If you must use macros for conditional compilation or platform-specific code, use these mitigation techniques. [16, 17] 
## 1. Use Unique Prefixes [18] 
Prefix macro names with your project or library name in all capital letters. [19] 

#define MYPROJECT_LOG_ERROR(msg) // Less likely to collide

## 2. Undefine Macros Immediately
If a macro is only needed inside a specific file, undefine it as soon as you are done. [20] 

#define TEMPORARY_MACRO 5// ... use macro here ...#undef TEMPORARY_MACRO // Pollution stops here

## 3. Wrap in do-while(0) for Multi-line Blocks [21, 22] 
This ensures the macro behaves like a single statement and does not break control flow structures. [23, 24] 

#define SAFE_PRINT(x) do { \
    std::cout << x << std::endl; \
} while(0)

Would you like to look at a specific macro in your codebase to see how we can rewrite it using modern C++?


https://www.reddit.com/r/cpp/comments/gov4ap/what_do_we_need_to_get_completely_rid_of_macros/


https://www.fluentcpp.com/2018/09/04/function-poisoning-in-cpp/

https://locka99.gitbooks.io/a-guide-to-porting-c-to-rust/content/porting_from_cpp/namespace_collisions.html


https://www.reddit.com/r/C_Programming/comments/vworgh/are_macros_like_this_evaluated_at_runtime_or_at/


https://gist.github.com/lefticus/10191322


https://www.reddit.com/r/learnprogramming/comments/xdffy4/are_cc_macros_bad/


https://www.vaia.com/en-us/textbooks/computer-science/c-how-to-program-8-edition/chapter-14/problem-11-why-might-you-choose-to-use-a-function-template-i/


https://learn.microsoft.com/en-us/cpp/preprocessor/macros-c-cpp?view=msvc-170


https://dev.to/pauljlucas/cc-preprocessor-macros-fh5


https://www.reddit.com/r/learnprogramming/comments/xdffy4/are_cc_macros_bad/


https://www.mathworks.com/help/bugfinder/ref/certcrec.pre12c.html


https://eecs390.github.io/notes/metaprogramming.html


https://codefinity.com/blog/Understanding-Preprocessor-Directives-in-C-plus-plus


https://mahinhasanaiub.medium.com/understanding-macros-in-c-define-directive-and-its-applications-called-macro-82899479dbbd

https://news.ycombinator.com](https://news.ycombinator.com/item?id=26735655

https://www.naukri.com](https://www.naukri.com/code360/library/macros-in-cpp

https://softwareengineering.stackexchange.com/questions/412249/current-industry-standard-with-regards-to-c-macros

https://unstop.com](https://unstop.com/blog/macros-in-c

https://luckyresistor.me/page/avoid-preprocessor-macros/

https://stackoverflow.com/questions/69755824/is-there-a-way-to-have-the-same-define-statement-in-different-files-that-are-in

https://herovired.com/learning-hub/topics/macros-in-c


https://stackoverflow.com/questions/23444371/how-to-write-safe-and-user-friendly-c-c-define-macros

https://www.allpcb.com/allelectrohub/the-dowhile0-idiom-in-c-and-c

https://spin.atomicobject.com/preprocessing-with-caution/

****** civic tech idea:
******* MY IDEA: a charitable giving platform that facilitates direct donations to homeless neighbors in need.
******** Tree Canopy Tracker: A computer-vision project analyzing satellite data to find local neighborhoods lacking green cover
******** https://dspace.mit.edu/entities/publication/b091ea46-752a-4f99-9585-3cdf1f06ef30
******** according to HUGSI, the "greeness" of Malaysia is rated at 35%, with a grade of D- globally
******* Civic tech software projects bridge the gap between residents and local systems by enhancing public transparency, improving community service coordination, or streamlining public engagement.
https://medium.com/civic-makers/civictech-primer-what-is-civic-tech-7ea788e766d3
https://www.computer.org/csdl/magazine/so/2022/06/09786040/1DQPBo2560M
https://github.com/awesomelistsio/awesome-civic-tech
## 📊 Transparency & Open Data

******* Municipal Budget Visualizer: A tool that converts complex PDF government budgets into interactive charts.
******* Public Records Tracker: A system to automate and track Freedom of Information Act (FOIA) requests.
******* Legislative Vote Checker: An app tracking local council votes to show if representatives align with campaign promises.
******* Zoning Change Alerter: A web scraper that notifies residents when property zoning rules change in their neighborhood.

## 🛠️ Community Service & Mutual Aid

******* Disaster Response Coordinator: A lightweight, offline-first app mapping local resources and shelter capacities during emergencies.
******* Food Rescue Network: A platform connecting local restaurants with surplus food directly to nearby shelters.
******** run drives to supply them with temperature-controlled logistics or extra delivery fleets.
******* Tool & Equipment Library: An open-source inventory system for neighborhoods to share tools, reduction waste.
******* Air Quality Mapping: A platform crowd-sourcing data from cheap, DIY IoT air monitors to map local pollution blocks.

## 🗳️ Civic Engagement & Democracy

******* Virtual Town Hall: A platform allowing moderated asynchronous video or text debates on local city proposals.
******* Plain-Language Law Translator: An AI-assisted parser turning dense local ordinances into simple, accessible text.
******* Digital Ballot Builder: A mock voting sandbox helping citizens research local candidates and measures before election day.
******* Tenant Rights Navigator: A decision-tree app guiding low-income renters through local legal options against eviction.

## 📈 Infrastructure & Environment

******* Crowdsourced Hazard Mapper: A mobile app letting citizens map broken streetlights, aggressive potholes, or blocked bike lanes.
******* Tree Canopy Tracker: A computer-vision project analyzing satellite data to find local neighborhoods lacking green cover.
******* Public Transit Delay Reporter: A community-driven, real-time alert platform for reporting bus or train route issues.

Before writing any code, it is highly recommended to explore existing open-source ecosystems like the [Civic Tech Field Guide](https://directory.civictech.guide/listing-category/open-source) to avoid duplication. Building on top of existing tools can maximize community impact with minimal wasted developer resources.
Could you share more about your goals? Let me know:

******* Your target programming language or stack
******* The specific community problem you hope to solve
******* Your project scale (hackathon prototype vs. long-term production app)
****** We need to write all this somehere:
******* #pragma comment: compiler specific preprocessor directive, for linking behaviour of Microsoft Visual C++
******* #pragma comment: commonly used to link static library
******* #pragma comment: GCC uses flags instead
******* #pragma comment: Windows uses registry based, or fixed paths. Auto linking wouldbe fragile in a Linux environment, where library locations vary widely
******* Clang: a popular alternativew compiler to GCC for game dev, which goes well with CMake
******* C/C++ macros: It always pollutes the global namespace becoz the preprocessor substitutes text before the compiler processes namespace.
******* Lisp preprocessor: its just macros, syntactic transformation performed in the compilation environment, 
******* Lisp preprocessor: syntactic vs lexical. Unlike substition, it uses AST or S-expressions, 
******* Lisp homoiconic: all Lisp code is lists. so macros can use any list-processing in Lisp to generate new code. . Lisp macro (itself) is turing complete
******* compile-time func execution: C  NO! C++ yes, with constexpr and consteval
******* C compile time computation: For c, only macro expansion and  constant expression
****** Links:
******* [[https://stackoverflow.com/questions/15002550/c-macros-and-namespaces][macros know nothing about namespaces]]
******* [[https://www.artima.com/articles/reducing-preprocessor-namespace-pollution][reducing preprocessor namespace pollution]]
******* 
****** its time to master grep alist
******* compilation-error-regexp-alist
******* https://emacsredux.com/blog/2026/03/06/mastering-compilation-mode/
******* https://groups.google.com/g/gnu.emacs.help/c/cBvCocaCBfs?pli=1
******* https://christiantietze.de/posts/2025/08/clickable-swift-testing-failure-messages-in-emacs-compile-mode/
******* https://doc.endlessparentheses.com/Var/compilation-error-regexp-alist.html
******* https://andreyor.st/posts/2023-01-10-compiling-clojure-projects-in-emacs/
******* https://emacs.stackexchange.com/questions/43956/which-regexp-from-compilation-error-regexp-alist-is-used-by-compilation-mode
****** Lets read on creativity and false memory
******* https://www.psychologytoday.com/us/blog/ulterior-motives/202110/surprising-link-between-creativity-and-false-memories
******* https://pmc.ncbi.nlm.nih.gov/articles/PMC8594559/
****** lets create an abbrev in 42: the steps are:
#+begin_src emacs-lisp

    ;; forget our special functions that auto insert.
    ;; we dont have any variable or filename of our abbrev, so we first need to bootstrap by creating our abbrev table AND file
    ;; at first it will NOT read our file, and the variable needs to setup first, so its a chicken or egg problem. We first create our file, start Emacs which creates an empty vector (which is our table). upon saving it will finally read our file
    ;; redefine abbrev-file-name

    (setq abbrev-file-name "/home/ardie/Documents/delete/another_defs")

  ;; (add-hook 'org-mode-hook 'abbrev-mode)

  (setq xx-abbrev-table (make-abbrev-table ))


  (define-abbrev-table 'xx-abbrev-table
    '(
     ("fn" "function")
     ("function" "function name (x) { return x; }"))
    )

  (define-derived-mode xx org-mode "xx"
    "A major mode for xx."
    :abbrev-table xx-abbrev-table
    (abbrev-mode 1)
    )


  ;; once we save we can see our changes in those files

  ;; remember to comment the define-abbrev-table becoz it will overwrite that file everytime

  ;; So, even after all this, it still might not work. If so, we need to actually include these functions inside abbrev-file-name, so that Emacs can actully read it and do something

  ;; inside abbrev-file-name

  (define-abbrev-table 'ardie/c++-mode-abbrev-table
  '(
    ("qd" "qDebug() <<" nil :count 7)
   ))

#+end_src

****** lets read about Raylib
#+begin_quote


Several C implementations exist for generating and solving mazes, ranging from simple recursive backtracking to complex roguelike grid systems. Joe Wingbermuehle's 1999 maze.c uses a randomized depth-first search algorithm to carve paths through a grid, initializing the map with walls and recursively visiting unvisited cells to create a perfect maze. 

Maze Generation and Solving
Algorithm: The code typically initializes a grid filled with walls (1), then uses a recursive backtracking or "carve" function to remove walls (0) while moving in random directions until the entire grid is explored. 
Simulation: Advanced versions, such as those from Purdue University assignments, include functions to simulate an agent's movement through a generated maze based on a direction file, returning the number of steps or -1 if the path is invalid. 
Roguelike Style: Projects like "Decoded: Rogue" utilize K&R style C functions to handle data copying and maze structures, often employing a "cell" abstraction where walls occupy entire grid cells rather than single characters. 
Code Example (Simplified Recursive Backtracker)
A basic implementation initializes a 2D array, marks the start cell, and recursively visits neighbors to carve paths:

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define WIDTH 21
#define HEIGHT 21

// 1 = Wall, 0 = Path
int maze[HEIGHT][WIDTH];

// Function to check if a cell is valid and unvisited
int is_valid(int x, int y) {
    return (x > 0 && x < WIDTH - 1 && y > 0 && y < HEIGHT - 1 && maze[y][x] == 1);
}

// Recursive function to generate the maze
void generate_maze(int x, int y) {
    int dx[] = {0, 0, 2, -2};
    int dy[] = {2, -2, 0, 0};
    
    maze[y][x] = 0; // Mark current cell as path
    
    // Shuffle directions for randomness
    srand(time(NULL));
    
    for (int i = 0; i < 4; i++) {
        int nx = x + dx[i];
        int ny = y + dy[i];
        
        if (is_valid(nx, ny)) {
            maze[(y + dy[i] / 2)][(x + dx[i] / 2)] = 0; // Carve wall between cells
            generate_maze(nx, ny);
        }
    }
}

int main() {
    // Initialize maze with walls
    for (int y = 0; y < HEIGHT; y++) {
        for (int x = 0; x < WIDTH; x++) {
            maze[y][x] = 1;
        }
    }
    
    // Start generation from (1, 1)
    generate_maze(1, 1);
    
    // Print the maze
    for (int y = 0; y < HEIGHT; y++) {
        for (int x = 0; x < WIDTH; x++) {
            printf("%c ", maze[y][x] ? '#' : '.');
        }
        printf("\n");
    }
    
    return 0;
}

#+end_quote
****** we might have to lower org-drill-learn-fraction to increase frequency of our org-drill
****** a debugging framework in eLisp and Lisp, why is debugging so hard in Emacs and Lisp
****** the only thing you need to master Emacs is "highlight your text"
****** the real reason why we're changing is because I keep accidentally pressing M-v for scroll-down-command, so doing it this way feels like a lot of win
****** 2 recipes involving lovi lovi, or Flacourtia Intermis
******* https://yumpickles.wordpress.com/2012/02/24/lovi-lovi-flacourtia-inermis-pickle/
******* https://archwaytomomsgarden.blogspot.com/2014/10/lovi-chutney-sweet-sweet-lovi-chutney-i.html
****** we should also post about infra-sounds of AI data centers.
****** We need to post about 42KL somewhere in Facebook AND Developer Kaki
****** we need to practice typing using home rows: https://www.keybr.com/
******* lair liar line rail nail linen learn alien all real ill earlier
******* nail alien real lie lane lean learn 
****** https://www.coddykit.com/pages/blog-detail?id=512749
******* we need to read about code visualization
****** Dev Kaki
******* https://www.nvidia.com/gtc/?ncid=ref-inpa-296-prsp-en-gb-1-l11
******* select a session and STAY at least 5 minutes, and take a screenshot of u joining the session, and send to:
******* https://forms.gle/6bHa6ijhh15sgCwCA
****** [[https://dev.to/darkwiiplayer/an-introduction-to-coroutines-38i4][Introduction to coroutines (and stackful vs stackless)]]
******* dealing with terminoloy
******* coroutines: functions that can pause itself
******* there is caller and the callee, the caller CALLS the function, it EXECUTES, then RETURNS to the caller
******* coroutine: the caller CALLS the function, it EXECUTES, then YIELDS to the caller
******* what is YIELD?
******* Asymmetric coroutines: similar to functions, once it calls a function, control can only be returned from the function called. 
******* Basically: it cannot be RESUMED (from the ~top), only yielded to
******* Symmetriccoroutines: control can come from anywhere, we will call it TRANSFER
******* ----- continued -----
****** [[https://www.youtube.com/watch?v=H7c92T-megA][we need to learn about clothes]]
****** [[https://thephilosophicalsalon.com/avengers-and-the-endgame-of-liberalism/][WRITE about Avengers Endgame and the end of liberalism]]
******* https://www.thestranger.com/film/2018/04/27/26108191/a-fucking-liberal-is-the-villain-of-avengers-infinity-war
****** [[https://www.youtube.com/watch?v=hKHjH5OU7Eo][Artists dont follow rules]]
******* be delusional.
******* People go, "oh no, thats not realistic" - GOOD
******* "oh, thats not going to happen" - GOOD
******* And people are saying, "whats wrong with you" - Youre on the right track.
****** [[https://www.youtube.com/watch?v=lhwnOBjSklE][verbal orange cones]]
****** [[https://www.youtube.com/watch?v=J-SH18dtBlY][speech jammer]] 
****** https://www.youtube.com/shorts/bwAKNGgMKg0
****** mu4e
#+begin_quote



https://cachestocaches.com/2017/3/complete-guide-email-emacs-using-mu-and/

How to setup email in Emacs
-install mu (but mu is only for indexing and searchng emails)
-offlineimap (becoz mu needs another software to keep a local copy of ur emails)
-offlineimap can set up 2 emails (in the example, the guy sets a script to sync both emails every 5 minutes)
-the configs are stored inside  ~/.offlineimaprc
Concepts
--in that file, just like Git, there is a "named" local and remote repo of your email
--you can choose any folder
--you can can STORE YOUR PASSWORD, not recommended, usually under remotepass\
--we dont want that, so instead we can use Python and GPG
--"folderfilter" can filter folders, as well Googles bad default "All Mail/Important"
--to keep indexing we put "mu index" via postsynchook
--this is DONE, so we call offlineimap thatstarts a process and syncs every 5 min
--but this means leaving terminal open, so we start a daemon
--mu4e comes installed with mu (mu is the "real package", mu4e is the Emacs package that comes with it), we need to include mu4e path in our Emacs load-path
--in "headers", we have severl shortcu options
--by setting mu4e-contexts variable, we can make our mu4e aware of our email source, if its Gmail, the variable mu4e-trash-folder and mu4e-refile-folder is changed. So our delete commands for example, are context-aware
--he defines mu4e-refile-folder as a function, that filters using (cond) and (mu4e-message-field msg :subject) to check the message's subjct against a text and filters further more
--

mmu4e alert
-mu4e-alert-enable-mode-line-display calling this would update modeline with unread msgs
-which means we need to run-with-timer
-problem: mu4e maintains connection with server, which mu index will never (we NEVER get email updates)
-we solve this with mu4e~proc-kill
-we put all these all in use-package (as in example)
-we set variable mu4e-alert-interesting-mail-query for selective alerts, becoz Google being weird, marks all folders moved to trash as unread
-to send email we need SMTP, we set a bunch of SMTP parameters just our like Python Flask project. But we also have account specific parameters (we use setq for the SMTP, and mostly defvar for the account-spec)
-the my-mu4e-set-account function is to combine (set operation-ish) SMTP values and account-spec values,


https://www.macs.hw.ac.uk/~rs46/posts/2014-01-13-mu4e-email-client.html

-offlineimap mentioned above is a tool (offline) to sync copy. An alternative here is mbsync.
-just like before we are using symmetric encryption (one way, public key only). We create a dotfile, written in is our password, and generate a public key
-they both seem to use 2 different hooks
-there also some variables not used in previous article: mu4e-get-mail-command (here we set to a mbsync command) mu4e-html2text-command mu4e-update-interval mu4e-headers-auto-update mu4e-compose-signature-auto-include
-we got more commands here


  https://f-santos.gitlab.io/2020-04-24-mu4e.html

#+end_quote
****** [[https://www.youtube.com/watch?v=ZJ09dPNJ8G8][How programming jobs get created and destroyed]]
#+begin_quote

 
How IT/programmers jobs are actually created.

He hasnt worked in gaming indusrty and foesnt plan to

everything tech indusrty is largely custome in the last few decandes

the non tech is largely the same.

So all programming jobsh is largely between a speectrum and a slidin scale, mainigng old code and a new stratup (and everyinqg in between)

It was a lot like construction was, back before girders and planks were standardized, and construction used whatever resources they found at the time.

Nowadays, the analogy no loner works, becoz construction is mostly standardized, nad programming isnt (even for "big" companies)

what happend:

 - some gets an idea,
 - tis person, asometimes a solo entrpnour, getting money from investors, or gets money from a company
 - why is tis money allocated, somtimes company gets somuch money, they spend all that money on a new projec
 - this was true years ago, when programmer salaries were through the roof
 - if this is not true, the money is borrowed or from investors, who believe once the money is built, he gets the money back.
 - NOW, assuming the person with the idea isnt building it himeseves, he needs tecanical people. hires people as employees, and hires consultants from company that bulds sofware on demand.
 - in ideal worlds, the first person they hire is a senior tech person to plan stuff, and hire others.
 - mostly its not ideal, so they hire recruiter from the same or a consultant company. If the person hires full consultant company, they also look for more people by looking for recuiters themselves.
 - 

What spawned the leet-code interviews



#+end_quote
****** Be consistent like Louis Rossmann, how can we provide a counter-incentive structure to (the massive incentive use of) AI.
****** YouTubers who have no issue with long/fat functions. And even those who like functions chunky (I like em chunky too, wink, wink)
****** The #1 reason to use Emacs is to write a diary
****** Cool video on what compilers do behind the scenes, explained in a very friendly manner. Also, now that Im going down the rabbit hole of programming langs again. I just realized English as a language has a lot ambiguity in it. It is "easy" only becoz of its dominance, but its actually difficult to master from a non-native speaker, becoz theres a lot overloaded terms.
****** The bullshitness of supply and demand (write this in an org file)
****** "Public school is about education. It is NOT job training. And it should not be. Otherwise, the capitalists win." 
****** [[https://www.youtube.com/watch?v=w3krYEeqnyk&t=1214s][conquering kubernetes with Emacs]]
****** [[https://people.kernel.org/linusw/rust-in-perspective][rust in perspective, AMAZING history of languages]]
******* What do you guys thik of this article?
******* Article says that Rust is attempting to raise the abstraction of the programming language. (and to consolidate Computer Science and Software Engineering) (Ardie: I have no idea what that means)
******* The first "real" Operating System that used virtual memory, used a language called Atlas autocode, a dialect ALGOL. 
******* TIDBIT: What is virtual memory, The infamous schizophreniac racist Terry Davis who created his own super tiny, super efficient OS, his OS doesnt use virtual memory, the result is super fast and efficient.
******* ALGOL inspired CPL which inspired BCPL which inspired B which inspired C
******* ALGOL was popular the time of UNIX, and C was not universally loved for valid reasons
******* Understatement: it was universally hated as well
******* The original Bourne Shell source code at the time, showed a dialect of ALGOL in the code. Stephen Bourne, created a set of C macros, so the C preprocessor would translate his code into C. He went to quite an effort to avoid C.
******* The article makes a VERY interesting point about TDD (Test Driven Development, you hear it everywhere in the real world)
******* A conference that is famous among UNIX circles at the time is the Garmisch conference.
******* Smaller mention in that conference. Of "analytic verification" and "correctness proof" ==> supposed to replace testing (or Test Driven Development)
******* TDD is mostly Software Engineering. Analytic vertification is mostly Computer Science.
******* TDD is not easy
******* Interesing:
******** The discussions in Garmisch had an influence on the programming language Pascal strings
******** "Pascal strings": a massive improvement over ALGOL
******** This String is stored in memory begins with a positive integer that defines of the string. The abstraction of strings is "raised", a higher level language thing. Different way to say it? In Pascal, strings in Pascal are set-entities.
******** How Niklaus Wirth (some creator of a language called Pascal), both critized C language. Something along the lines of "it gives the appearance of high level language while not behaving like 1". An example is how C has no "awareness" of array sizes and we are dealing with memory addresses. (In C, you have to pass the size of the array into a function). If any benefit of having this low level of control, is that the pointer can refer to anything, register/RAM/etc. Its debatable whether its "good" power and control.
******** Is C a high or low level language?.... C is misleading.... it claims to be higher than Assembly... but its actually amazingly stupid.... has no awareness of array or string size.... hence the necessity to pass size of arrays in a function
******* Conclusion: I dont hate C that much actually (or I should really hate it more than I should). Coz a language like C (effiency-obsessed, hacky syntax and directly manipulating memory) is like Thanos, its inevitable. If Dennis Ritchie didnt make C, someone else would make a C-like (and by extension Linux is inevitable). Also, becoz society is generally shitty (and rent-seeking trascends everything) a lang like C is inevitable. 
******* (Can you imagine, that compilers were once jealously guarded secrets? And a programmer had to pay LOTS of money for a compiler? in 1 example 200 USD, LOL)
******* Also conclusion: Never trust anyone who has only programmed in 1 language.
******* There are many other interesting points in this article that I either did not understand or mentioned
******* References:
******** https://hackaday.com/2018/04/04/the-basics-and-pitfalls-of-pointers-in-c/
**** Jobs:
***** [[https://app.outlier.ai/en/expert][Outlier tasks]]
***** micro1
***** Interesting companies
****** PostCo: really likes open minded developers, who learn rare stuff. says want developers open to learning Ruby on Rails 
****** Hero Plus Group: uses Ruby in Rails. Specifically mentions Flask.
***** https://my.hiredly.com
***** https://www.maukerja.my/
***** https://www.jorawork.com/
***** https://www.ricebowl.my
***** Read about orchestration and automation
***** about Google cloud platforms: Snowflake and Databricks (good to have)
***** maybe SQL and Azure diffs
**** Emacs
***** We need to: how to get inline rust documentation in emacs without lsp server
***** We need to: what is the qch file format qt
***** Convincing others:
****** Non-destructive ways to test Emacs packages:
******* use the try package. Then do the usual use-package, or any normal config for that package you found online.
***** Also try Emacs Application Framework on a new laptop
***** You like trying cool custom personalized Emacs el. This one is useful simpler bookmark, might help a lot in you html editing: [[https://github.com/joodland/bm][here]]
***** we are professional, so we need to make Python SUBMIT to us. [[https://emacs.stackexchange.com/questions/3372/coloring-indentation-levels][Color diff indentation levels]]
***** web-mode-element-wrap must be hydra-ed. We also need to auto-select a whole delimiter. But first try the stackoverflow templating engine trick.
***** We need to learn this Emacs [[https://emacs.stackexchange.com/questions/23810/getting-proper-indentation-for-python-flask-templates][templating indent]] mode thingy
**** I read about ketamine, psilocybin and alcohol, and also neurotransmitter GABA
***** https://adf.org.au/drug-facts/ketamine/
***** https://www.psychologytoday.com/intl/blog/culturally-speaking/202312/the-magic-behind-the-molecules-psilocybin-vs-alcohol
***** https://my.clevelandclinic.org/health/articles/22857-gamma-aminobutyric-acid-gaba
****** Researchers are still studying the effects of increased level of GABA, for High blood pressure, Insomnia, Diabetes.
***** GABA presence in food:
******  kimchi, miso and tempeh
****** green, black and oolong tea
****** brown rice, soy and adzuki beans, chestnuts, mushrooms, tomatoes, spinach, broccoli, cabbage, cauliflower, Brussels sprouts, sprouted grains and sweet potatoes
**** [[https://ringgitplus.com/en/blog/income-tax/how-to-file-your-taxes-for-the-first-time.html][read on how to do e-filing for d first time]]
**** Read about your Hugo
***** Understand layouts and everything inside (partials, shortcodes, _default)
***** When you replaced your /layouts folder, it fails, simple rename back /_layouts
* Piano (no social media progress)
** You need to buy a stand
* MyKasih, SARA, MySTR
** https://bantuantunai.hasil.gov.my/2026/Identity/Account/Login
** https://checkstatus.mykasih.net/sara2/checkstatus
* More org notes
*** some YSAC u did before
*** your chocolate donut (combination of Jamie Olivers friend & Gordon Ramsay)
** For suit, call these numbers for material. (Mention that Sparkle, Lot L-D 1&2, Pudu Plaza, KL recommended these guys)
*** 011 70018033
*** 013 343 2049
*** 018 398 5048
* Address:
** G-12-30, BLOCK G MENTARI COURT Gate 1, Jalan PJS 8/9, Bandar Sunway, 46150 Petaling Jaya, Selangor, Malaysia
