#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="zoho_ticket.css" />
#+OPTIONS:  toc:nil num:nil ^:nil


* Reminder
** Remember what Chomsky said
*** societies ban certain discussions on purpose to  keep the illusion  of freedom of discussion going. 
*** Most reporters worth their salt, take their job as a mostly a joke. They know the illusion of freedom of speech
*** remember, you made the FUCKING d minor prelude??
* What to do today:
** TODO 
*** read about database versioning
*** scrub shoe sole at night
** Not sure what we  have to do with our Java links
** wrote a little n Scriabin nocturne
** TODO 
*** move the new hydra to 1 of the remote, but also clean it again
*** Doom Emacs, try with Emacs 29, and change the init-directory
** Read about your Hugo
*** Understand layouts and everything inside (partials, shortcodes, _default)
*** When you replaced your /layouts folder, it fails, simple rename back /_layouts
** contact the fabric guys for your Myanmar project
** buy the jean bag from Pudu Plaza
** You managed to obtain 25 us dollars. You have to think of a cool way to play with that.
** do your new hiking shoe
** Remember you done it before, the kind of Sam Seder-ish intellect fuck-off, it feels right. 
** remember ur extreme writing skills. Your skills are a million times better than the other staff
** Mask handmade practice, start with small paper mache bowl
** Yammer 6:
*** Sometime at  the end of last year. i got a task relating to counting the lines of a file, and piping the output (number of lines) back to Magik. I proposed a solution using only Powershell. And also solved the permission problem using the lines,
#+begin_quote

PowerShell.exe -ExecutionPolicy Bypass -File runme.ps1

#+end_quote
*** Which means you no longer need to change ExecutionPolicy per every environment. And this does not result in any changes in configurations, or any writing to disk. You just bypass policy per script. Powershell is increasingly being used by many programmers who deals with Windows who just needs a quick ad-hoc calculation. The task insisted on Java (at first) and then Python. Python apparently was not an option, becoz installing Python environment required escalating that issue to the top, becoz its not in our environment. (Python also has virtual environment which makes it very safe to experiment with modules). But Java interoperability is certainly overkill, for something as simple as counting lines. One has to  compile the code and include that class in an path  environment. One also has to put annotations for each function you want being called in Magik (although that I think about  it, why cant we just count lines directly in Magik? Maybe the script was meant to grow bigger?). 
*** 
*** So we now turn our attention to Powershell. Powershell is more advanced than batch. And you can also call batch files in a Powershell script (but not the other way around). Powershell is avilable   by default in all modern Windows. And since it is relatively new and continuously being updated, it might be more secure than batch. 
*** SmallWorld also has limited integration with the underlying OS (operating system) and has to rely on external programs to be more flexible. But Powershell has a lots of cmdlets capable of doing this. The key to using Powershell in Magik is
#+begin_quote

system.input_from_command()

#+end_quote
*** There is a blog by an old time SmallWorld user who consistently uses Powershell in SmallWorld to solve quick ad-hoc problems. 
*** (There are also 13 other methods to bypass Powershell execution policy according to [[https://www.netspi.com/blog/technical-blog/network-penetration-testing/15-ways-to-bypass-the-powershell-execution-policy/][this]]). 
** Yammer 7:
*** https://geospatialworld.net/article/gis-maintains-a-single-source-of-truth-for-utilities/
* Piano (no social media progress)
** You need to buy a stand
** Post on FB after its done (things that happened):
*** Write about piano, how theres a strong argument to be made of how the only people who like Schoenberg of deluded elitists. True snobs, who fail to look inside themselves. And there are plenty of serious musicians who dont get or even dislike Schoenberg. Turns out I also hate Schoenberg. Also write something about comparing Scriabin and Schoenberg.
**** https://www.talkclassical.com/threads/arnold-schoenberg-1874-%E2%80%93-1951.4505/
*** Guy who knows about ergonomical split keyboards, presents a study (Masters? PhD?  something else?). And absolutely impressed the judges. I  even  feel  amazing his success on Reddit. People dont know that ergo-keyboards literally reduce injuries and  pain (pre-existing or  otherwise). [[https://www.reddit.com/r/ErgoMechKeyboards/comments/1h7r6de/just_finished_my_thesis][Link]]
*** Amos Yee, I dont know anything about him, and only remember him from a YouTube video where he mocked Lee Kuan Yee and Islam. Never was particularly offended, obviously. But then I saw ShoeOnHeads response to  his video defending pedophiles. I searched his name on Google. Interesting results, most English-language results highlighted his child sex case, while most Bahasa Melayu results highlight his criticism of religion. (In fact, one Bahasa article only mentioned his child sex case at the VERY end). Even after decades of sacrifice, Malaysians still like their pedophiles. Holy shit, just thinking about that, makes me want to assassinate an random Ulamak.
* More org notes
** For your recipes
*** Balti
*** some YSAC u did before
*** your chocolate donut (combination of Jamie Olivers friend & Gordon Ramsay)
** For suit, call these numbers for material. (Mention that Sparkle, Lot L-D 1&2, Pudu Plaza, KL recommended these guys)
*** 011 70018033
*** 013 343 2049
*** 018 398 5048
* Read
** endometriosis
*** The only way to defniitely diagnose endometriosis is laparoscopy. A small camera looking into your pelvis
** https://www.medicalnewstoday.com/articles/315066#treatment-and-self-care
** abdominal bracing
