#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="zoho_ticket.css" />
#+OPTIONS:  toc:nil num:nil ^:nil


* create a shortcut, for duplicating immediate line im on. no need for 3 actions of selecting, copy and paste, this is important in hydra
* create 2 more "themes"
* title window indicating runlias environment. thats pretty cool.
* we need to write or practice, whatever, quickly switching between proc and method
* The nature of documentation
** and also quickly switching between slots and shared variable
* What do we do right now
** Finish reading  the doc you downloaded
* PNI
* What to do later
** Remember what Chomsky said
*** societies bans certain discussions on purpose to  keep the illusion  of freedom of discussion going. 
*** Most reporters worth their salt, take their job as a mostly a joke. They know the illusion of freedom of speech
*** remember, you made the FUCKING d minor prelude??
* What to do today:
** Remember you done it before, the kind of Sam Seder-ish intellect fuck-off, it feels right. 
** Go to CIMB for checking of fiver attempt
** buy battery 
* Piano (no social media progress)
** Bought a simple mask, not worth it,  painting it for now. I would most likely over-think it
** You need to buy a stand
** Post on FB after its done (things that happened):
*** I did the mask experiment. Interesting reaction, Meleys especially, being the emotional creatures they are, wwere more likely to judge my music. I think Meleys will forever te emotional creatures till the end of time. Millions of years into the future
*** I went to some anime shop. Asked for an Attack on Titan merch or anything. Im just a casual fan, was curious anyway. Guy took my request over-serious, went into a long explanation of several of their lines. I usually dont cringe at enthusiasm (passion makes anyone attractive to my eyes), but I felt this one, 2nd-hand embarassment. 
*** Learnt a new phrase, 2nd hand embarassment. Meleys dont usually feel it (being the psychos that they are, but I felt it)
*** Indians love micro-managing people  at work, huge problem for freedom to develop your skill and grow
*** Misogyny and excessive love of your own mother are closely linked. This is a slight exaggaration, but there is some truth in it
* More org notes
** For your recipes
*** Balti
*** some YSAC u did before
*** your chocolate donut (combination of Jamie Olivers friend & Gordon Ramsay)
* Read
** endometriosis
** https://www.medicalnewstoday.com/articles/315066#treatment-and-self-care
* SL
** Peanut butter
** throat lozenge 2
** chocolate 1
** 
