* Python Django framework
* Predictive analytics
* machine learning
* material genome software
* preditive maintenance
* condition monitoring diagnostics of rotating machines
* python pandas  
* Notes:
** https://skymind.ai/wiki/lstm
*** A beginners guide to LSTM's and Recurrent Neural Network. One is (RNN) time dependent, one is not. 
*** The RNN preserves sequential information in the hidden state. 
*** The output of the hidden layer is used as input to the next time step. 
*** The sum of the hidden state and weight is squashed by a funtion (eg. logistic sigmoid function). Because of this feedback loop, each hidden state contains not only of (directly) previous hidden state, but also those before h_t-1 as long as memory cna persist
*** Recurrent nets are old (like most neural network), and major OLD problem is the "vanishing gradient problem"
*** LSTMs are a variation of recurrent net. They help preserve the error that can be propagated through time and layers. By maintaining a more constant error, they allow recurrent nets to continue to learn over many time steps (over 1000)
