* Steven Zapata
** https://youtu.be/AuBpYY-wOv8?t=11350
*** How to relax and develop confidence as an artist
** https://www.youtube.com/watch?v=AuBpYY-wOv8
*** "Theres not a lot of pre-made market for artists" - Designing Monsters with Class (3:44:00)
*** "Everything in life is hypnotizing people into not being creative, into not being artists" (3:50:30)
** https://www.youtube.com/watch?v=1CK3WI46ns4
*** "If you ever pause a movie frame, and you get an under-exposed picture, theres barely anything there. Which means most of the time, in a movie, your brain is interpreting everything (your brain is completing the picture)" (3:32:00)
**** So much of art, is the audience interpreting everything. This makes art as a conversation, as a living thing, extremely difficult.
** https://www.youtube.com/watch?v=9yCdQleLsO0
*** "Art is hard, art is difficult. Its a struggle of so many things other than the skill, other than the HOW you make the art. And I feel so few people quit becoz of (their lack of) skill. Art kills people. When people hang up their hats, that they just cant bear it anymore, its not becoz of problems with their skill. Its problems with everything else, their mental health, what they expect of themselves, what people expect of them, what people need of them. Art in the small sense, is losing its value in the modern world. In todays world, you can barely get anyone to pay for it, everyone just expects it for free, or at least cheap. Thats a hard fact on the people who have to do it, on the people who are going to do it no matter what. Unfortunately, its a feedback loop, one breeds the other -> You HAVE to do it, so you do it for less pay, a group of people (artists) eventually do that, social status goes down, and it produces a feeling that its not valuable. And yet, art itself has not changed. Art itself is unblemished and untouched. It is only the conditions around it that has changed." (23:30)
** https://www.youtube.com/watch?v=LqOhJXOApGI
*** "Whats your opinion on the idea that AI-generated works is not art. And if you believe that, whats your stance. I actually dont think its super important whether its art or not. Coz the label of art is handed out subjectively. I think this conversation needs to be argued on something more substantive. I personally have no emotional walls on whether people label it as art, coz everybody's definition of art is different. Its not about what art is and what isnt art. The real argument is about unethical and probably illegal data acquisition"(28:40)
* Why Its Rude to Suck at WarCraft:
** https://www.youtube.com/watch?v=BKP1I7IocYU
*** Instrumental play vs free play
*** "Success is relative and socially defined" (9:11)
*** paratext? - (19:18)
**** Gerard Genette - a book contains text (primary text). And paratext, stuff that is not primary text but completes the book (Eg: Title, Cover Artwork, Foreword, TOC)
* Also another art:
** https://www.youtube.com/watch?v=BOp5DYZZRtc
*** Sometimes, a piece of art is so good, so beautiful, that its most appreciated in silence. Everyone who has been to a museum, knows what Im talking about. But that doesnt mean millions of people dont wanna see it. It just means that this type of content/art/art-content generally generates a different type of response. (6:28)
* Top marginal tax rate (write about it):
** https://www.youtube.com/watch?v=UwJH5kyOOQU
* Fake vs real magic.
** https://www.youtube.com/watch?v=omipHCbh_v8
*** "Over dinner, we were talking about the difference between real and fake art. Theres this paradox, that art seems to be incredibly valuable. And yet, that value is not located in the object itself. A forgery is literally an exact copy of that masterpiece. And the real masterpiece, even if it suffers some damage, is still incredibly valuable. What worries me about the way you value your enterprise, or at least the way you seem to be linking our rationale/scientific project with religion is right here. Magic is actually a better analogy. Paradoxically, fake magic is real magic, and fake magic is real magic. The only real magic in the world produced by magicians is the fake magic. Someone like Derren Brown will tell you, no I cant read minds, its all fake. But the surprise is that even when knowing its fake (aka the method revealed), your mind is still boggled by how the illusion is acheived ("how can the human mind be tricked by something so simple?!"). Sometimes the sheer effectiveness & simplicity of the method is the only real magic. Whereas the fake magicians are the ones pretending to be real, or not acknowledging the real mechanics behind what makes it effective. What worries me is the way in which you describe the power of myths and stories, is I think the leverage or utility of these stories can be had, while acknowledging the stories behind it." (0:14)
* I think literate programming is a bad idea.
** https://www.youtube.com/watch?v=SzA2YODtgK4
*** My intuition proved correct once again. This time about literate programming in org-mode. "I think literate programming is a bad idea. For example, if you have some kind of project. I think having a good programming project, is having code that can change easily. And I think having a lot of comments that needs to be changed alongside the code, will make it harder to change, and will eventually become deceptive becoz people will not always change these comments"(25:40)
* https://www.youtube.com/watch?v=NgJxVkz2mjo
** Some mechanisms arent designed at all, they are caused by accidents. This mechanical goat is simulating an accident. Theres an interesting dynamic between predictability and accident. I want the machines I make to be predictable, even if its simulating an "accident". Craftsmen like us, are tourists to the realm of Engineering, but we dont necessarily speak the language.... Mechanisms are a balance between freedom and constraint (interesting artistic analysis). Too much freedom, and this mechanical doll's writing becomes meaningless scribbles. Too much constraint, and he stops dead.
** Careful work has been done to keep the string in this cat tight, until the poisoned milk takes effect. I want to make a new machine that contrasts the rigid state of the living cat with its haphazard collapse. There'll be a strict controlled women with an emotionally unstable man. Im going to call it "bad news"
* https://www.youtube.com/watch?v=W6QAqU2KpaY
** Noam Chomsky destroying a libertarian.
** Why "increase in standards of living" is not a good justification for Capitalism.
** There was rising "standards of living" in slave societies. As well as rising standards of loving during Hitlers rise to power.
** Slaves were often had much better living during the 19th century than the 18th century. Is that an argument for slavery. No, its a TERRIBLE argument.
** You give the same arguments of "economic growth" for Stalinism. There was very substantial economic growth during the Soviet Union. It was once the 2nd world until 1989, then it became the 3rd world due to Capitalist Reforms. Theyve had 10 years of Capitalist Reforms which have pushed them right back into the 3rd world where they came from. In fact, Western leaders were in fact annoyed by the success achieved in the Soviet Union before that, they didnt really care about the atrocities committed. In fact, President Harry Truman admired Stalin, called him an honest man. The West didnt really care about the atrocities in Russia.
** "If our Capitalist system is so bad, why hasnt there been better greater movements to challenge it".
*** Answer: There have ALWAYS been challenges.For example, we have a very violent labor history. Hundreds of American workers were being killed right into late 30's, in the process to finally get labor right. There have been very extensive challenges through the 50's. In the 60's, the whole thing blew up, and many concessions had to be made. And it continues.
*** Even the "challenges" argument is bad. Slavery went on for centuries and centuries without any challenge. Did that justify slavery? In fact, the slave owners were giving arguments like yours. Read arguments by George Fitzhugh, who was the leading the spokesperson for slave owners in the South.
*** He had pretty powerful arguments. "Look, the reason you Northerners were against slavery coz youre anti-Negroe racists. We on the other hand, are not racists. We believe you should take care of your subjects, so we treat them nicely. Like an analogy with car. If I buy and you rent a car, which car will look better in the long term. Obviously an owned car, coz it will be taken care of. While when you rent a car, you can just throw it away when youre dont with it, and get a better one. ". Hence, similar arguments were used for the right to own a slave.
* https://www.youtube.com/watch?v=qu0yNdnjeAU
** Write about this one. Simply, class discrimination doesnt really replace racial discrimination in any shape or form. Certainly, in America. class oppression is used as a tool to perform racial oppression. Interesting how human nature has not changed.
* https://www.youtube.com/watch?v=u4kMUk7sCUs
** The UNIX war saga (7:30)
** SCO files 4 lawsuits against several companies that used Linux. Claiming the Linux source code belonged to them (copyright)
** SCO source division - plain evil. They were going around to Linux customers, primarily in the corporate space and charging them 699 US dollars per CPU to be using Linux.
* https://www.youtube.com/watch?v=MM6GzlhJrxw
** You dont think Gold can be manipulated. So you think Gold has some intrinsic value that paper money does not. Why instead of Gold, we cant have Iron as the standard. Whats the difference between Gold and Iron? Why not use something that people ACTUALLY consume, like water, or something more valuable like trees. You understand, there's no intrinsic value to Gold, its just at one point people accepted "yeah, ill take payment in Gold". Just like paper money, its an agreed medium between people exchanging stuff.... Sorry dude, we're gonna do Iron, you can keep your Gold. We're gonna do Iron, Iron is so much cooler, you can soften it with heat, you can harden it, you can anneal it. Transform it into a blade, shape it into an artwork. You can keep your Gold, Gold is boring. (6:15)
* https://www.youtube.com/watch?v=6aRRyfCZxD4
** Atheism.
* https://www.youtube.com/watch?v=CFRhGnuXG-4
** Programming
** Methods to denest
*** Extraction
*** Inversion
**** Inversion is super-super simple. If you are over-thinking about it, youre doing it wrong. You just move the unhappy/negative block up, making it first.
* https://www.youtube.com/watch?v=iQ3o94o9PPQ
** A book that depiects or describes sex acts or positions, doesnt teach children how to perform those acts. Anymore so than a book that describes the civil war teaches children how to start a civil war (15:45x)
