
* Things we installed: Raylib
** We installed it, the commands we used:
#+begin_quote

git clone --depth 1 https://github.com/raysan5/raylib.git raylib

cd raylib/src/

# ===== To make the static version.
# ===== We used the static version, becoz if you dont know that's what you use
make PLATFORM=PLATFORM_DESKTOP

# ===== Static version.
sudo make install

#+end_quote
** And to compile our 1st example:
#+begin_quote

gcc -o test.exe blocksIntro.c -lraylib -lGL -lm -lpthread -ldl -lrt -lX11

#+end_quote
** 
* Pointers are almost like a completely C invention, an important disticiton made between address and value inside address is a C inventino
** a constant pointer VS a pointer to a constant
#+begin_src c++



  int aNumber1 = 20;
  int const aNumber2 = 99;


  // The OLD way I memorize is constant pointer VS pointer to constant,
  // is that asterisk(*) serves to take emphasis away,
  // so you ignore the * in the declaration 

  int const *imInside = &aNumber2;

  imInside = &aNumber1;
  // ----- this will fail
  // *imInside = 2000;





  // we learnt the BEST way to read declarations. And yet, it doesnt work in this example, we KNOW now
  int* const imOutside = &aNumber2;

  ,*imOutside = 2000;
  // ----- this will fail
  // imOutside = &aNumber1;


#+end_src
** Of course we now learnt the BETTER way to read declarations. (Again, our new way makes us fail in the constant pointer above)
** We now KNOW the answer. When reading boustrophedonically
*** when reaching "from the left", if we encounter either const, volatile or \*, we keep reading "from the left"
** a double pointer (our personal internal term: pointer pointer)
** string literals are not pointer type, but l-value, both of these work:
*** but when you put it in an expression, they magically dont work.
#+begin_src c

  char *b = "hello there";
  char[] = "hello there"

#+end_src
*** but this will not work, [[https://www.reddit.com/r/learnprogramming/comments/ziesu8/invalid_initializer_in_c/][reddit, invalid initializer]]:

#+begin_src c++

  char b[]=(a>0)?"positive":"negative";

  // (a>0)?"positive":"negative" is an expression that produces a char * value
  // although it seems to return a fixed size, the compiler cant know beforehand, so it treats it like an r-value



#+end_src
** so a string DOESNT EXIST (more or less) in C, hence we have %c and %s when printing the same "char *somevar"
** More buggery on arrays and pointer
*** This is more mind-f***ery, why does the 1st fail, but the 2nd work?
#+begin_src c

    char newOne[];

    newOne = "tetsy";
  

#+end_src
*** This fails
#+begin_src c

    char newOne[];

    newOne = "tetsy";
  
#+end_src
*** [[https://stackoverflow.com/questions/8040284/why-is-literal-string-assignment-in-c-not-possible-for-array-with-specified-leng][more string literal assignments from stackoverflow]]
* We finally FOUND a way to understand pointers for REAL, the key is understanding rvalue and lvalue and it pertains to compile-time and run-time
** https://stackoverflow.com/questions/579734/assigning-strings-to-arrays-of-characters
** https://stackoverflow.com/questions/8040284/why-is-literal-string-assignment-in-c-not-possible-for-array-with-specified-leng
** Both of these links pertain to assigning string to characters, but more importantly, variable declaration, is an lvalue which is why this will work:
#+begin_src c

  /* -----this WILL work */
  char var1[] = "some string";

  /* -----this WILL work */
  char *var1 = "some string";

  /* -----this WILL work */
  char *var1;
  ,*var1 = "some string";


  /* -----this WILL NOT work */
  char var1[];
  var1 = "some string";



#+end_src
* WRITE about how &someVar++ doesnt work becoz & is a function, and it accepts an lvalue. WE SHOULD ALSO TEST IT
* MORE LINKS, this ones Raylib lib help: https://raylibhelp.wuaze.com/_info/raylib-struct.htm?i=2
* Build system, compilation and more:
** this link makes much more sense:x
*** [[https://www.steinwurf.com/blog/error-while-loading-shared-libraries][steinwurf: on thinking through loading our shared library]]
** Thinking through:
#+begin_src shell

   gcc -fPIC -c readme.c # c: Creating object file, fPIC: position-independent-code

   gcc -shared -o readme.so readme.o # o: output file, -shared: create shared object


   # ----- and finally

   sudo ldconfig /home/ardie/my-personal-libs/shared-objects/

   # ----- note the the full file name is required, yes, this seems like OS-level stuff
   # ----- turns out you dont need LD_LIBRARY_CONFIG

#+end_src
** Useful to know, and to understand.
#+begin_src shell

  ldconfig -p | grep <some-lib-we-looking-for>

  # we know this
  sudo ldconfig /some/path/

  # lets look at the symbols, actually, nm is the dumber of the lot
  nm -D gl_ardie.so

  # more relevant for this task
  readelf -d /home/ardie/my-personal-libs/shared-objects/test.so | grep SONAME

  # seems similar t readelf, but looks better and more info, objdump can also do the same like nm using -D
  objdump -p libcurl.so.3.0.0 | grep SONAME

  # sometimes, grepping through the header files is much better

  cat /path/to/glad/gl.h | grep glad_glEvalMesh2


#+end_src