* 10 rules of low latency
** Database Index
** Payload compression
** Request Grouping
** CDN
** Load Balancing
** Vertical Scaling
** Cache
** Connection Pooling
** Message Queue
** Data Serialization
* Database concurrency
** [[https://www.youtube.com/watch?v=wEsPL50Uiyo][Understanding Database Concurrency Control is important]]
*** Understanding race condition
*** The example he shows, uses an update clause in JS db library
*** We learnt: the "await" keyword can only be used inside "async" function. Its pause execution until a promise resolves. The example is quite good, where a DB is waited first
** A way to solve it in PostgreSQL
#+begin_src sql

  BEGIN;

-- Lock the account row to prevent concurrent modifications
SELECT balance FROM accounts WHERE id = 1 FOR UPDATE;

-- Perform some application-level logic (e.g., withdraw funds)
-- ...

-- Update the account balance
UPDATE accounts SET balance = balance - 100 WHERE id = 1;

COMMIT;

#+end_src
* SQL grammar/syntax
** SQL generally returns sets (unless its an expression, that's another subject)
** this "set" can be further processed with "clauses", such as 
*** WHERE
*** GROUP BY
*** HAVING
*** ORDER BY
** Clause?
*** Clause = Subject + Verb
*** Independent clauses ->
*** "She sings"
*** "I went to the store"
*** Dependent clauses->
*** "That I read" in "The book that I read was good"
** Clause example:
#+begin_src sql

  SELECT	elective_class,
  SUM(elective_class) AS total_fees
  FROM students,
  GROUP BY elective_class; -- verbed, subject

  SELECT * FROM students
  ORDER BY elective_class ASC; --verbed, subject, adjective?

#+end_src
* An important precursor to understand Apache Kafka (maybe): [[https://mariadb.com/resources/blog/a-peek-under-the-hood-of-distributed-sql-engines/][Distributed SQL Engines]]
** 1st: the NON-distributed
** Approach 1: Multi instances of single server databases (replication/sharding)
*** This is just simple copying of the same DB. Obviously, this means writing overhead, coz wew need to write twice
** Approach 2: Sharding your data
*** "When you shard your data, you divide your data into shards, based on a shard key" - The shard key seems to be the code/query level too. This means ur app also deals with the shard key. There is also an overhead of refactoring, data balancing, maintenance. This is becoz, it works well when there is high degree of isolation in ur data (no need to query across keys or shard). But if ur dataset grows and becomes unbalanced, u need to modify ur shards and app code as well.
** Approach 3: Shared storage
*** This section is a bit confusing. Its multiple database instances that share the same physical storage. Unified interface, where queries are sent to any of the front end nodes (a DIAGRAM pastes here is helpful). 
*** This approach apparently, has limitations, latency increases dramatically with workload (especially Writes)
** Approach 4: Distributed compute, shared nothing
*** 
