
* Jinja:
** [[https://realpython.com/primer-on-jinja-templating/][realpython]]. Has primer on jinja templating. Better read this instead of searching forever for beginners doc.
** How to call function from within Jinja:
*** [[https://saidvandeklundert.net/2020-12-24-python-functions-in-jinja/][saidvandeklundert]] and some [[https://stackoverflow.com/questions/6036082/call-a-python-function-from-jinja2][stackoverflow]] shows . Basically, "normal html" has no awarenss of functions inside view. So this is necessary. 
*** The idea is:
#+begin_src python

  # ========== inside __init__.py im assuming, or any main file .py
  def clever_function():
      return u'HELLO'

  app.jinja_env.globals.update(clever_function=clever_function)

  # ========== and somewhere in your templates/
  {{ clever_function() }}


#+end_src
*** Another, this time a template/ file calling 2 functions
#+begin_src python

  def hello_world():
      return "hello world from within the function"

  def multiply(x, y):
      return str(x * y)

  func_dict = {
      "hello_world": hello_world,
      "multiply": multiply,
  }


  def render(template):
      # ===== snip
      jinja_template.globals.update(func_dict)
      template_string = jinja_template.render()
      return template_string




#+end_src
** Multiple inheritance, one trick is shown [[https://stackoverflow.com/questions/1976651/multiple-level-template-inheritance-in-jinja2][here]]:
*** by using includes in all in-betweens
#+begin_export html

{% include "some-parent.html" %}

#+end_export
*** So the naming I came up with might be base-layout.html -> inner-layout_h.html -> inner-layout_n.html -> post.html. 
**** where the _h, _n stands for header or navigation
** Jinja as problem of awarenes of dict structure . Hence, we use tricks like this:
#+begin_export web

{% for membersAnswer in membersAnswers.values() %}
    {% if loop.first %}

	{% for fieldname,answer in membersAnswer.items() %}
	    {% if answer.subgroupId is none %}
		<th class="w-20 p-4 bg-yellow-400">
		    {{ fieldname }}
		</th>
	    {% else %}
		<th class="w-20 p-4 border-x-2 border-yellow-600 bg-yellow-200 font-light">
		    {{ fieldname }}
		</th>
	    {% endif %}
	{% endfor %}



    {% endif %}
{% endfor %}



#+end_export
** Jinja2 award winning [[https://ttl255.com/jinja2-tutorial-part-4-template-filters/][blog]]
* Basics:
** [[https://www.askpython.com/python-modules/flask/flask-crud-application][askpython]] shows Flask CRUD
** [[https://www.silvaneves.org/deleting-old-items-in-sqlalchemy][removing old entries, or deleting with expired entries]]
* Alternative software:
** Cool list of software to view DBs [[https://stackoverflow.com/questions/66545908/how-to-see-sqlalchemy-database][here]]
** [[https://www.apriorit.com/dev-blog/web-python-libraries-for-database-management#using-python][site]] that shows specific modules/packages to connect to DBs such as SQLite or Apache, etc
** 
* Flask:
** Forms Basics:
*** Multiple buttons in a single form:, first do this:
#+begin_export html

<button type="submit" name="button" value="add">Add</button>

#+end_export
*** Then this:
#+begin_src python

  request.form.get("button") == "add"
  # will return true

#+end_src
* Flask environment
** Avoiding circular imports:
*** https://stackoverflow.com/questions/42909816/can-i-avoid-circular-imports-in-flask-and-sqlalchemy
** [[https://flask.palletsprojects.com/en/stable/cli/][palletsprojects]]. Has better links for configs. Example:
#+begin_quote

$ flask run --extra-files file1:dirA/file2:dirB/

#+end_quote
*** mostly becoz certain env variables are unsafe to have it running in production, hence some like  FLASK_RUN_EXTRA_FILES are disabled (?)
** Our way
#+begin_src python

  class Config:

    JWT_SECRET_KEY = "my-secret-key"
    JWT_TOKEN_LOCATION = ['headers']
    SECRET_KEY = "also_my_secret_key"
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    # ===== cool conditional example, fast, for prod and dev environment
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or \
        'sqlite:///' + os.path.join(basedir, 'app.db')
    # ===== can also do this
    if os.environ.get('YOURAPPLICATION_MODE') == "production":
        SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI')
        SECRET_KEY = os.environ.get('SECRET_KEY')

    # ===== from app.py
    from config import Config
#+end_src
* Flask authorization (middleware), not fun at all
** To learn basic, random, advanced:
*** we always use sha256 compared to those older ones
*** [[https://pypi.org/project/flask-auth-middleware/][protect routes here and there]] BASIC
*** [[https://variable-scope.com/posts/storing-and-verifying-passwords-with-sqlalchemy][variable-scope]] quite advanced with functions for password checking defined inside User model (Eg)
*** [[https://realpython.com/flask-google-login/][Google-login]]?
*** [[https://www.freecodecamp.org/news/jwt-authentication-in-flask/][freecodecamp]]
*** [[https://dev.to/abbyesmith/password-hashing-using-bcrypt-in-python-2i08][dev.to]] also has functions for inside model
*** [[https://www.geeksforgeeks.org/hashing-passwords-in-python-with-bcrypt/][bcrypt]] BASIC
** The first trick we first did was this:
#+begin_src python

  m = Member.query.filter_by(mcfId=mcfId).first() # ===== where 2nd mcfId is request.form['mcfId']
  isVerified = bcrypt.check_password_hash(bcrypt.generate_password_hash(password).decode('utf-8'), m.password)

#+end_src
** In [[https://tedboy.github.io/flask/generated/werkzeug.check_password_hash.html][check_password_hash()]], arguments are 1 - hashed password and 2 - paintext password, to compare against. But in our example, the plainttext is from our DB, and hased is from login form. Below is proper.
** One can:
*** hash during the argument when creating a user from User model. Like this [[https://www.digitalocean.com/community/tutorials/how-to-add-authentication-to-your-app-with-flask-login][link]]
#+begin_src python

  new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))
  # ...
  password = request.form.get('password')
  # ...
  check_password_hash(user.password, password) # ===== here its the DB first, form 2nd

#+end_src
*** with full conditional cases. Examples [[https://www.loginradius.com/blog/engineering/guest-post/securing-flask-api-with-jwt/][here]]
*** we wanna learn [[https://www.freecodecamp.org/news/how-to-setup-user-authentication-in-flask/][blueprints?]]
** We wasted so much time with JWT, SIMPLE, we need Javascript to set tokens in header, [[https://flask-jwt-extended.readthedocs.io/en/stable/token_locations.html][official site]] has great example
** Flask-Login
*** instead of using Sessions, we can try LoginManager (Flask-Login), heres the [[https://flask-login.readthedocs.io/en/latest/][link]]
*** [[https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-v-user-logins][miguel's]] blog
** SQLite:
*** One day we can try [[https://docs.sqlalchemy.org/en/20/dialects/sqlite.html#foreign-key-support][this]], so we can blindly and stupidly create Python on any setup.
*** 
** JWT (we dont understand this mostly)
*** [[https://hyperskill.org/learn/step/36181][IMPORTANT]]
* Flask SQLAlchemy, which is mostly used to avoid ORM pitfalls like SQL injection
** Relationships
*** [[https://medium.com/@mandyranero/one-to-many-many-to-many-and-one-to-one-sqlalchemy-relationships-8415927fe8aa][medium]] example for one-to-one & others
*** one-to-one puts foreign key on 1 SIDE. Becoz [[https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html#one-to-one]["the ORM considers the “one-to-one” pattern as a convention, where it makes the assumption"]], which means its a constraint on the code/ORM level, not SQL level. So the child.parent side is "expecting" a 1-to-1, but not constrained in the database itself.
*** [[https://medium.com/@philipdutra/understanding-relationships-in-flask-sqlalchemy-one-to-many-vs-many-to-many-6050d04c6cf0][one-to-many & many-to-many]]
*** 
*** We did this (no need that extra bracket):
#+begin_src python

  fide = db.relationship("Fide", backref="member", uselist=False)

#+end_src
** To avoid the headache of database relationship, we use, strings split into list, so later on we just use a join:
*** https://stackoverflow.com/questions/61013648/how-to-store-a-list-within-a-model-in-flask-sqlalchemy
** Dropping practice (from Brave)
#+begin_src python

  from sqlalchemy.engine import reflection
from sqlalchemy.schema import (
    MetaData, Table, DropTable, ForeignKeyConstraint, DropConstraint
)

def db_DropEverything(db):
    conn = db.engine.connect()
    trans = conn.begin()

    inspector = reflection.Inspector.from_engine(db.engine)

    metadata = MetaData()

    tbs = []
    all_fks = []

    for table_name in inspector.get_table_names():
        fks = []
        for fk in inspector.get_foreign_keys(table_name):
            if not fk['name']:
                continue
            fks.append(ForeignKeyConstraint((), (), name=fk['name']))
        t = Table(table_name, metadata, *fks)
        tbs.append(t)
        all_fks.extend(fks)

    for fkc in all_fks:
        conn.execute(DropConstraint(fkc))

    for table in tbs:
        conn.execute(DropTable(table))

    trans.commit()

#+end_src
** [[https://stackoverflow.com/questions/24289808/drop-all-freezes-in-flask-with-sqlalchemy][close_all_sessions() before dropping tables]]. One reply to comment correctly points version change means using close_all_sessions()
** What is this insane [[https://stackoverflow.com/questions/23714864/efficient-ways-to-store-multiple-excel-files-in-a-database][Excel shit]]
** Time our queries, [[https://flask-sqlalchemy.readthedocs.io/en/stable/record-queries/][link]]
** Faster deletes SQL:
*** https://www.sqlservercentral.com/articles/how-to-delete-large-amounts-of-data
** @classmethod tricks:
*** In Flask-SQLAlchemy, filtering queries based on conditions is a common operation. The query attribute available on your model classes, provided by Flask-SQLAlchemy, allows you to build and execute queries, including applying filters.
#+begin_src python

  from app import db, User

  # Find users with a specific username
  user = User.query.filter_by(username='john_doe').first()

  # Find all active users
  active_users = User.query.filter_by(is_active=True).all()

#+end_src
* Flask-ish
** Render persistent disk:
*** navigating and modifying the folders from inside Render Dashboard shell tab
*** [[https://community.render.com/t/files-in-render-disk-are-being-lost-with-starter-service/17440/4][use /data path]]. Being root is fine, it will persistent and be writable
*** [[https://render.com/docs/disks?_gl=1*1c3j8ip*_gcl_au*MTU0Nzc2NjkxOS4xNzQyNDUzMTcw*_ga*NDI4NTk4MDM0LjE3NDI0NTEyMTU.*_ga_QK9L9QJC5N*czE3NDY3MTU2NjEkbzExJGcxJHQxNzQ2NzE1ODkwJGo1JGwwJGgw#transferring-files][persistent disk]]
*** python write to disk
#+begin_src python

  import os

disk_path = "/mnt/data"  # Path to the persistent disk
folder_name = "my_folder"
folder_path = os.path.join(disk_path, folder_name)

try:
    os.makedirs(folder_path, exist_ok=True)
    print(f"Folder '{folder_name}' created successfully at '{folder_path}'.")
except Exception as e:
    print(f"An error occurred: {e}")

#+end_src
*** [[https://magic-wormhole.readthedocs.io/en/latest/welcome.html][magic wormhole to download files]]
*** [[https://www.youtube.com/watch?v=oFrTqQw0_3c][magic wormhole]]
*** [[https://render.com/docs/disks?_gl=1*18deote*_gcl_au*MTU0Nzc2NjkxOS4xNzQyNDUzMTcw*_ga*NDI4NTk4MDM0LjE3NDI0NTEyMTU.*_ga_QK9L9QJC5N*czE3NDY3MTI2NDQkbzEwJGcxJHQxNzQ2NzEzMzQ0JGoyMSRsMCRoMA..][monitoring Render persistent disk]]
** for uploads
*** [[https://www.pullrequest.com/blog/secure-file-uploads-in-flask-filtering-and-validation-techniques/][secure file uplaods]]
*** [[https://www.geeksforgeeks.org/uploading-and-downloading-files-in-flask/][file upload basics]]
*** [[https://blog.miguelgrinberg.com/post/handling-file-uploads-with-flask][miguel file uploads]]
*** [[https://imagekit.io/blog/how-to-upload-files-in-html/][basic element]]
*** [[https://www.pullrequest.com/blog/secure-file-uploads-in-flask-filtering-and-validation-techniques/][in flask]]
*** [[https://stackoverflow.com/questions/7076042/what-mime-type-should-i-use-for-csv][the mimetypethat should be used]]
*** We need database tracking each uploads.
#+begin_src python

  class File(db.Model):
         id = db.Column(db.Integer, primary_key=True)
         filename = db.Column(db.String(200), nullable=False)
         filepath = db.Column(db.String(300), nullable=False)
         created_at = db.Column(db.DateTime, default=datetime.utcnow)

         def __repr__(self):
             return f"File('{self.filenname}', '{self.filepath}')"

  # and do the usual db.session.add() db.commit()

#+end_src
* Moving away from SQLAlchemy, learning, or better control
** Apparently, there are lots of people using Flask without sqlalchemy. Some claim its easy, but you need to google a lot on sql queries. Read this [[https://neon.com/postgresql/postgresql-python][LINK]] someday
**** Also this [[https://www.psycopg.org/psycopg3/docs/][LINK]]
* SQLAlchemy:
*** https://docs.sqlalchemy.org/en/20/orm/session_basics.html
*** https://docs.sqlalchemy.org/en/20/core/pooling.html
*** https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Engine.dispose
*** https://docs.sqlalchemy.org/en/20/core/pooling.html#dealing-with-disconnects
*** https://docs.sqlalchemy.org/en/20/tutorial/index.html
*** https://docs.sqlalchemy.org/en/20/core/engines.html#engine-configuration
* Handling deletions, a huge decision:
** But, deleting data from DBS is [[https://softwareengineering.stackexchange.com/questions/159232/should-we-ever-delete-data-in-a-database][usually a GOOD IDEA]]
** Soft deletes are messy tricky, but [[https://blog.miguelgrinberg.com/post/implementing-the-soft-delete-pattern-with-flask-and-sqlalchemy/page/0][miguelgrinberg]] suggests other alternatives at article end, like separate table (my style)
** [[https://www.silvaneves.org/deleting-old-items-in-sqlalchemy][And heres what we used, removing old entries, or deleting with expired entries]]
** Examples of making a Query filter by default, we did NOT need it, as we added a password reset much later, if our code gets bigger, we will need this, coz imagine if we added an attribute like "hard delete", and we have 3 other parts of the site that uses this, we WILL eventually forget. But we dont need this, coz we only have 1 part.
#+begin_src python

  # ===== in Model.py

  from flask_sqlalchemy import SQLAlchemy, BaseQuery

  class MyFilteredQuery(BaseQuery):
      def __init__(self, entities, session=None):
          super().__init__(entities, session)
          # Apply your default filter here
          self._set_default_filter()

      def _set_default_filter(self):
          # Example: Filter all queries for a 'deleted' column being False
          if hasattr(self.column_descriptions[0].entity, 'deleted'):
              self.filter_by(deleted=False)


  from flask_sqlalchemy import SQLAlchemy

  db = SQLAlchemy()

  class User(db.Model):
      __tablename__ = 'users'
      id = db.Column(db.Integer, primary_key=True)
      name = db.Column(db.String(80), unique=True, nullable=False)
      deleted = db.Column(db.Boolean, default=False)

      # Assign the custom query class
      query_class = MyFilteredQuery


  # ===== Usage
  # This query will automatically include `WHERE deleted = False`
  active_users = User.query.all()
#+end_src
* Error Handling:
** lets learn how to handle errors [[https://www.digitalocean.com/community/tutorials/how-to-handle-errors-in-a-flask-application][here]]
** [[https://docs.python.org/3/library/exceptions.html][built-in]] python exceptions
** [[https://docs.sqlalchemy.org/en/20/core/exceptions.html][SQLalchemy core]] exceptions
* Email, password resets, tokens for reset, itsdangerous, CSRF
** The minimum required to send email, (after setting app password, instead of using your email pass):
#+begin_src python

  # ========== config, either app.config[] or app.config.from_object(Config)
  MAIL_SERVER = 'smtp.mail.yahoo.com'  # e.g., 'smtp.gmail.com'
  MAIL_PORT = 587  # or 465 for SSL
  MAIL_USE_TLS = True  # Set to False if using SSL (port 465)
  MAIL_USE_SSL = False  # Set to True if using SSL (port 465)
  MAIL_USERNAME = 'wan_ahmad_ardie@yahoo.com'
  MAIL_PASSWORD = 'rppfxeiuwqrxjilk'
  MAIL_DEFAULT_SENDER = 'wan_ahmad_ardie@yahoo.com' # Optional default sender, not needed if we always set sender in msg body

  from flask_mail import Mail, Message

  @app.route('/send-email')
  def send_mail():
      msg = Message(
          subject="hello i just got sent from Flask",
          recipients=["wan.ardie.mejia@gmail.com"],
          body="this is a test body"
          )

      try:
          mail.send(msg)
          return redirect(url_for("main_page", whatHappened="Info: Password reset link successfully sent"))
      except Exception as e:
          return redirect(url_for("main_page", whatHappened="Error: Password reset link failed to send"))


#+end_src
** Password resets
*** TimedJSONWebSignatureSerializer is [[https://stackoverflow.com/questions/76131622/itsdangerous-security-typeerror-unsupported-operand-types-for-int-and][outdated]]  , yet some doc still shows it.
*** from itsdangerous import URLSafeTimedSerializer as Serializer: basically its time-aware secret keys, making it excellent for password resets (the other option is to use DB, which is also perfectly fine)
*** The logic needed fixing further. Something to do with an URLSafeTimedSerializer instance, not converting string to integer automatically for max_age attribute. (Note below the int()).
#+begin_src python

  token = s.dumps({'some_id': current_user.mcfId}, salt="reset_pass")
  some_id = s.loads(token, salt="reset_pass", max_age=int(app.config["TOKEN_MAX_AGE"]))['some_id']

#+end_src
** Common errors:
*** If CSRF tokens are still missing, the g (app context) variable is still up and this might need to be set (anywhere after initializing app). Fix: we are not entirely sure
#+begin_src python

  @app.teardown_request
  def teardown_request(response_or_exc):
      db.session.remove()

  @app.teardown_appcontext
  def teardown_appcontext(response_or_exc):
      db.session.remove()

#+end_src
** ----- somethineg ----
** A good [[https://stackoverflow.com/questions/72092485/the-csrf-session-token-is-missing-when-csrf-token-is-present-in-request][link]] for CSRF basics, but its stackoverflow
*** why does CSRF [[https://stackoverflow.com/questions/21501058/form-validation-fails-due-missing-csrf][fail]]
* Cloud service:
** Render, to make logging work we need these:
#+begin_src python


  from logging.config import dictConfig

    dictConfig({
        "version": 1,
        "formatters": {
            "default": {
                "format": "[%(asctime)s] %(levelname)s in %(module)s: %(message)s",
            }
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "stream": "ext://sys.stdout", # Or ext://sys.stderr
                "formatter": "default",
            }
        },
        "root": {"level": "INFO", "handlers": ["console"]}, # Set root level to INFO
    })

    app.logger.setLevel(logging.DEBUG) # Or DEBUG more verbose than INFO

#+end_src
** [[https://flask.palletsprojects.com/en/stable/tutorial/deploy/][flask deployment basic notes]] and its associated [[https://flask.palletsprojects.com/en/stable/deploying/][concepts]]
* Flask projects
* Django
* app configs, server configs, tips, tricks and hacks, deployment
** General important read on [[https://docs.gunicorn.org/en/stable/settings.html][gunicorn exhaustive settings]]
** gunicorn command:
#+begin_src python

  gunicorn -b 0.0.0.0:9000 'wsgi:app' -t 300 --keep-alive 300
  gunicorn -b 0.0.0.0:9000 'wsgi:app' -t 30 --keep-alive 3
  gunicorn --workers=3 -b 0.0.0.0:54284 'wsgi:app' -t 30 --keep-alive 3  --max-requests 1200 --preload
  gunicorn --workers=3 -b 0.0.0.0:10000 -t 30 --keep-alive 120  --max-requests 1200 'wsgi:app'
  

#+end_src
*** from Render:
#+begin_quote

HI there, I would recommend you don't randomise the port. You can set it, but if it's not set, we will default it to it 10000. Using -b 0.0.0.0:10000 It would be what it defaults to if you don't use the -b option.
I'm not a regular user of Gunicorn, but I seem to recall that at some stage the positioning of the parameters mattered. I don't know if this is the case now. I would probably recommend you put your app entry point last, so I would do the command as gunicorn --workers 3 -b 0.0.0.0:10000 -t 30 --keep-alive 30 --max-requests 1200 wsgi:app.
A couple of other notes:

    The worker timeout defaults to 30 seconds, so -t 30 isn't needed.
    We would recommend setting keep-alives to 120 seconds.

#+end_quote
*** from Render:
#+begin_quote

https://community.render.com/t/optimizing-gunicorn/2068

gunicorn --worker-tmp-dir /dev/shm --workers=2 --threads=4 --worker-class=gthread --log-file=- <application_path>

#+end_quote
*** from Render
#+begin_quote

Render has a 100-minute timeout. The timeout here is the Gunicorn worker timeout, and using -t / --timeout sets this to a specific value. The default is 30 seconds.
Some users set it at 60 or higher

#+end_quote
** waitress:
*** [[https://blog.etianen.com/][dont user gunicorn]]
*** [[https://flask.palletsprojects.com/en/stable/deploying/waitress/][waitress docs]]
*** [[https://flask.palletsprojects.com/en/stable/deploying/waitress/][deploying with waitress]]
**** Dont use --host, to avoid running as root. INFO: root requires port 80 or 443
*** [[https://docs.pylonsproject.org/projects/waitress/en/stable/runner.html][waitress-serve arguments]]
#+begin_quote



#+end_quote
*** 
** [[https://docs.gunicorn.org/en/stable/settings.html#limit-request-line][Stop DDOS]]
** Common render deploy issues:
*** https://community.render.com/t/gunicorn-port-is-bound-but-deploy-is-failing-to-detect-port-python-fast-api/33846
*** https://devcenter.heroku.com/articles/python-gunicorn
** [[https://www.digitalocean.com/community/tutorials/how-to-deploy-python-wsgi-apps-using-gunicorn-http-server-behind-nginx][Why]] you should try to deploy gunicorn (app server) behind a "real server" like ngix
*** This same [[https://www.digitalocean.com/community/tutorials/a-comparison-of-web-servers-for-python-based-web-applications][link]] from DigitalOcean justifies why
** Keepalive:
*** (Read about werkzeug below) The trick is to [[https://stackoverflow.com/questions/10523879/how-to-make-flask-keep-ajax-http-connection-alive][set HTTP protocol version]] to 1.1
*** [[https://github.com/KangersHub/python-flask-example-keepalive][alternative]]
*** Look at [[https://stackoverflow.com/questions/24130305/postgres-ssl-syscall-error-eof-detected-with-python-and-psycopg][this]], if the error is
#+begin_quote

(psycopg2.OperationalError) SSL SYSCALL error: EOF detected 

#+end_quote
* Arrange 
** https://www.codersjungle.com/2024/07/09/handling-http-methods-in-flask-get-and-post-requests/
** https://frankvalcarcel.com/blog/conveniently-storing-lists-in-database/
** When exporting data from Database to excel, we can do this:
#+begin_src python

  query = sa.select(Member)
  ms = db.session.scalars(query).all()
  download_data = pd.read_sql(query,db.session.connection())

  byte_object = BytesIO()
  download_data.to_excel(byte_object, index=False)
  byte_object.seek(0)

  return send_file(byte_object, 
                   download_name="hello.xlsx", as_attachment=True)


#+end_src
*** Our code above is inspired by examples like this [[https://www.geeksforgeeks.org/uploading-and-downloading-files-in-flask/][uploading and downloading file]] online, and treat the BytesIO like a file object itself, before passing to send_file. Heres another [[https://stackoverflow.com/questions/67894605/downloading-a-file-in-downloads-directory-flask-python][one]]. We also need to make sure we pull seek back to 0 since its an Byte object like in this [[https://stackoverflow.com/questions/68568527/create-excel-file-from-dataframe-and-allow-download-in-flask-error-file-format][example]]
*** send_file is the proper Flask way to deal with downlaods
*** we havent experimented with finer control possible with more advanced Pandas Dataframe [[https://medium.com/@alice.yang_10652/python-how-to-export-data-from-database-to-excel-step-by-step-guide-9cf6ea476abe][tricks]]. It might help if someone wants to exports to a single sheet
*** we can also use the mysterious [[https://stackoverflow.com/questions/18977387/how-to-export-sql-server-result-to-excel-in-python][cursor]] object when writing to Excel, cursors are lower level elements of db sessions. They are how Python executes PostgreSQL command in a database session. 
*** This [[https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html][page]] from the official Pandas documentation shows at the bottom an example of writing to several sheets of a single file. We can truy seduce Terry with this. But that might be overkill. 
* Node, NPM:
** NPM is just the online repository of Javascript modules. Installing Node comes with npm command, which is used to interact with this repo
** 
* Educational
** [[https://werkzeug.palletsprojects.com/en/stable/][werkzeug]] is a WSGI web application library. This is what lies underneath Flask 
** 
