* Day 80:
** added validation for my badass worklflow
** attempting to do my folding stool, discovered a loop
*** prepared tools, and material
*** started minor work
*** get tired, need minor project to stay motivated,
*** also minor project while all tools are out and messy
** We finally created proper UI for CSV.
*** https://medium.com/@ryan_forrester_/reading-csv-files-in-c-how-to-guide-35030eb378ad
*** We planned on separating the Upload File part from the Upload To DB part. This means Upload File part will have validations and checks and good feedback
*** Turns out uploading CSV's its own science and art.
*** We discover ranged loops, we are sticking to the immutable version, like this:
#+begin_src c++

    for(const auto& a_row : full_csv){
  // ==================================================    
    }

#+end_src
*** We discovered std::string appends are not the best (well, we got bugs), but also, we use overloaded + anyway, because appends modify by default (and return this*), but + dont do anything special, and just returns a new modified string
*** 
* Day 81:
** Played Chopin, recorded absolutely magnificent interpretation of Chopin Nocturne Op62.
** Best supportive Reddit comment
#+begin_quote

Wow this is such a radical interpretation, you’re about to move the whole classical world (and piss off some snobs) with such novelty and creativity. Anyone who says otherwise is just dismissive of your obvious genius.


I piss off on a small scale locally here, the conservatory and institution level, not worth it. Too much trouble and power dynamics.


I agree! But still if someday you change your mind, you’d do something great for humanity!


#+end_quote
* Day 82:
** tried a bit of Common Lisp 
** a Reddit comment somewhere said that we should habitualize using REPL, not running functions from file
** always run rlwrap before sbcl
** ASDF is a build system, but quicklisp manages external dependencies between Lisp systems
** 
* Day 83:
** there is no confusion between header declaration and the usage in .cpp. But we cant get our head around placement of & or *
#+begin_src c++

void UserCsvWidget::getFile__QStringList(QStringList& files){}

#+end_src
** we REALLY need to read the history of creation of & and *
** QStringList 
*** https://forum.qt.io/topic/143408/how-to-pass-and-simply-iterate-c-c
** in modern C++, the recommended alternatives to using raw pointers and explicit new/delete are standard library containers and smart pointers.
* Day 84:
** we mostly learnt Rust (advent of code) and did woodworking. We only planed wood for our folding stool. Not much progress
* Day 85:
** Discovered that we can define QList from std::initializer_list, and define QStringList from QList
** We can also define QStringList straight from curly brackets 
** Some examples:
#+begin_src c++

  QList<QString> testlist = {"1", ":2014"};

  QStringList testlist_better(testlist);

  // or we can do this

  QStringList fonts = { "Arial", "Helvetica", "Times" };

  // probably more

  

#+end_src
* Day 86:
** We only read Rust code so far.
** We attempted some basic file reading, but went nothing beyond that.
** We decided to stop for a while and just Rust docs, coz its worth especially our encountering of strange symbols (pipe, ?question mark)
** We finished planing a piece of wood, but that took literally 3 hours, when including rest and cleaning
* Day 87:
** We discovered that C++ compiler will actually STOP us from repeating definition of our parseCSVRow() function.
** We discovered that we only needed to add namespace, and we define it and use it exactly the same way (only difference: MyParser::)
** Theres boilerplate code for this. The usual header guards, but most important is the namespace
#+begin_src c++

  // we couldnt make it work without the namespace, but regardless, namespace is good practice
  namespace MyParser
  {
    std::vector<std::string> parseCSVRow(const std::string& row);
  }

#+end_src
** The rest is exactly the same
** Remember: One Definition Rule
* Day 88:
** We successfully ran a vecto function that successfully outputs to a png file
** We still havent done anything of significance with Common Lisp
* Day 89:
** We are struggling to learn Common Lips Recipes, but, things are looking up becoz we discovered Lisp is a very cool lang, with a history of GUI way ahead of its time. And other stuff we learnt
** common lisp
*** the symbol has its own properties like an object, even its own lifespan separate from the function or value it defines
*** this is very different from other traditional langs, where the "variables name/label/whateer" is the same as the function, so all are like the "same object" with a single lifespan
* Day 90:
** we fixed our sly keybindings, which still feels like magic by itself
* Day 91:
** We learnt about in-place modification, and its a topic too in C++. Is it worth it? And does it really improve performance by that much?
** there's a cool library called "algorithm" in cpp
* Day 92:
** We learnt QSqlQuery select from this one link, [[https://forum.qt.io/topic/71381/qsqlquery-select/3][qsqlquery select]]
** 
* Day 93:
** apart from evaluation, we attempted the same for our sql operation
** we realized, its not 1-to-1, coz SQL works by a search
** this means, we cant really do a function that "cleans a string before comparison"
** we are beginning to notice a pattern
** when we do search and comparison type operations between user interaction and DB, there needs to be a set rule or standard, for comparison, such as "always store as number" for a field, or "always a space before text" (spaces between are ignored by SQL usually)
* Day 94:
** we watched the Lisp video on constructing a list with conses
** we did the same with (list) and backquotes
** theres an important distinction, such as with (list we need ' to stop evaluating an uncreated name example: )
  #+begin_src emacs-lisp

    (list 'a 'b 'c)

    ;; instead of

    '( a b c)

#+end_src
** putting our "engineering is also history" cap on, this means '() is a short form
* Day 95:
** In order to indexOf("<some-field-name>") to work, we need a valid record. exec() simply prepares i guess, but first() or next() finally returns a valid record. (we spent too much time doing this)
** This seems counter-intuitive, it just means we dont know whats the purpose of exec()
#+begin_src c++

  if(query_getDepartmentId.exec()) {
    int fieldIndex = query_getDepartmentId.record().indexOf("id");
    qDebug() << "fieldIndex is -1 here" << fieldIndex;
    qDebug() << "isvalid is False here" << query_getDepartmentId.isValid();
    if(query_getDepartmentId.first()){	
      int fieldIndex = query_getDepartmentId.record().indexOf("id");
      qDebug() << "fieldIndex is a proper number here" << fieldIndex;
      qDebug() << "isvalid is True here" << query_getDepartmentId.isValid();
      QString someValue = query_getDepartmentId.value(0).toString();
    }
  }

#+end_src
* Day 96:
** what do we do today (coz we might accidentally delete this):
- we need to read this link: https://www.amyschlesener.com/posts/2020/04/increasing-ubuntu-partition/
- according to most, increasing partition is easy, but not shrinking
- install baobab for Hanifa's laptop, setup a .desktop file
- there's no God and there's no free will
- we need to learn some QML concept
  - https://doc.qt.io/archives/qt-5.15/qtquick-modelviewsdata-modelview.html
  - https://doc.qt.io/qt-6/qtqml-cppintegration-contextproperties.html
  - https://doc.qt.io/qt-6/qqmlcontext.html
  - https://forum.qt.io/topic/76162/how-to-write-in-a-text-label-made-in-qml/5
  - https://doc.qt.io/qt-6/qml-qtquick-mousearea.html
  - https://doc.qt.io/qt-6/qtqml-syntax-signals.html
  - to really get, which is not recommended, but we are a badass, so we will do it anyway. objectName is visible to the C++ meta-object system
    #+begin_src qml

      // MyItem.qml
      import QtQuick

      Item {
          Rectangle {
              objectName: "myTargetRect"
              width: 100; height: 100
              color: "blue"
          }
      }

      
    #+end_src
  - the main.cpp
#+begin_src c++

  // main.cpp
  #include <QQmlApplicationEngine>
  #include <QQuickItem>

  QQmlApplicationEngine engine;
  engine.load(QUrl("main.qml"));

  // 1. Get the root object (the Window or top-level Item)
  QObject *rootObject = engine.rootObjects().first();

  // 2. Search for the child by objectName
  QObject *rect = rootObject->findChild<QObject*>("myTargetRect");
  if (rect) {
      // 3. Cast to the specific type if needed (e.g., QQuickItem)
      QQuickItem *item = qobject_cast<QQuickItem*>(rect);
      item->setProperty("color", "red");
  }

#+end_src
  - the best advice is actually this: [[https://doc.qt.io/qt-6/qtqml-cppintegration-interactqmlfromcpp.html]["All QML methods are exposed to the meta-object system"]]
* Day 97:
** Tried cmake for the first time. The most important part of the CMakeLists.txt is acually target_link_libraries(hello PRIVATE Qt::Core Qt5::Widgets) and the Core and Widgets using find_package() is not enough
** 
* Day 98:
** we figured out how to org-notify in the simplest way possible, in short:
#+begin_quote

systemctl start --user dunst

#+end_quote
** And example eLisp:
#+begin_src emacs-lisp

  (defun ardie/bien-biel-que-el-paso-paso()
    (interactive)
    (print "bien bien peuded que si, puede que no")
    )

  (run-with-timer 2 10 'ardie/bien-biel-que-el-paso-paso)

#+end_src
