* Day 80:
** added validation for my badass worklflow
** attempting to do my folding stool, discovered a loop
*** prepared tools, and material
*** started minor work
*** get tired, need minor project to stay motivated,
*** also minor project while all tools are out and messy
** We finally created proper UI for CSV.
*** https://medium.com/@ryan_forrester_/reading-csv-files-in-c-how-to-guide-35030eb378ad
*** We planned on separating the Upload File part from the Upload To DB part. This means Upload File part will have validations and checks and good feedback
*** Turns out uploading CSV's its own science and art.
*** We discover ranged loops, we are sticking to the immutable version, like this:
#+begin_src c++

    for(const auto& a_row : full_csv){
  // ==================================================    
    }

#+end_src
*** We discovered std::string appends are not the best (well, we got bugs), but also, we use overloaded + anyway, because appends modify by default (and return this*), but + dont do anything special, and just returns a new modified string
*** 
* Day 81:
** Played Chopin, recorded absolutely magnificent interpretation of Chopin Nocturne Op62.
** Best supportive Reddit comment
#+begin_quote

Wow this is such a radical interpretation, you’re about to move the whole classical world (and piss off some snobs) with such novelty and creativity. Anyone who says otherwise is just dismissive of your obvious genius.


I piss off on a small scale locally here, the conservatory and institution level, not worth it. Too much trouble and power dynamics.


I agree! But still if someday you change your mind, you’d do something great for humanity!


#+end_quote
* Day 82:
** tried a bit of Common Lisp 
** a Reddit comment somewhere said that we should habitualize using REPL, not running functions from file
** always run rlwrap before sbcl
** ASDF is a build system, but quicklisp manages external dependencies between Lisp systems
** 
* Day 83:
** there is no confusion between header declaration and the usage in .cpp. But we cant get our head around placement of & or *
#+begin_src c++

void UserCsvWidget::getFile__QStringList(QStringList& files){}

#+end_src
** we REALLY need to read the history of creation of & and *
** QStringList 
*** https://forum.qt.io/topic/143408/how-to-pass-and-simply-iterate-c-c
** in modern C++, the recommended alternatives to using raw pointers and explicit new/delete are standard library containers and smart pointers.
* Day 84:
** we mostly learnt Rust (advent of code) and did woodworking. We only planed wood for our folding stool. Not much progress
* Day 85:
** Discovered that we can define QList from std::initializer_list, and define QStringList from QList
** We can also define QStringList straight from curly brackets 
** Some examples:
#+begin_src c++

  QList<QString> testlist = {"1", ":2014"};

  QStringList testlist_better(testlist);

  // or we can do this

  QStringList fonts = { "Arial", "Helvetica", "Times" };

  // probably more

  

#+end_src
* Day 86:
** We only read Rust code so far.
** We attempted some basic file reading, but went nothing beyond that.
** We decided to stop for a while and just Rust docs, coz its worth especially our encountering of strange symbols (pipe, ?question mark)
** We finished planing a piece of wood, but that took literally 3 hours, when including rest and cleaning
* Day 87:
** We discovered that C++ compiler will actually STOP us from repeating definition of our parseCSVRow() function.
** We discovered that we only needed to add namespace, and we define it and use it exactly the same way (only difference: MyParser::)
** Theres boilerplate code for this. The usual header guards, but most important is the namespace
#+begin_src c++

  // we couldnt make it work without the namespace, but regardless, namespace is good practice
  namespace MyParser
  {
    std::vector<std::string> parseCSVRow(const std::string& row);
  }

#+end_src
** The rest is exactly the same
** Remember: One Definition Rule
* Day 88:
** We successfully ran a vecto function that successfully outputs to a png file
** We still havent done anything of significance with Common Lisp
* Day 89:
** We are struggling to learn Common Lips Recipes, but, things are looking up becoz we discovered Lisp is a very cool lang, with a history of GUI way ahead of its time. And other stuff we learnt
** common lisp
*** the symbol has its own properties like an object, even its own lifespan separate from the function or value it defines
*** this is very different from other traditional langs, where the "variables name/label/whateer" is the same as the function, so all are like the "same object" with a single lifespan
* Day 90:
** we fixed our sly keybindings, which still feels like magic by itself
* Day 91:
** We learnt about in-place modification, and its a topic too in C++. Is it worth it? And does it really improve performance by that much?
** there's a cool library called "algorithm" in cpp
* Day 92:
** We learnt QSqlQuery select from this one link, [[https://forum.qt.io/topic/71381/qsqlquery-select/3][qsqlquery select]]
** 
* Day 93:
** apart from evaluation, we attempted the same for our sql operation
** we realized, its not 1-to-1, coz SQL works by a search
** this means, we cant really do a function that "cleans a string before comparison"
** we are beginning to notice a pattern
** when we do search and comparison type operations between user interaction and DB, there needs to be a set rule or standard, for comparison, such as "always store as number" for a field, or "always a space before text" (spaces between are ignored by SQL usually)
* Day 94:
** we watched the Lisp video on constructing a list with conses
** we did the same with (list) and backquotes
** theres an important distinction, such as with (list we need ' to stop evaluating an uncreated name example: )
  #+begin_src emacs-lisp

    (list 'a 'b 'c)

    ;; instead of

    '( a b c)

#+end_src
** putting our "engineering is also history" cap on, this means '() is a short form
* Day 95:
** In order to indexOf("<some-field-name>") to work, we need a valid record. exec() simply prepares i guess, but first() or next() finally returns a valid record. (we spent too much time doing this)
** This seems counter-intuitive, it just means we dont know whats the purpose of exec()
#+begin_src c++

  if(query_getDepartmentId.exec()) {
    int fieldIndex = query_getDepartmentId.record().indexOf("id");
    qDebug() << "fieldIndex is -1 here" << fieldIndex;
    qDebug() << "isvalid is False here" << query_getDepartmentId.isValid();
    if(query_getDepartmentId.first()){	
      int fieldIndex = query_getDepartmentId.record().indexOf("id");
      qDebug() << "fieldIndex is a proper number here" << fieldIndex;
      qDebug() << "isvalid is True here" << query_getDepartmentId.isValid();
      QString someValue = query_getDepartmentId.value(0).toString();
    }
  }

#+end_src
* Day 96:
** what do we do today (coz we might accidentally delete this):
- we need to read this link: https://www.amyschlesener.com/posts/2020/04/increasing-ubuntu-partition/
- according to most, increasing partition is easy, but not shrinking
- install baobab for Hanifa's laptop, setup a .desktop file
- there's no God and there's no free will
- we need to learn some QML concept
  - https://doc.qt.io/archives/qt-5.15/qtquick-modelviewsdata-modelview.html
  - https://doc.qt.io/qt-6/qtqml-cppintegration-contextproperties.html
  - https://doc.qt.io/qt-6/qqmlcontext.html
  - https://forum.qt.io/topic/76162/how-to-write-in-a-text-label-made-in-qml/5
  - https://doc.qt.io/qt-6/qml-qtquick-mousearea.html
  - https://doc.qt.io/qt-6/qtqml-syntax-signals.html
  - to really get, which is not recommended, but we are a badass, so we will do it anyway. objectName is visible to the C++ meta-object system
    #+begin_src qml

      // MyItem.qml
      import QtQuick

      Item {
          Rectangle {
              objectName: "myTargetRect"
              width: 100; height: 100
              color: "blue"
          }
      }

      
    #+end_src
  - the main.cpp
#+begin_src c++

  // main.cpp
  #include <QQmlApplicationEngine>
  #include <QQuickItem>

  QQmlApplicationEngine engine;
  engine.load(QUrl("main.qml"));

  // 1. Get the root object (the Window or top-level Item)
  QObject *rootObject = engine.rootObjects().first();

  // 2. Search for the child by objectName
  QObject *rect = rootObject->findChild<QObject*>("myTargetRect");
  if (rect) {
      // 3. Cast to the specific type if needed (e.g., QQuickItem)
      QQuickItem *item = qobject_cast<QQuickItem*>(rect);
      item->setProperty("color", "red");
  }

#+end_src
  - the best advice is actually this: [[https://doc.qt.io/qt-6/qtqml-cppintegration-interactqmlfromcpp.html]["All QML methods are exposed to the meta-object system"]]
* Day 97:
** Tried cmake for the first time. The most important part of the CMakeLists.txt is acually target_link_libraries(hello PRIVATE Qt::Core Qt5::Widgets) and the Core and Widgets using find_package() is not enough
** 
* Day 98:
** we figured out how to org-notify in the simplest way possible, in short:
#+begin_quote

systemctl start --user dunst

#+end_quote
** And example eLisp:
#+begin_src emacs-lisp

  (defun ardie/bien-biel-que-el-paso-paso()
    (interactive)
    (print "bien bien peuded que si, puede que no")
    )

  (run-with-timer 2 10 'ardie/bien-biel-que-el-paso-paso)

#+end_src
* Day 99:
** based on our understanding of rvalue, lvalue and valid expressions like dest+3 or \*(dest+5), (as opposed to &(dest+5)) we can do something like this to change 3rd and 5th character
#+begin_src c

  char *call_me(char *dest, char *src){

      char *temp = dest+3;
      ,*temp = 'a' ;
      if(*(dest+5) == 'y'){
          char *temp2 = dest+5;
          ,*temp2 = '_' ;
      }

      return dest;
  }

  int main(void){
      char src[] = "hello";
      char dest[] = "goodbye";
      call_me(dest,src);
      printf("%s", dest);
      return 0;
  }

#+end_src
* Day 100:
** 
#+begin_quote

the steps in general looks like this, but we SHOULD REALLY try static linking, we havent tried it yet
- 

  we first create an object file. SAME with static, but we Position Independent Code

  gcc -c -fPIC mysource.c -o mysource.o

  we then create a static library using archiver. The archiver is a tool that can create input for the linker (think, linker was developed separate from compiler, and the logic behind it is almost completely different. Maybe its a separate paradigm/tool?)

  we can now link it

  gcc -o -shared mysource.so mysource.o

    this will not work

  gcc main.c -L. -lmylib

  this will work

  gcc main .c -L/home/ardie/location-of-library -Wl,-rpath=/home/ardie/location-... -o result mylib.c -lmylib

  Note how the -L is basically telling thje compiler to pass the options to the linker instead.

  mylib is some name coming from mylib.c and mylib.h, but the naming is convention, the true naming, im guessing, comes from #define MYLIB_H in the header file.

  so what does header file do in this case?

  anyway 

#+end_quote
** some links:
*** https://www.cprogramming.com/tutorial/shared-libraries-linux-gcc.html
*** https://www.geeksforgeeks.org/c/how-do-i-create-a-library-in-c/
*** Note how the the secind link uses 2 methof static and dynamic, and static doesnt work, but we SHOULD REALLY try..x
* Day 101
** Our Piscine is finished. What did we learnt so far:
*** we learnt that making an Emacs exam config, and writing it from the beginning was definitely worth it.
*** we learnt we have trouble separating life in shallow Sunway Uni, from reality of a brown man surviving in SEAsia.
*** we learnt that it was actually not that difficult or that destructive to modify most navigation keys to something radical (as long as its not Ctrl-M, that messes <return> coz Emacs does that to Ctrl-M)
*** we learnt that we still cant communicate our hatred of leetcode and corpo environment to the general public.
*** we learnt that I get nervous, and I still need help practicing talking to people
*** I learnt that I can do decent stuff in C.
*** I learnt much more badass stuff in C, as long as I take the time to learn and absorb
* Day 102
** 1st attempt at installing opengl, just to draw a bloody triangle
** downloading frmo nigel's github, only make (not cmake) works, (must build inside /auto). Why are they downloading stuff called "registry's"
** stuff like OpenGL-Registry, EGL-Registry, only then creating glew.h
** glew.h apparently is so important
** read this??:
*** https://stackoverflow.com/questions/12122631/difference-between-opengl-files-glew-h-and-gl-h-glu-h
* Day 103:
** Finally:
#+begin_quote

everything in programming is mostly history and linguistics than math, remember.


static-linking used to be common. Linux made it weird, and shamed people for statically linking, shared/dynamic linking is apparently better, even though memory is getting cheap.

Dynamically linking = runtime-ish

First some basics:
-I is for the compiler. Include files. Since includes are usually definitions, remember -> you cant have 1 (I)without the other (L). More or less. But usually gcc looks for libs by itself anyway.
-L is for the linker, and tells the location of library (directory)
-l is for the linker, and tells which library to use (file)

But -l comes with convention (yuck). -lhelper means look for libhelper.a or libhelper.so



Since, programming is history too, and dynamical linking came later. The gcc sometimes need more information.

remember dynamical linked means at runtime (saving space thingy), and -L only helps at compile/linking time. So you would still usually need LD_LIBRARY_PATH sometimes.

#+end_quote
** to read on [[https://www.reddit.com/r/opengl/comments/sskqmu/how_do_i_link_glfw_to_my_cc_program_in_linux/][reddit]]
*** apparently, you can use something like pkg-config, which is also a compiler-adjacent tool
** for using nm with shared object, dynamically linked stuff, you can use the -D option (nm -D)
* Day 104:
** what we're learning right now: https://learnopengl.com/Getting-started/Hello-Window 
* Day 105:
** C macros might pollute namespace (???)
** Notice how we create a "destructive-malloc-struct-creation" for our Person. Note how verbose it is. they keyword "struct" is everywhere, which is apparently a good thing
#+begin_src c

    struct Person * createNewStruct(){
      struct Person * sarah = (struct Person*)malloc(sizeof(struct Person));
      return sarah;
  }

  /* of course we can always start off with something simple, if we get lost */

  int* createNewStruct(){
      int *what = (int *)malloc(sizeof(int) * 5);
      return what;
  }

#+end_src
* Day 106:
** gcc actually looks at the NAME when running with the -l<some-random-lib> (example: -lmylib)
** GLAD and GLEW does the same exact thing. Dont include both (except for special reasons): [[https://community.khronos.org/t/problems-with-glad-and-glew-libraries/109452/5][khronos: GLAD and GLEW does the same thing]]
** we generate a GLAD header from this link: [[https://gen.glad.sh/][GLAD]]
** theres a Github example: https://github.com/dav1dde/glad
** for the includes, you must always put glad before the glfw3 headers ([[https://community.khronos.org/t/help-with-setting-up-glfw-with-glad/107258][glad before glfw3]])
** a very COOL link explainig what the true spirit of LD_LIBRARY_PATH, and some tips around, such as using env (rather than the export), or using a wrapper bash script. [[https://www.hpc.dtu.dk/?page_id=1180][hpc on ld_library_path]]
** We live in a small world, better have fun, being a badass at GCC flags?? [[https://blog.httrack.com/blog/2014/03/09/what-are-your-gcc-flags/][httrack blog on GCC flags]]
** 
* Day 107:
** this link makes much more sense:x
*** [[https://www.steinwurf.com/blog/error-while-loading-shared-libraries][steinwurf: on thinking through loading our shared library]]
** Thinking through:
#+begin_src shell

   gcc -fPIC -c readme.c # c: Creating object file, fPIC: position-independent-code

   gcc -shared -o readme.so readme.o # o: output file, -shared: create shared object


   # ----- and finally

   sudo ldconfig /home/ardie/my-personal-libs/shared-objects/

   # ----- note the the full file name is required, yes, this seems like OS-level stuff
   # ----- turns out you dont need LD_LIBRARY_CONFIG

#+end_src
** Useful to know, and to understand.
#+begin_src shell

  ldconfig -p | grep <some-lib-we-looking-for>

  # we know this
  sudo ldconfig /some/path/

  # lets look at the symbols, actually, nm is the dumber of the lot
  nm -D gl_ardie.so

  # more relevant for this task
  readelf -d /home/ardie/my-personal-libs/shared-objects/test.so | grep SONAME

  # seems similar t readelf, but looks better and more info, objdump can also do the same like nm using -D
  objdump -p libcurl.so.3.0.0 | grep SONAME

  # sometimes, grepping through the header files is much better

  cat /path/to/glad/gl.h | grep glad_glEvalMesh2


#+end_src
* Day 108:
** the process of compilation seems rather ugly, even though -l<some-lib-name> "seems" rather elegant, it feels very OS-ish, it seems like something the programmer should never touch, because you are dealing with ldconfig, which updates some cache that seems to be used SYSTEM-wide.
** doesnt feel right AT ALL
** actually, you can just use the full file name of the .so (shared object), but it quicly becomes super-long
** why does nobody say how weird this feels
** 
* Day 109:
** it took us to watch Casey's video, to understand how GLFW actually stores window specific stuff, becoz we thought the separation was arbitrary. 
** It actually makes sense, when you consider that, that openGL is a "specification", which actually means: God knows what your platform is doing, do you plan on using 2 windows, does your platform even have a concept of windows. So, this POV makes more sense
** 
* Day 110:
** How IDs Work in OpenGL
*** Generate - request 1 or more IDs, using glGenBuffers or glGeArrayVertex
*** Bind - "activate" by binding ID to specific target (Eg: GL_ARRAY_BUFFER)
*** Configure - now you can configure
* Day 111:
** In the normal way of doing things, "window" is directly tired to "context". And working with buffers outside of context, produces "core dumped"
#+begin_src c++
  
  glfwInit();

  GLFWwindow* window2 = glfwCreateWindow(800, 600, "LearnOpenGL", NULL, NULL);
  glfwMakeContextCurrent(window);

  GLuint VertexArrayID;
  printf("%d", VertexArrayID);

  GLuint myBufferID = 0;
  // ===== if we put these after glfwTerminate, it'll "core dump"
  glGenBuffers(1,&myBufferID); //
  glBindBuffer(GL_ARRAY_BUFFER,myBufferID); //


  glfwTerminate();

#+end_src
* Day 112:
** Opportunity for teaching!!:
** This example is actually way to teaching reading other files in other formats.
** Also an argument for putting EVERYTHING inside 1 file.
** Yes, thats how its always been. "everything in 1 file rules all":
#+begin_src c++

  #include<iostream>
#include<glad/glad.h>
#include<GLFW/glfw3.h>

// Vertex Shader source code
const char* vertexShaderSource = "#version 330 core\n"
"layout (location = 0) in vec3 aPos;\n"
"void main()\n"
"{\n"
"   gl_Position = vec4(aPos.x, aPos.y, aPos.z, 1.0);\n"
"}\0";
//Fragment Shader source code
const char* fragmentShaderSource = "#version 330 core\n"
"out vec4 FragColor;\n"
"void main()\n"
"{\n"
"   FragColor = vec4(0.8f, 0.3f, 0.02f, 1.0f);\n"
"}\n\0";


#+end_src
** Original file example here (Victor Gordon): [[https://github.com/VictorGordan/opengl-tutorials/blob/main/YoutubeOpenGL%202%20-%20Triangle/Main.cpp][main cpp]]
* Day 113:
** we still dont understaand how vertex
  attributePointer() works.
** Complete mystery, when we attempted to draw 2 triangles (obviously doesnt work, coz apparently, we're NOT ALLOWED to do that). VertexAttribPointer will attempt to create non-sensical coordinates, when you put more than the "size"
  #+begin_src c++

    // this will work
    glVertexAttribPointer(0,3, GL_FLOAT, GL_FALSE, 0, 0);

    // this will NOT work
    glVertexAttribPointer(0,6, GL_FLOAT, GL_FALSE, 0, 0);

#+end_src
* Day 114:
** So again:
#+begin_quote

GenBuffer()
BindBuffer()
BufferData()

Before that, we need to create shaders (which are ACTUAL OBJECTS) and link it to the program.

We then need to use VertexAttribPointer, which is the ever confusing, WTF is this?? What does it do behind the scenes? Theres also the confusing bit where we CAN create another VBO, and turn it on - GenBuffers() - BindBuffers() - VertexAttribPointer() EnableVertexAttribPointer()

#+end_quote
* Day 115:
** C is so hacky, you can literally use header files (.h) as a "transform to cpp file, if we define MACRO" file
** Basically it goes something like this:
*** #define your header file first, then #include your header
*** put something meaningful inside #ifdef MYFILE_H (instead of #ifndef)
*** now watch the magic of header files, becoming like .cpp files 
* Day 116:
** despite our accidental ardie/back-to-square-one, (which cancels ALL our work), in the end, its just the "working area", so we only cancled our workong area, our main didnt need fixing (LOL). my workflow WORKS YET again. (mostly becoz becoz Emacs still remembers our edits)
** misnomer:
*** Uniform's are literally passed from CPU to GPU
*** but that is jsut the mechanic, what really matters, is that the GPU is just secondary to the whole operation.
*** Even though the entire pipeline is "important", data is passed to the GPU "imperatively". So uniforms, are "injecting data from your code to the pipeline of a single object"
*** super important link: https://thebookofshaders.com/glossary/?search=mix
*** just like in Photoshop, we must think what matters to most designers. We ask questons like "does shading matter?", in the case of Photoshop, only for text effects. whats powerful, is probably a way to use math. But again, as Blow says, programming isnt math, math is perfect and "a box", programming has a lot of "imperative injection into your perfect model"
* Day 117:
** [[https://thebookofshaders.com/glossary/?search=mix][Great link, but be careful with examples:]]
*** The 2nd example, while interesting showcase of smoothstep, is hardly practical, and is just a fancy way of showing "how to plot a line using smoothstep()"
*** Reminder: our previous example of using sin() to generate ratio cycles based on a linear input, is much more useful
*** smoothstep is the only step, and the way to implement linearstep is writing oneself
*** this implies that its a relatively common operation, looking at how ALL these functions are used might prove useful (even if its looks weird at first)
*** now that we have some familiarity of what GLSL and shaders code look like (2 types of shaders at least), and how they feed code into each other. We should REALLY read about Graphics History. Some interest includes "what is z-buffer". We downloaded the file as History-of-graphics.pdf. But heres the link:
**** https://graphics.stanford.edu/courses/cs248-01/History-of-graphics/History-of-graphics.pdf
*** thats it!1
* Day 118
** [[https://developer.samsung.com/galaxy-gamedev/resources/articles/gpu-framebuffer.html][I hate samsung, but now we need to learn this, quite cool, make sure to rewrite this]]
* Day 119 (Get ready for lots of unrelated progress (so its not real progress):):
** misnomer:
- Uniform's are literally passed from CPU to GPU
- again, this results in lots of function bloat (so many APIs), becoz GPU can come in any form, this will be important for a very long time (think: Bolt Graphics)
- Data is passed to the GPU "imperatively". So uniforms, are "injecting data from your code to the pipeline of a single object"
- [[https://thebookofshaders.com/glossary/?search=mix][book of shaders]]
- uniforms are NOT constant, but are global, I think
- we finally understand how mix() works
- x*(1−a)+y*a.
- a sin wave = fluctuates = literal wave = also a wheel
- Therefore: weight can come from "positivizing" sin of "infinite linear time"
- we discovered "switches" inside a single GLSL script, so macros are not the perfect switches, but rather operate inside each pipeline (its fine, its a good way to test different GLSL in 1 file)
- framebuffer: it is not a hack, computer researchers have been using this for decades
- DirectX is more "direct". Its tightly integrated with Windows and XBOX ecosystem. Vulkan is cross-platform works well with Linux. (However, DirectX is not faster, both perform similarly)
- DirectX will be around for a very long time, as Windows is ONLY ever updating this library
Then, how does Linux handle Windows games??
- Proton/Wine: it intercepts DirectX calls, and translates them into native Vulkan instructions
** misnomer
- we finally understand big o notation
- when we look at the example, from this [[https://www.youtube.com/watch?v=XMUe3zFhM5c][YouTube video]], the example being AddUp(), it seems particular doable, and also you can apply (making your algorithm simpler), to almost any function
** misnomer
- we discovered renderdoc a cool debugging tool for graphics under linux
- Cohen and Sutherland (1974) - sorting - according to this [[https://lodev.org/cgtutor/lineclipping.html][link]], a common representation is to use ourcode (binaries of a certain look), and the benefits of outcode is that we can have "trivial accept" and "trivial reject"
** misnomer:
- lookup-table is an imperitive hack. For any function F(x), x in the table can have a range of (a,b). Obviously, you decide that x has a "finite" range
- its an optimization, but its speed depends on  frequency of function evaluation and storage
- the [[https://paroj.github.io/gltut/Texturing/Tutorial%2014.html][article]] then proceeds to talk about Gaussian Specular function (what?!?!?!),
** Raylib bubble example:
- game state as: switch() inside while()
- if offsety consistent throughout
- drawmap() function
- we need to know the full set of value range within the "map" variable (we do this in inilevel)
- by separating the temp() from map(), the temp() can be a "ratio map"
- the formular below, means, "tile is dynamically adjusted to screenwidth"
- think of it as "desire", we desire this mapWidth, that screenWidth, so the code needs to know tileWidth from this calculation
  #+begin_src c++

        tileWidth = abs((float)screenWidth/(float)mapWidth);

#+end_src
- if we know anything about games, its that its not perfect, so while loops is not a constant perfection. For example, apart from rendering not being a perfect constant inside each loop iteration, will there be moments, where character level-ups pause everything
* Day 120:
** Apparently, everytime we try to go back to our GLSL and re-try the (color across primitive, gradiented by the coordinates). We keep encountering the same BUG again caused by implicit variables imported by default. This time by gl_FragCoord.
** There should be a lesson from this, one we can generalize (I cant think of any)
* Day 121:
** we now know that using C preprocessor directives is very legit for test mechanic
** variables like gl_FragCoord are EXTREMELY problematic!! Becoz it is implicit it CAN be a source of hard to detect bugs for beginners
* Day 122:
** Once we are reading many others, we can revisit this [[https://teaching.csse.uwa.edu.au/units/CITS3003/lectures/019_texture_mapping_in_OpenGL.pdf][link]], and see wherer understanding stands
** we should also revisit link
*** https://www.nv5geospatialsoftware.com/docs/PassingInfoShader.html
** more revisiting:
*** [[https://beta.p5js.org/tutorials/intro-to-glsl/][link]]
*** [[https://research.ncl.ac.uk/game/mastersdegree/graphicsforgames/introductiontographics/IntroductionToGraphics.pdf][introduction to graphics]]
** Finally a better explanation of Sutherland clipping algo. The [[https://www.dgp.toronto.edu/~ah/csc418/fall_2000/notes/clip2d.html][link]] shows how the vertex list gets updated each time
** [[https://nils-olovsson.se/articles/heightfield_shading/][we havent read this]]
** [[https://web.eecs.umich.edu/~sugih/courses/eecs487/lectures/16-Phong+Shading.pdf][or thhis one]]
* Day 123:
** we finally understand big o notation mostly by watching a YouTube video
** Wait, based on this [[https://medium.com/@melekcharradi/understanding-state-machines-a-developers-guide-to-predictable-application-logic-d3df50e3e621][link]], im already implementing a state machine in my code, when I press r or t:
*** But its not enough, "events" should be the only way to move between states, not key presses
*** States should be mutually exclusive, no "isLoading" or "isError" at the same time. But how?
*** But the article uses a stupid (or good?) example of if-elses to switch to ensure "we are always in 1 state"
#+begin_src javascript

  // assuming Javascript enum's are defined

  class FormStateMachine {
    constructor() {
      this.state = STATES.IDLE;
    }

    transition(event) {
      const currentState = this.state;

      if (currentState === STATES.IDLE && event === EVENTS.SUBMIT) {
        this.state = STATES.SUBMITTING;
        return true;
      }

        // ... repeat ...

      console.warn(`Invalid transition: ${event} in state ${currentState}`);
      return false;
    }

    getState() {
      return this.state;
    }
  }

  const formMachine = new FormStateMachine();

  formMachine.getState(); // => idle

  formMachine.transition(EVENTS.SUBMIT); // => 'submitting'

  formMachine.transition(EVENTS.SUCCESS); // => 'success'

#+end_src
*** We can also have hierarchical or parallel states. Example of hierarchical states would use enum's  (and hacky if-elses like above) like these:
#+begin_src javascript

  const musicPlayerStates = {
  stopped: {},
  playing: {
    initial: 'normal',
    states: {
      normal: {},
      volumeAdjusting: {},
      seeking: {}
    }
  }
      
#+end_src
** Another state machine we should be reading
*** https://gameprogrammingpatterns.com/state.html
** A super cool article, that I found, [[https://medium.com/@nainia_ayoub/floating-point-accuracy-on-gpus-57d01ddc7b0b][floating point accuracy in GPUs]]
*** computers inherently, dont have a way to calculate division literally, so it usually boils down to addition and substraction operations (in the CPU).
*** An example,  (34 / 8) is done as  ((((34 - 8) - 8) - 8) - 8), until you have a quotient 4 and a remainder of 2
*** there are lots articles explaining reciprocal, but none of it made sense.
*** Remember the example above such as 34/8? Now imagine dividing a number > 1000. The quick word we need to remember is "iteration" as we read further
*** ULP (Unit in the Last Place) is the distance between floating-point numbers in a value (? I guess)
*** ULP gives you a scale-aware way to talk about error.
*** The value is not fixed
*** Around small values, representable numbers are tightly packed.
*** Around large values, they are farther apart.
*** the error is 1 ULP: the result is off by about one representable step at that magnitude.
*** ULP gives you a scale-aware way to talk about error.
*** Errors involving ULP shows up in:
**** iterative solvers
**** optimizers
**** physics simulations
**** ML training loops with very small learning rates
**** Nothing is “wrong” with the code. The stopping condition simply lives at the precision limit.
**** Most real life effective numerical algos rely on the convergence test
#+begin_quote

stop when |x_new − x_old| < ε

#+end_quote
**** The usual ULP expected is <=0.5 ULP. But in real life, some algos dance around 102 ULP
* Day 124:
** https://developer.download.nvidia.com/assets/gamedev/docs/TransformAndLighting.pdf
*** NVIDIA transform and lighting
*** 3D is ultimately complex, so different frames of reference (different coordinate systems) is important to handle this data
*** the different coordinate systems are world, eye, screen but since, coordinate systms are different, data must be "transformed" as it travels through the pipeline
*** In this article we are STILL talking about Graphics Pipeline but in an NVIDIA context
*** Its still important, coz its VERY accessible
* Day 125:
** Original [[https://github.com/jwiegley/use-package#notes-about-lazy-loading][article]] on use-package:
*** (use-package) implies (require) only if package is in system
*** init: misnomer, run code before package is loaded
*** init: OVERWRITES lazy loading, takes precendence
*** config: misnomer, run code before package loads
*** config: SUBMITS to lazy loading
*** you can actually nest (use-package)
*** autoload: Its all about loading a file. Registers the location of the file, function is never loaded, once a function is called/etc..., the file is loaded
*** use-package always autoloads, and its implied such as in this command:
  #+begin_src emacs-lisp

    (use-package ace-jump-mode
  :bind ("C-." . ace-jump-mode))

#+end_src
*** bind-keymap: example
  #+begin_src emacs-lisp

    (use-package projectile
  :bind-keymap
  ("C-c p" . projectile-command-map))

#+end_src
*** the article does a better job explainign this stuff, but we can think of it "2 layers of deferring evaluation"
** After all that however, we learnt from [[https://batsov.com/articles/2025/04/17/using-use-package-the-right-way/][Batsov]] that its much better practice to actually to remove :init, :config, and move most of the code over to, such as, :bind, :hook, :custom, etc.. Most of these already have implied "defer loading"
* Day 126:
** [[https://www.escapistmagazine.com/realistic-graphics-are-broken/][realistic graphcis are broken]]
*** console makers are still selling us systems based on how good the game looks
*** realistic graphics are a dead end, becoz of many reasons, uncanny valley, higher production costs, diminishing returns with photo realism.
*** but most important of all, game mechanics havent caught up with graphics improvement, players cant react realistically
** But in the end, we DONT CARE about all this
** [[https://forums.escapistmagazine.com/threads/why-arent-graphics-done-as-vectors.255501/][why arent graphics done as vectors]]
*** drawing complex textures using mathematical operations instead of pixel is HIGHLY impractical
*** 1 guy implies an interesting fact, using a system of pixels, means that all movement can be done as linear transformations (matrix). Vector operations, on the hand, commonly require square root operations. Square root operations are one of the slowest computation for a computer. Imagine millions of such operations per frame!!
* TODO

TODO:
- https://community.khronos.org/t/glsl-clipping/59665
- there are many ways to do clipping in GLSL: simple scanline conversion (huh??)
- http://yummymelon.com/devnull/in-emacs-everything-looks-like-a-service.html
- in Emacs, everything looks like a service
- https://comp.anu.edu.au/courses/comp4610/assets/notes/slides_week_8.pdf
- Phong lighting model
- https://twodee.org/blog/17840
- lighting in eye space
- https://xoticpc.com/blogs/news/history-of-gpus?srsltid=AfmBOor8da8lUF7UfuEL_Xv7PwxIJvglqMS8jdKKI3ETKn-lQNqnaohR
  - history of GPU
- https://patents.google.com/patent/US6597363B1/en
- deferred shading shit
- https://www.cs.drexel.edu/~deb39/Classes/CS432/Assignments/a6.html
- interactive computer graphics assignment
- https://developer.download.nvidia.com/assets/gamedev/docs/TransformAndLighting.pdf
- NVIDIA Transform and Lighting Engine
- -----
- world, eye, screen coordinate
  - https://learnopengl.com/Getting-started/Coordinate-Systems
- world, eye, screen coordinate
- https://gamedev.stackexchange.com/questions/82494/why-is-h-blinn-used-instead-of-r-phong-in-specular-shading
- why is blinn used instead of phong
- https://alaingalvan.gitbook.io/a-trip-through-the-graphics-pipeline/chapter5-primitive-assembly
- Cool website, a trip through the graphics pipeline
- https://www.scratchapixel.com/lessons/3d-basic-rendering/perspective-and-orthographic-projection-matrix/building-basic-perspective-projection-matrix.html
- Also cool website, scratchapixel, perspective and orthographic projection
- https://gabrielgambetta.com/computer-graphics-from-scratch/09-perspective-projection.html
- A website on the book, Computer Graphics from Scratch
- he link is on perspective projection
- https://cientistavuador.github.io/articles/3_en-us.html
- I dont know what this one is about, strange and confusing
- https://medium.com/@breede/vex-ray-tracer-4-blinn-phong-shading-f0bf3042ba92
- Guy who personally implements Blinn-Phong Shading
- https://hero.handmade.network/forums/code-discussion/t/2479-using_opengl_uniforms_attributes_outputs_in_more_efficient_way
- handmadehero mention of efficient use of uniform/attributes/outputs
