* Day 80:
** added validation for my badass worklflow
** attempting to do my folding stool, discovered a loop
*** prepared tools, and material
*** started minor work
*** get tired, need minor project to stay motivated,
*** also minor project while all tools are out and messy
** We finally created proper UI for CSV.
*** https://medium.com/@ryan_forrester_/reading-csv-files-in-c-how-to-guide-35030eb378ad
*** We planned on separating the Upload File part from the Upload To DB part. This means Upload File part will have validations and checks and good feedback
*** Turns out uploading CSV's its own science and art.
*** We discover ranged loops, we are sticking to the immutable version, like this:
#+begin_src c++

    for(const auto& a_row : full_csv){
  // ==================================================    
    }

#+end_src
*** We discovered std::string appends are not the best (well, we got bugs), but also, we use overloaded + anyway, because appends modify by default (and return this*), but + dont do anything special, and just returns a new modified string
*** 
* Day 81:
** Played Chopin, recorded absolutely magnificent interpretation of Chopin Nocturne Op62.
** Best supportive Reddit comment
#+begin_quote

Wow this is such a radical interpretation, you’re about to move the whole classical world (and piss off some snobs) with such novelty and creativity. Anyone who says otherwise is just dismissive of your obvious genius.


I piss off on a small scale locally here, the conservatory and institution level, not worth it. Too much trouble and power dynamics.


I agree! But still if someday you change your mind, you’d do something great for humanity!


#+end_quote
* Day 82:
** tried a bit of Common Lisp 
** a Reddit comment somewhere said that we should habitualize using REPL, not running functions from file
** always run rlwrap before sbcl
** ASDF is a build system, but quicklisp manages external dependencies between Lisp systems
** 
* Day 83:
** there is no confusion between header declaration and the usage in .cpp. But we cant get our head around placement of & or *
#+begin_src c++

void UserCsvWidget::getFile__QStringList(QStringList& files){}

#+end_src
** we REALLY need to read the history of creation of & and *
** QStringList 
*** https://forum.qt.io/topic/143408/how-to-pass-and-simply-iterate-c-c
** in modern C++, the recommended alternatives to using raw pointers and explicit new/delete are standard library containers and smart pointers.
* Day 84:
** we mostly learnt Rust (advent of code) and did woodworking. We only planed wood for our folding stool. Not much progress
* Day 85:
** Discovered that we can define QList from std::initializer_list, and define QStringList from QList
** We can also define QStringList straight from curly brackets 
** Some examples:
#+begin_src c++

  QList<QString> testlist = {"1", ":2014"};

  QStringList testlist_better(testlist);

  // or we can do this

  QStringList fonts = { "Arial", "Helvetica", "Times" };

  // probably more

  

#+end_src
* Day 86:
** We only read Rust code so far.
** We attempted some basic file reading, but went nothing beyond that.
** We decided to stop for a while and just Rust docs, coz its worth especially our encountering of strange symbols (pipe, ?question mark)
** We finished planing a piece of wood, but that took literally 3 hours, when including rest and cleaning
* Day 87:
** We discovered that C++ compiler will actually STOP us from repeating definition of our parseCSVRow() function.
** We discovered that we only needed to add namespace, and we define it and use it exactly the same way (only difference: MyParser::)
** Theres boilerplate code for this. The usual header guards, but most important is the namespace
#+begin_src c++

  // we couldnt make it work without the namespace, but regardless, namespace is good practice
  namespace MyParser
  {
    std::vector<std::string> parseCSVRow(const std::string& row);
  }

#+end_src
** The rest is exactly the same
** Remember: One Definition Rule
* Day 88:
** We successfully ran a vecto function that successfully outputs to a png file
** We still havent done anything of significance with Common Lisp
* Day 89:
** We are struggling to learn Common Lips Recipes, but, things are looking up becoz we discovered Lisp is a very cool lang, with a history of GUI way ahead of its time. And other stuff we learnt
** common lisp
*** the symbol has its own properties like an object, even its own lifespan separate from the function or value it defines
*** this is very different from other traditional langs, where the "variables name/label/whateer" is the same as the function, so all are like the "same object" with a single lifespan
* Day 90:
** we fixed our sly keybindings, which still feels like magic by itself
* Day 91:
** We learnt about in-place modification, and its a topic too in C++. Is it worth it? And does it really improve performance by that much?
** there's a cool library called "algorithm" in cpp
* Day 92:
** We learnt QSqlQuery select from this one link, [[https://forum.qt.io/topic/71381/qsqlquery-select/3][qsqlquery select]]
** 
* Day 93:
** apart from evaluation, we attempted the same for our sql operation
** we realized, its not 1-to-1, coz SQL works by a search
** this means, we cant really do a function that "cleans a string before comparison"
** we are beginning to notice a pattern
** when we do search and comparison type operations between user interaction and DB, there needs to be a set rule or standard, for comparison, such as "always store as number" for a field, or "always a space before text" (spaces between are ignored by SQL usually)
* Day 94:
** we watched the Lisp video on constructing a list with conses
** we did the same with (list) and backquotes
** theres an important distinction, such as with (list we need ' to stop evaluating an uncreated name example: )
  #+begin_src emacs-lisp

    (list 'a 'b 'c)

    ;; instead of

    '( a b c)

#+end_src
** putting our "engineering is also history" cap on, this means '() is a short form
* Day 95:
** In order to indexOf("<some-field-name>") to work, we need a valid record. exec() simply prepares i guess, but first() or next() finally returns a valid record. (we spent too much time doing this)
** This seems counter-intuitive, it just means we dont know whats the purpose of exec()
#+begin_src c++

  if(query_getDepartmentId.exec()) {
    int fieldIndex = query_getDepartmentId.record().indexOf("id");
    qDebug() << "fieldIndex is -1 here" << fieldIndex;
    qDebug() << "isvalid is False here" << query_getDepartmentId.isValid();
    if(query_getDepartmentId.first()){	
      int fieldIndex = query_getDepartmentId.record().indexOf("id");
      qDebug() << "fieldIndex is a proper number here" << fieldIndex;
      qDebug() << "isvalid is True here" << query_getDepartmentId.isValid();
      QString someValue = query_getDepartmentId.value(0).toString();
    }
  }

#+end_src
* Day 96:
** what do we do today (coz we might accidentally delete this):
- we need to read this link: https://www.amyschlesener.com/posts/2020/04/increasing-ubuntu-partition/
- according to most, increasing partition is easy, but not shrinking
- install baobab for Hanifa's laptop, setup a .desktop file
- there's no God and there's no free will
- we need to learn some QML concept
  - https://doc.qt.io/archives/qt-5.15/qtquick-modelviewsdata-modelview.html
  - https://doc.qt.io/qt-6/qtqml-cppintegration-contextproperties.html
  - https://doc.qt.io/qt-6/qqmlcontext.html
  - https://forum.qt.io/topic/76162/how-to-write-in-a-text-label-made-in-qml/5
  - https://doc.qt.io/qt-6/qml-qtquick-mousearea.html
  - https://doc.qt.io/qt-6/qtqml-syntax-signals.html
  - to really get, which is not recommended, but we are a badass, so we will do it anyway. objectName is visible to the C++ meta-object system
    #+begin_src qml

      // MyItem.qml
      import QtQuick

      Item {
          Rectangle {
              objectName: "myTargetRect"
              width: 100; height: 100
              color: "blue"
          }
      }

      
    #+end_src
  - the main.cpp
#+begin_src c++

  // main.cpp
  #include <QQmlApplicationEngine>
  #include <QQuickItem>

  QQmlApplicationEngine engine;
  engine.load(QUrl("main.qml"));

  // 1. Get the root object (the Window or top-level Item)
  QObject *rootObject = engine.rootObjects().first();

  // 2. Search for the child by objectName
  QObject *rect = rootObject->findChild<QObject*>("myTargetRect");
  if (rect) {
      // 3. Cast to the specific type if needed (e.g., QQuickItem)
      QQuickItem *item = qobject_cast<QQuickItem*>(rect);
      item->setProperty("color", "red");
  }

#+end_src
  - the best advice is actually this: [[https://doc.qt.io/qt-6/qtqml-cppintegration-interactqmlfromcpp.html]["All QML methods are exposed to the meta-object system"]]
* Day 97:
** Tried cmake for the first time. The most important part of the CMakeLists.txt is acually target_link_libraries(hello PRIVATE Qt::Core Qt5::Widgets) and the Core and Widgets using find_package() is not enough
** 
* Day 98:
** we figured out how to org-notify in the simplest way possible, in short:
#+begin_quote

systemctl start --user dunst

#+end_quote
** And example eLisp:
#+begin_src emacs-lisp

  (defun ardie/bien-biel-que-el-paso-paso()
    (interactive)
    (print "bien bien peuded que si, puede que no")
    )

  (run-with-timer 2 10 'ardie/bien-biel-que-el-paso-paso)

#+end_src
* Day 99:
** based on our understanding of rvalue, lvalue and valid expressions like dest+3 or \*(dest+5), (as opposed to &(dest+5)) we can do something like this to change 3rd and 5th character
#+begin_src c

  char *call_me(char *dest, char *src){

      char *temp = dest+3;
      ,*temp = 'a' ;
      if(*(dest+5) == 'y'){
          char *temp2 = dest+5;
          ,*temp2 = '_' ;
      }

      return dest;
  }

  int main(void){
      char src[] = "hello";
      char dest[] = "goodbye";
      call_me(dest,src);
      printf("%s", dest);
      return 0;
  }

#+end_src
* Day 100:
** 
#+begin_quote

the steps in general looks like this, but we SHOULD REALLY try static linking, we havent tried it yet
- 

  we first create an object file. SAME with static, but we Position Independent Code

  gcc -c -fPIC mysource.c -o mysource.o

  we then create a static library using archiver. The archiver is a tool that can create input for the linker (think, linker was developed separate from compiler, and the logic behind it is almost completely different. Maybe its a separate paradigm/tool?)

  we can now link it

  gcc -o -shared mysource.so mysource.o

    this will not work

  gcc main.c -L. -lmylib

  this will work

  gcc main .c -L/home/ardie/location-of-library -Wl,-rpath=/home/ardie/location-... -o result mylib.c -lmylib

  Note how the -L is basically telling thje compiler to pass the options to the linker instead.

  mylib is some name coming from mylib.c and mylib.h, but the naming is convention, the true naming, im guessing, comes from #define MYLIB_H in the header file.

  so what does header file do in this case?

  anyway 

#+end_quote
** some links:
*** https://www.cprogramming.com/tutorial/shared-libraries-linux-gcc.html
*** https://www.geeksforgeeks.org/c/how-do-i-create-a-library-in-c/
*** Note how the the secind link uses 2 methof static and dynamic, and static doesnt work, but we SHOULD REALLY try..x
* Day 101
** Our Piscine is finished. What did we learnt so far:
*** we learnt that making an Emacs exam config, and writing it from the beginning was definitely worth it.
*** we learnt we have trouble separating life in shallow Sunway Uni, from reality of a brown man surviving in SEAsia.
*** we learnt that it was actually not that difficult or that destructive to modify most navigation keys to something radical (as long as its not Ctrl-M, that messes <return> coz Emacs does that to Ctrl-M)
*** we learnt that we still cant communicate our hatred of leetcode and corpo environment to the general public.
*** we learnt that I get nervous, and I still need help practicing talking to people
*** I learnt that I can do decent stuff in C.
*** I learnt much more badass stuff in C, as long as I take the time to learn and absorb
* Day 102
** 1st attempt at installing opengl, just to draw a bloody triangle
** downloading frmo nigel's github, only make (not cmake) works, (must build inside /auto). Why are they downloading stuff called "registry's"
** stuff like OpenGL-Registry, EGL-Registry, only then creating glew.h
** glew.h apparently is so important
** read this??:
*** https://stackoverflow.com/questions/12122631/difference-between-opengl-files-glew-h-and-gl-h-glu-h
* Day 103:
** Finally:
#+begin_quote

everything in programming is mostly history and linguistics than math, remember.


static-linking used to be common. Linux made it weird, and shamed people for statically linking, shared/dynamic linking is apparently better, even though memory is getting cheap.

Dynamically linking = runtime-ish

First some basics:
-I is for the compiler. Include files. Since includes are usually definitions, remember -> you cant have 1 (I)without the other (L). More or less. But usually gcc looks for libs by itself anyway.
-L is for the linker, and tells the location of library (directory)
-l is for the linker, and tells which library to use (file)

But -l comes with convention (yuck). -lhelper means look for libhelper.a or libhelper.so



Since, programming is history too, and dynamical linking came later. The gcc sometimes need more information.

remember dynamical linked means at runtime (saving space thingy), and -L only helps at compile/linking time. So you would still usually need LD_LIBRARY_PATH sometimes.

#+end_quote
** to read on [[https://www.reddit.com/r/opengl/comments/sskqmu/how_do_i_link_glfw_to_my_cc_program_in_linux/][reddit]]
*** apparently, you can use something like pkg-config, which is also a compiler-adjacent tool
** for using nm with shared object, dynamically linked stuff, you can use the -D option (nm -D)
* Day 104:
** what we're learning right now: https://learnopengl.com/Getting-started/Hello-Window 
* Day 105:
** C macros might pollute namespace (???)
** Notice how we create a "destructive-malloc-struct-creation" for our Person. Note how verbose it is. they keyword "struct" is everywhere, which is apparently a good thing
#+begin_src c

    struct Person * createNewStruct(){
      struct Person * sarah = (struct Person*)malloc(sizeof(struct Person));
      return sarah;
  }

  /* of course we can always start off with something simple, if we get lost */

  int* createNewStruct(){
      int *what = (int *)malloc(sizeof(int) * 5);
      return what;
  }

#+end_src
* Day 106:
** gcc actually looks at the NAME when running with the -l<some-random-lib> (example: -lmylib)
** GLAD and GLEW does the same exact thing. Dont include both (except for special reasons): [[https://community.khronos.org/t/problems-with-glad-and-glew-libraries/109452/5][khronos: GLAD and GLEW does the same thing]]
** we generate a GLAD header from this link: [[https://gen.glad.sh/][GLAD]]
** theres a Github example: https://github.com/dav1dde/glad
** for the includes, you must always put glad before the glfw3 headers ([[https://community.khronos.org/t/help-with-setting-up-glfw-with-glad/107258][glad before glfw3]])
** a very COOL link explainig what the true spirit of LD_LIBRARY_PATH, and some tips around, such as using env (rather than the export), or using a wrapper bash script. [[https://www.hpc.dtu.dk/?page_id=1180][hpc on ld_library_path]]
** We live in a small world, better have fun, being a badass at GCC flags?? [[https://blog.httrack.com/blog/2014/03/09/what-are-your-gcc-flags/][httrack blog on GCC flags]]
** 
* Day 107:
** this link makes much more sense:x
*** [[https://www.steinwurf.com/blog/error-while-loading-shared-libraries][steinwurf: on thinking through loading our shared library]]
** Thinking through:
#+begin_src shell

   gcc -fPIC -c readme.c # c: Creating object file, fPIC: position-independent-code

   gcc -shared -o readme.so readme.o # o: output file, -shared: create shared object


   # ----- and finally

   sudo ldconfig /home/ardie/my-personal-libs/shared-objects/

   # ----- note the the full file name is required, yes, this seems like OS-level stuff
   # ----- turns out you dont need LD_LIBRARY_CONFIG

#+end_src
** Useful to know, and to understand.
#+begin_src shell

  ldconfig -p | grep <some-lib-we-looking-for>

  # we know this
  sudo ldconfig /some/path/

  # lets look at the symbols, actually, nm is the dumber of the lot
  nm -D gl_ardie.so

  # more relevant for this task
  readelf -d /home/ardie/my-personal-libs/shared-objects/test.so | grep SONAME

  # seems similar t readelf, but looks better and more info, objdump can also do the same like nm using -D
  objdump -p libcurl.so.3.0.0 | grep SONAME

  # sometimes, grepping through the header files is much better

  cat /path/to/glad/gl.h | grep glad_glEvalMesh2


#+end_src
* Day 108:
** the process of compilation seems rather ugly, even though -l<some-lib-name> "seems" rather elegant, it feels very OS-ish, it seems like something the programmer should never touch, because you are dealing with ldconfig, which updates some cache that seems to be used SYSTEM-wide.
** doesnt feel right AT ALL
** actually, you can just use the full file name of the .so (shared object), but it quicly becomes super-long
** why does nobody say how weird this feels
** 
