* Day 80:
** added validation for my badass worklflow
** attempting to do my folding stool, discovered a loop
*** prepared tools, and material
*** started minor work
*** get tired, need minor project to stay motivated,
*** also minor project while all tools are out and messy
** We finally created proper UI for CSV.
*** https://medium.com/@ryan_forrester_/reading-csv-files-in-c-how-to-guide-35030eb378ad
*** We planned on separating the Upload File part from the Upload To DB part. This means Upload File part will have validations and checks and good feedback
*** Turns out uploading CSV's its own science and art.
*** We discover ranged loops, we are sticking to the immutable version, like this:
#+begin_src c++

    for(const auto& a_row : full_csv){
  // ==================================================    
    }

#+end_src
*** We discovered std::string appends are not the best (well, we got bugs), but also, we use overloaded + anyway, because appends modify by default (and return this*), but + dont do anything special, and just returns a new modified string
*** 
* Day 81:
** Played Chopin, recorded absolutely magnificent interpretation of Chopin Nocturne Op62.
** Best supportive Reddit comment
#+begin_quote

Wow this is such a radical interpretation, you’re about to move the whole classical world (and piss off some snobs) with such novelty and creativity. Anyone who says otherwise is just dismissive of your obvious genius.


I piss off on a small scale locally here, the conservatory and institution level, not worth it. Too much trouble and power dynamics.


I agree! But still if someday you change your mind, you’d do something great for humanity!


#+end_quote
* Day 82:
** tried a bit of Common Lisp 
** a Reddit comment somewhere said that we should habitualize using REPL, not running functions from file
** always run rlwrap before sbcl
** ASDF is a build system, but quicklisp manages external dependencies between Lisp systems
** 
* Day 83:
** there is no confusion between header declaration and the usage in .cpp. But we cant get our head around placement of & or *
#+begin_src c++

void UserCsvWidget::getFile__QStringList(QStringList& files){}

#+end_src
** we REALLY need to read the history of creation of & and *
** QStringList 
*** https://forum.qt.io/topic/143408/how-to-pass-and-simply-iterate-c-c
** in modern C++, the recommended alternatives to using raw pointers and explicit new/delete are standard library containers and smart pointers.
* Day 84:
** we mostly learnt Rust (advent of code) and did woodworking. We only planed wood for our folding stool. Not much progress
* Day 85:
** Discovered that we can define QList from std::initializer_list, and define QStringList from QList
** We can also define QStringList straight from curly brackets 
** Some examples:
#+begin_src c++

  QList<QString> testlist = {"1", ":2014"};

  QStringList testlist_better(testlist);

  // or we can do this

  QStringList fonts = { "Arial", "Helvetica", "Times" };

  // probably more

  

#+end_src
* Day 86:
** We only read Rust code so far.
** We attempted some basic file reading, but went nothing beyond that.
** We decided to stop for a while and just Rust docs, coz its worth especially our encountering of strange symbols (pipe, ?question mark)
** We finished planing a piece of wood, but that took literally 3 hours, when including rest and cleaning
* Day 87:
** We discovered that C++ compiler will actually STOP us from repeating definition of our parseCSVRow() function.
** We discovered that we only needed to add namespace, and we define it and use it exactly the same way (only difference: MyParser::)
** Theres boilerplate code for this. The usual header guards, but most important is the namespace
#+begin_src c++

  // we couldnt make it work without the namespace, but regardless, namespace is good practice
  namespace MyParser
  {
    std::vector<std::string> parseCSVRow(const std::string& row);
  }

#+end_src
** The rest is exactly the same
** Remember: One Definition Rule
* Day 88:
** We successfully ran a vecto function that successfully outputs to a png file
** We still havent done anything of significance with Common Lisp
* Day 89:
** We are struggling to learn Common Lips Recipes, but, things are looking up becoz we discovered Lisp is a very cool lang, with a history of GUI way ahead of its time. And other stuff we learnt
** common lisp
*** the symbol has its own properties like an object, even its own lifespan separate from the function or value it defines
*** this is very different from other traditional langs, where the "variables name/label/whateer" is the same as the function, so all are like the "same object" with a single lifespan
* Day 90:
** we fixed our sly keybindings, which still feels like magic by itself
* Day 91:
** 
