Since, approx, last year:
* First GP I met, as I asked for a sleeping pill. Told me to see a psychiatrist. This was a common dismissal, I will see repeated from Government Hospitals
* Due to monetary situation, I had trouble and avoided going clinics.
* Somewhere towards end of last year, I went to HKL after a severe pain throughout my whole body. I almost collapsed in a shopping mall, went to the nearest private clinic out of emergency, and doctor gave me strong medication, after I responded my pain being a level 7 (from 1 - 10). The pain at the time was usually throughout the whole body, extreme fatigue, but usualy pain in lower abdomen, accompanied by unusual bowel habits.
* In HKL, results returned normal, and some of the visits to doctors early on dismissed me as being depressed. This will be a repeated theme throughout.
* Pain would come and go, during this year (2022), often resulting in having trouble focusing on my new teaching job.
* Last month or 2, a severe level 10 pain made my father drive me to University Malayas own Hospital. The doctor confused by my reaction, initially called a psychiatrist who was convinced there was nothing wrong with me mentally (see?). Doctors decided on a Endoscopy or scope, but after 1 week of waiting, it was scheduled to next year. (another 6 months!!)
* Extreme fatigue made me quit my job for 1 day. My father was okay with supporting my Scope (top and bottom) at the Beacon Hospital. Diagnosed with something related to acid reflux and possibly IBS
* after 1 week of taking medication, the pain has not gone away. In fact, there would be pain before going to the toilet, and dietary fibre drink helps the digestion but not the pain. I am now strange shivers, random minor headaches, and random pins and needles as of Thursday (23/6/2022)
** Jasminder Kaur AP Karnail Singh (Gastroenterology & Hepatology)
*** Avoid:
**** Garlic
**** milk
**** wheat
** TEsts:
*** C-reactive protein
*** thyroid
*** calcium
** Medication:
*** Rifaximin NO
*** Duloxetine
