
* [[https://pmc.ncbi.nlm.nih.gov/articles/PMC8594559/][Linking creativity and false memory: Common consequences of a flexible memory system]]
** Some previous studies show that flexible episodic memory system (sometimes leading to memory errors) has functional benefits for creativity.
** If so, there SHOULD be a direct link between creativity and susceptibility to memory distortion.
** However, previous studies examining such a link have yielded inconclusive results??
* https://pubmed.ncbi.nlm.nih.gov/20951630/
** we already know that, the usual the usual "recollecting" "hardens" neurons, and spaced repetition moves short-term memory to long-term
** this article, adds, that "tests" and "exams" are commonly accepted, as assessing our knowledge, and true learning is when we "study"
** this is FALSE, as tests that encourage retrieval enhance mnemonics
** this retrieval is still beneficial, even without the correct answer.
** the power of retrieval practice is useful consolidating memory, and useful for education practices
* [[https://www.sciencedirect.com/science/article/abs/pii/S0306453016301354][stress in the zoo]]
** we learnt new things such as the important region of the brain responsible for memory formation is the amygdala and hippocampus
** there is the fast acting sympathetic nervous system (releases catetholamines), and slow acting axis (releases cortisol)
** the slow one seems to encourage memory retention, but only for a short while, then the slow axis, inhibits memory retention. 
* we need to look for articles on convergent and divergent thinking as it relates to creative false memories
* [[https://www.harvardmagazine.com/2025/01/harvard-study-memory-creative-thinking][is memory connected to creativity]]
** Despite our fatigue of memory (no thanks to fetishization of short term Exams such as in our culture), some are disgusted by the idea of putting value in memory. But this is not the same thing.
** Creativity might be related to episodic memory, or ability to relive (id like to call it retrieve), specific moments from past experience
** An interesting read is the 2001 book "The Seven Sins of Memory: How the Mind Forgets and Remembers"
** referring to a recent research involving "episodic simulation", aka how the human constructs simulations of past and future events
** It refers to a study, of an accident patient with a severe case of amnesia, with shattered "episodic memory", unable to recall personal past experiences, but his "general knowledge" was fine.
** Most interestingly, when asked what he would to tomorrow, he was unable to plan for the future. Study suggest a strong link between, remembering the past and envisioning the future
** Led to formation of "constructive episodic simulation hypothesis", merging pieces of the past ideas of the future.
** Study involving an "induction" test, where non-control subjects did a recall experiment, reveal more detailed innovative ideas
** 2 types of creative thinking: divergent creative thinking and convergent creative thinking
** But it comes with a trade-off, subjects with higher divergent creative thinking, showed "memory distortions", adding false details 
